fuzzing: initial fuzzing implementation
coconut-svsm/svsm pull request #113
Opened 2023-10-02 18:21 UTC by 00xc

This PR adds:
* Basic fuzzing infrastructure via `cargo-fuzz`.
* Two harnesses, for the firmware metadata (`fw_meta`) and ACPI table parsing respectively.
* Relevant documentation.

Works towards #34

2023-10-12 13:21 UTC, joergroedel requested changes
I made a few comments, but besides those this looks good overall. Thanks for working on fuzzing, it already uncovered some bugs.

2023-10-12 13:21 UTC, joergroedel commented on FUZZING.md
> +[rust-fuzz website](https://rust-fuzz.github.io/book/cargo-fuzz.html).
Can you please add a section describing the dependencies and how install them on openSUSE? For me it was `cargo-fuzz`, `clang` and `lld`.

2023-10-12 13:21 UTC, joergroedel commented on src/acpi/tables.rs
> +        }
Why is that needed?

2023-10-12 13:21 UTC, joergroedel commented on src/acpi/tables.rs
> +        }
Same here, why is that needed?

2023-10-12 13:21 UTC, joergroedel commented on src/acpi/tables.rs
> +            0 if entry_len == mem::size_of::<RawMADTEntryLocalApic>() => {
This looks like a fix for an issue found by fuzzing. Can you please submit all such fixes in a separate PR, please? We can merge them independently of the fuzzer itself.

2023-10-12 13:21 UTC, joergroedel commented on src/fw_cfg.rs
> +
This does not need to be limited to fuzzing. I think we can safely assume a maximum supported buffer size for the fw_cfg file-list.

2023-10-12 13:29 UTC, 00xc commented on src/acpi/tables.rs
> +        }
Because the size is a hypervisor-controlled value. Since we are fuzzing from the perspective of a malicious hypervisor, we would potentially be allocating thousands of bytes on each fuzzing iteration, which would slow down the fuzzer greatly with little to no additional coverage.

2023-10-12 13:34 UTC, 00xc commented on src/fw_cfg.rs
> +
I was not sure this would make sense in regular builds, as the [only size limited imposed by qemu](https://www.qemu.org/docs/master/specs/fw_cfg.html#file-directory-key-0x0019-fw-cfg-file-dir) is `u32::MAX`. However I would agree that it would not make much sense to have such amount of files. Should we just set the limit it to 4096 for all builds?

2023-10-12 13:59 UTC, 00xc commented on src/acpi/tables.rs
> +            0 if entry_len == mem::size_of::<RawMADTEntryLocalApic>() => {
Opened #125

2023-10-12 13:59 UTC, 00xc commented on FUZZING.md
> +[rust-fuzz website](https://rust-fuzz.github.io/book/cargo-fuzz.html).
Done in the new version

2023-10-13 09:48 UTC, 00xc commented on src/fw_cfg.rs
> +
Okay, so this one is about the number of files in a directory. There's two others:
* The size of the `etc/acpi/tables` file.
* The size of an ACPI table, obtained from a field in the header (`RawACPITableHeader`).

Should we limit these as well for all builds? Same limit values?

2023-10-13 12:12 UTC, joergroedel commented on src/fw_cfg.rs
> +
> Okay, so this one is about the number of files in a directory. There's two others:
> 
>     * The size of the `etc/acpi/tables` file.

For that we can probably set a limit to 128KiB, that is the current size. Maybe also 256KiB, we can't allocate more via the allocator anyway.

>     * The size of an ACPI table, obtained from a field in the header (`RawACPITableHeader`).

Here we can just check that the size + offset of the table fully fits into buffer read from the `etc/acpi/tables` file.

2023-10-14 11:22 UTC, 00xc commented on src/fw_cfg.rs
> +
- File amount limited to 4096.
- `etc/acpi/tables` file size limited to 128 KiB.
- ACPI table size not limited, as we first try to get a slice to the buffer according to its announced length.

2023-10-14 11:35 UTC, 00xc commented
Also made `parse_fw_meta_data()` unsafe, as the caller must guarantee that the provided `VirtAddr` is valid and points to a region of the adequate size (4k).

2023-10-18 09:38 UTC, 00xc commented
Last version: rebased on main and fixed the ACPI harness to accommodate the new `Sync` bound for the `IOPort` trait.

2023-10-18 19:38 UTC, Freax13 requested changes

2023-10-18 19:38 UTC, Freax13 commented on fuzz/fuzz_targets/fs.rs
> +}
```suggestion
fn get_idx<T>(v: &[T], idx: usize) -> Option<usize> {
    idx.checked_rem(v.len())
}
```

2023-10-18 19:38 UTC, Freax13 commented on fuzz/fuzz_targets/fs.rs
> +}
```suggestion
/// A handle for a file that also holds its original name
#[derive(Debug)]
struct Handle<'a> {
    fd: FileHandle,
    name: &'a str,
}
```

Allocating into an `Rc` is not needed here.

2023-10-18 19:38 UTC, Freax13 commented on fuzz/fuzz_targets/fs.rs
> +fn get_idx<T>(v: &[T], idx: usize) -> Option<usize> {
All callers except one then go on to use the returned index to index into the slice. Have you considered just returning a `Option<&T>` instead of `Option<usize>`?

2023-10-18 19:38 UTC, Freax13 commented on src/fw_meta.rs
> +pub unsafe fn parse_fw_meta_data(vstart: VirtAddr) -> Result<SevFWMetaData, SvsmError> {
Should this function maybe just take a `&RawMetaBuffer` or `&[u8]`?

2023-10-18 20:01 UTC, 00xc commented on fuzz/fuzz_targets/fs.rs
> +fn get_idx<T>(v: &[T], idx: usize) -> Option<usize> {
Fixed in v2.

2023-10-18 20:01 UTC, 00xc commented on fuzz/fuzz_targets/fs.rs
> +}
Fixed in v2.

2023-10-18 20:06 UTC, 00xc commented on src/fw_meta.rs
> +pub unsafe fn parse_fw_meta_data(vstart: VirtAddr) -> Result<SevFWMetaData, SvsmError> {
`RawMetaBuffer` is private, so I would avoid that. A `&[u8]` would be better I think, that way we can check the length. With that I think we can avoid the `unsafe`, since `RawMetaBuffer` is `#[repr(C, packed)]`, which means there are no alignment requirements.

2023-10-18 20:17 UTC, Freax13 commented on src/fw_meta.rs
> +pub unsafe fn parse_fw_meta_data(vstart: VirtAddr) -> Result<SevFWMetaData, SvsmError> {
> `RawMetaBuffer` is private, so I would avoid that. A `&[u8]` would be better I think, that way we can check the length. With that I think we can avoid the `unsafe`, since `RawMetaBuffer` is `#[repr(C, packed)]`, which means there are no alignment requirements.

Sure, sounds good to me. 

I know y'all don't like adding external dependencies, but [`bytemuck`](https://docs.rs/bytemuck/latest/bytemuck/) is a really good crate that, among other things, makes it possible to easily and safely [convert byte slices to Rust types](https://docs.rs/bytemuck/latest/bytemuck/fn.from_bytes.html).

2023-10-18 20:28 UTC, 00xc commented on src/fw_meta.rs
> +pub unsafe fn parse_fw_meta_data(vstart: VirtAddr) -> Result<SevFWMetaData, SvsmError> {
Yeah there's also [zerocopy](/google/zerocopy), I've used it for the [PackIt](/coconut-svsm/packit) crate. I'm not sure how they compare to one another, but for now we can live without them I think. Definitely something to consider if we get more parsing-intensive code in the future.

2023-10-20 05:41 UTC, Freax13 approved these changes
Looks good to me!

2023-10-20 05:41 UTC, Freax13 commented on src/fw_meta.rs
> +    // We have also verified that the size of the slice matches.
Great job on the safety comments!

2023-10-20 05:43 UTC, Freax13 commented on src/fw_meta.rs
> +pub unsafe fn parse_fw_meta_data(vstart: VirtAddr) -> Result<SevFWMetaData, SvsmError> {
> Yeah there's also [zerocopy](/google/zerocopy), I've used it for the [PackIt](/coconut-svsm/packit) crate. I'm not sure how they compare to one another, 

I haven't used zerocopy, but AFAICT bytemuck can do more than zerocopy. They are pretty similar though.

> but for now we can live without them I think. Definitely something to consider if we get more parsing-intensive code in the future.

Fair enough. Definitively shouldn't be part of this pr anyways since it's unrelated to fuzzing.

2023-10-20 07:49 UTC, 00xc commented on src/fw_meta.rs
> +    // We have also verified that the size of the slice matches.
Thanks!

2023-10-20 12:36 UTC, 00xc commented
Dropped `fuzzing: limit hypervisor-controlled allocation sizes` in favor of #140. With that this PR has no unrelated commits.

2023-10-23 09:52 UTC, joergroedel approved these changes
Looks good now.

2023-10-23 09:52 UTC, merged