mm: stack: Add unit tests
coconut-svsm/svsm pull request #126
Opened 2023-10-12 15:19 UTC by Zildj1an

Add basic unit tests for the stack. This is a start to adding unit tests to all memory components.

2023-10-13 07:43 UTC, joergroedel requested changes
Thanks for adding this test. I left a few comments.

2023-10-13 07:43 UTC, joergroedel commented on src/mm/stack.rs
> +        assert_eq!(0xFFFFFFC000000000, bits);
The constant here looks like it can be expressed based on `SVSM_SHARED_STACK_BASE`

2023-10-13 07:43 UTC, joergroedel commented on src/mm/stack.rs
> +        };
And the expected base can be easier calculated using one of the STACK_SIZE or STACK_PAGES constants. Otherwise this test will always need adoption when we change the stack layout.

2023-10-16 16:14 UTC, Zildj1an commented
> Thanks for adding this test. I left a few comments.

Thanks for the feedback @joergroedel I have updated the test

2023-10-18 08:59 UTC, joergroedel approved these changes
Looks good now. Will merge once I am back at my test machine.

2023-10-23 09:28 UTC, merged