task, percpu: Use VMR to manage the task pagetable and VMKernelStack to allocate the task kernel stack
coconut-svsm/svsm pull request #136
Opened 2023-10-18 10:10 UTC by roy-hopkins

Now that virtual memory ranges and page table entries can be managed using the new `VMR` and associated structs, update the Task structure implementation to manage the task pagetable using these new capabilities.

The task structure now includes a `VMR` instance that defines the virtual address range for the task. The kernel stack for the task is created using `VMKernelStack` and added to the task VMR. This is applied to the task pagetable during creation.

`PerCpu` already includes a per cpu VMR. This needs to be applied to the task when it is context switched onto the CPU. Currently this is done directly by copying the PerCpu level 3 index. This patch adss the function `populate_page_table()` to PerCpu which applies the PerCpu VMR to the pagetable instead.

2023-10-18 12:34 UTC, roy-hopkins commented
You can see this being used in #64

2023-10-24 13:02 UTC, joergroedel requested changes
Looks good overall, thanks. I requested one change and made one suggestion for the mapping guard (but it is fine as-is for now).

2023-10-24 13:02 UTC, joergroedel commented on src/task/tasks.rs
> +    vm_range: VMR,
This needs a more specific name, as it covers the kernel VMR. We will get another VMR for user-space in the same structure. Maybe `vm_kernel_range`?

2023-10-24 13:02 UTC, joergroedel commented on src/cpu/percpu.rs
> +}
Maybe we can look into making this more generic to work with any VMR instance. This requires taking a reference to the VMR within the struct and lifetime annotations. But this is just a note, no requirement for this PR.

2023-10-24 15:08 UTC, roy-hopkins commented on src/task/tasks.rs
> +    vm_range: VMR,
Renamed as suggested.

2023-10-24 15:09 UTC, roy-hopkins commented on src/cpu/percpu.rs
> +}
I didn't really like that struct sitting there in percpu.rs so as suggested I've added the generic function using a couple of new commits. Please take a look.

2023-10-27 08:19 UTC, joergroedel approved these changes
Looks good now, thanks!

2023-10-27 08:19 UTC, merged