docs: Add documentation style guidelines
coconut-svsm/svsm pull request #141
Opened 2023-10-24 13:29 UTC by Zildj1an

Add documentation style guidelines within CONTRIBUTING.md to help clarify our expectations from a documentation standpoint. Co-developed by @00xc.

2023-10-24 13:31 UTC, Zildj1an commented
Unrelated to this commit, apparently the SignedOff check can't understand multiple signatures:

```
From https://github.com/coconut-svsm/svsm
 * branch            main       -> FETCH_HEAD
Checking b08ee52ee93c8fdac56a31df3a1fca99d3a064b1
Author name mismatch on commit b08ee52ee93c8fdac56a31df3a1fca99d3a064b1
    Commit author name: Carlos Bilbao
    Signed-off-by name: Carlos López
Carlos Bilbao
Error: Process completed with exit code 1.
```

2023-10-24 13:42 UTC, 00xc commented
> Unrelated to this commit, apparently the SignedOff check can't understand multiple signatures:
> 
> ```
> From https://github.com/coconut-svsm/svsm
>  * branch            main       -> FETCH_HEAD
> Checking b08ee52ee93c8fdac56a31df3a1fca99d3a064b1
> Author name mismatch on commit b08ee52ee93c8fdac56a31df3a1fca99d3a064b1
>     Commit author name: Carlos Bilbao
>     Signed-off-by name: Carlos López
> Carlos Bilbao
> Error: Process completed with exit code 1.
> ```

I'll look into this

2023-10-24 14:40 UTC, 00xc commented
> You're absolutely correct, but, I would prefer not to close and open a new PR if the commit already has the correct signatures. Is it possible to proceed with the existing PR?

Yes, you just need to amend the commit with the correct email and force push, no need to open a new PR :)

This should work:

```console
$ git commit --author="Name <email>" --amend --no-edit && git push origin your_branch --force
```

2023-10-24 14:43 UTC, 00xc commented
In the meantime I opened #142 so this does not fail in the future.

2023-10-25 16:03 UTC, 00xc approved these changes

2023-10-27 08:15 UTC, joergroedel requested changes
Please also create a separate `Documentation/` directory and put this guide into a separate file there. With the directory we can also move other general (non auto-generated) documentation files there.

2023-10-27 08:15 UTC, joergroedel commented on CONTRIBUTING.md
> +  changes. Your new documentation should be warning-free.
Can you please add examples for best practices here? It makes it much easier for contributors.

2023-10-31 12:29 UTC, 00xc commented
Once @joergroedel's comments are addressed the new version of `check-signed-off.sh` should run, removing the CI failure.

2023-10-31 15:47 UTC, Zildj1an commented
I have made the requested changes @joergroedel. Looks like there's still an issue with the CI @00xc?

2023-10-31 21:08 UTC, 00xc commented on README.md
> +for documentation guidelines to [DOC-GUIDELINES.md](Documentation/DOC-GUIDELINES.md).
```suggestion
guidelines please have a look at [CONTRIBUTING.md](CONTRIBUTING.md).
For documentation guidelines consult [DOC-GUIDELINES.md](Documentation/DOC-GUIDELINES.md).
```

2023-11-01 19:37 UTC, Zildj1an commented on README.md
> +for documentation guidelines to [DOC-GUIDELINES.md](Documentation/DOC-GUIDELINES.md).
Done!

2023-11-03 12:18 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +```
By the way, I just realized that running clippy in pedantic mode (`cargo clippy --all -- -W clippy::all -W clippy::pedantic`) will warn you about these. For example:

```
warning: docs for function which may panic missing `# Panics` section
   --> src/svsm.rs:325:1
    |
325 | pub extern "C" fn svsm_start(li: &KernelLaunchInfo, vb_addr: usize) {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: first possible panic found here
   --> src/svsm.rs:332:9
    |
332 |         launch_info.kernel_region_phys_start.try_into().unwrap(),
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc
```

I don't think we'll be running pedantic mode in our CI anytime soon, as there's just too many warnings, but maybe worth mentioning.

2023-11-09 15:14 UTC, Zildj1an commented
> I have some additional comments. As for examples, I would perhaps have smaller more specific examples for each point that requires one.

Thanks @00xc  I applied the suggested changes.

2023-11-09 17:33 UTC, 00xc requested changes
There are still things we can cleanup, I have added more suggestions.

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +
```suggestion
/// This function does A, takes parameter of type [`M`].
/// It returns [`B`], keep in mind C
fn main(a: M) -> B {
     // Some code here
}
```

Note there is also an extra newline that we do not need.

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +/// 1. The pointer `data` must be valid and properly allocated memory.
```suggestion
/// 1. The pointer `data` must point to valid memory.
```

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +///   `data`.
```suggestion
/// 2. The length `len` must accurately represent the number of bytes in
///   `data`.
```

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +/// 3. The caller must also ensure that the memory is correctly initialized
```suggestion
/// 3. `src` must be correctly initialized.
```

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +    assert!(!dest.is_null() && !src.is_null());
The function should have a `# Panics` section in this case. We can even merge this example with the one below.

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +    unsafe {
The function is already unsafe, so there is no need for this unsafe block as far as I know.

2023-11-09 17:33 UTC, 00xc commented on Documentation/DOC-GUIDELINES.md
> +/// it will panic.
I would simply say:

```suggestion
/// The function will panic if the provided length exceeds the buffer's capacity.
```

2023-11-20 14:12 UTC, joergroedel commented
Will merge it now, please send any updates on top of this.

2023-11-20 14:12 UTC, joergroedel approved these changes
LGTM

2023-11-20 14:23 UTC, joergroedel commented
Merged manually. Closing.

2023-11-20 14:23 UTC, closed without merging