mm: Add unit tests for kernel mapping, guestmem ops, address checks
coconut-svsm/svsm pull request #170
Opened 2023-11-29 15:00 UTC by Zildj1an

Add unit tests to evaluate offline correct behavior of memory components: kernel mappings (address_space.rs), read and write operations (guestmem.rs) and valid physical address checking (memory.rs).

2023-11-29 18:18 UTC, 00xc requested changes
At least one test is failing inside the SVSM, so we need that fixed at the minimum. I would also really want the Miri addition to go in, as I'm running Miri tests nightly.

2023-11-29 18:18 UTC, 00xc commented on src/mm/guestmem.rs
> +    fn test_read_u8_valid_address() {
This ends up using inline assembly, so Miri cannot handle it.

```suggestion
    #[test]
    #[cfg_attr(miri, ignore)]
    fn test_read_u8_valid_address() {
```

2023-11-29 18:18 UTC, 00xc commented on src/mm/guestmem.rs
> +        let result = read_u8(VirtAddr::new(test_address)).unwrap();
Nit: instead of using "as" casting, you can simply do:

```suggestion
        let test_address = VirtAddr::from(test_buffer.as_ptr());

        let result = read_u8(test_address).unwrap();
```

2023-11-29 18:18 UTC, 00xc commented on src/mm/guestmem.rs
> +    fn test_write_u8_valid_address() {
```suggestion
    #[test]
    #[cfg_attr(miri, ignore)]
    fn test_write_u8_valid_address() {
```

2023-11-29 18:18 UTC, 00xc commented on src/mm/guestmem.rs
> +        write_u8(VirtAddr::new(test_address), data_to_write).unwrap();
Nit: same here, instead of 'as' casting:

```suggestion
        let test_address = VirtAddr::from(test_buffer.as_mut_ptr());
        let data_to_write = 0x42;

        write_u8(test_address, data_to_write).unwrap();
```

2023-11-29 18:18 UTC, 00xc commented on src/mm/address_space.rs
> +    }
This test fails inside the SVSM when calling `phys_to_virt()` in this panic:

https://github.com/coconut-svsm/svsm/blob/be10d1b5ef8f4365434238e916623f14b59359d5/src/mm/address_space.rs#L43-L47

I suspect some of the other tests might also fail.

2023-11-30 14:48 UTC, Zildj1an commented
> At least one test is failing inside the SVSM, so we need that fixed at the minimum. I would also really want the Miri addition to go in, as I'm running Miri tests nightly.

I foresee the complexity of these and future tests growing considerably if we want all to be able to run inside the SVSM. My intention when I wrote and added these tests was to run them offline. For example, I need to either implement new functions that use `KERNEL_MAPPING_TEST` instead, or I have to consider the ramifications of using `KERNEL_MAPPING` uninitialized, etc. So I'm wondering, Is there a way we can leave some tests for offline testing only?

2023-11-30 14:52 UTC, 00xc commented
> I foresee the complexity of these and future tests growing considerably if we want all to be able to run inside the SVSM. My intention when I wrote and added these tests was to run them offline. For example, I need to either implement new functions that use `KERNEL_MAPPING_TEST` instead, or I have to consider the ramifications of using `KERNEL_MAPPING` uninitialized, etc. So I'm wondering, Is there a way we can leave some tests for offline testing only?

Yes, there are already some tests that are ignored inside the SVSM, for example in `mm/alloc.rs`. You can do that with:

```rust
#[test]
#[cfg_attr(test_in_svsm, ignore = "<REASON>")]
fn my_test() {}
```

I think you can also omit the reason.

2023-11-30 15:06 UTC, Zildj1an commented on src/mm/guestmem.rs
> +    fn test_read_u8_valid_address() {
Not sure if this is really needed anymore if we do `#[cfg_attr(test_in_svsm, ignore = "<REASON>")]` but including just in case

2023-11-30 15:12 UTC, Zildj1an commented on src/mm/guestmem.rs
> +        let result = read_u8(VirtAddr::new(test_address)).unwrap();
Good! thanks

2023-11-30 15:40 UTC, closed without merging

2023-11-30 15:45 UTC, Zildj1an commented
> > I foresee the complexity of these and future tests growing considerably if we want all to be able to run inside the SVSM. My intention when I wrote and added these tests was to run them offline. For example, I need to either implement new functions that use `KERNEL_MAPPING_TEST` instead, or I have to consider the ramifications of using `KERNEL_MAPPING` uninitialized, etc. So I'm wondering, Is there a way we can leave some tests for offline testing only?
> 
> Yes, there are already some tests that are ignored inside the SVSM, for example in `mm/alloc.rs`. You can do that with:
> 
> ```rust
> #[test]
> #[cfg_attr(test_in_svsm, ignore = "<REASON>")]
> fn my_test() {}
> ```
> 
> I think you can also omit the reason.

Thanks, I'm doing this, opening new clean PR