Optimize creation of the memory heap
coconut-svsm/svsm pull request #178
Opened 2023-12-11 21:28 UTC by msft-jlange

When the heap free list is first constructed, the list of pages is divided into a region of free page groups, one of which is aligned to a multiple of the size of the maximum free order, and the others are unaligned head/tail regions.  The aligned group is freed directly to the maximum order bucket, which avoids the need to do neighbor searching in order to construct the large buckets.  No similar optimization is performed on intermediate sizes of the unaligned head/tail regions because they are too small to worry about.

2023-12-14 10:00 UTC, joergroedel requested changes

2023-12-14 16:21 UTC, msft-jlange commented on src/mm/alloc.rs
> +            }
I see what you mean.  This should be simple to fix and I should have an update for you soon.

2023-12-15 09:17 UTC, joergroedel approved these changes

2023-12-15 09:17 UTC, joergroedel commented on src/mm/alloc.rs
> +                self.mark_compound_page(i, MAX_ORDER - 1);
Thanks, looks good now.

2023-12-15 09:18 UTC, merged