cpu/vc: handle faults when fecthing instructions
coconut-svsm/svsm pull request #295
Opened 2024-03-15 11:11 UTC by p4zuu

Faults can happen in the #VC handler if the exception context RIP (more generally the [RIP; RIP+15] array) doesn't belong to a mapped page.

To handle these faults, we can rely on GuestPtr::read() that uses the exception table if a fault occurs.

This touches the #VC handler, so I would wait for #288 to be merged to correctly test this PR.

2024-03-15 13:01 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    }
This looks good. While you are at it, you could probably add another test that reads invalid memory and that only runs inside the SVSM.

2024-03-15 13:04 UTC, p4zuu commented on kernel/src/cpu/insn.rs
>  }
You mean adding an `#[inline]` attribute or get rid of the `insn_fetch()` additional layer? I chose to leave it to make it clear that this is the instruction fetching part, but calling `read()` directly is probably clear enough :)

2024-03-15 13:05 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    }
Yes good idea!

2024-03-15 13:09 UTC, 00xc commented on kernel/src/cpu/insn.rs
>  }
Yes I meant removing the function directly. You could just add a comment that explains what that line does if you feel it's not clear enough.

2024-03-15 14:59 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    }
I added 2 new tests, but `make test-in-svsm` is currently broken on my environment.

2024-03-15 15:29 UTC, 00xc requested changes
Just a couple of comments, other than that this LGTM.

2024-03-15 15:29 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    }
This test fails - the memory beyond the allocated page is not lent by the allocator, but it's mapped as part of its memory region. I suggest you simply remove this test.

2024-03-15 15:29 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    }
Could you move this into the new commit adding tests?

2024-03-18 08:35 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    }
I wanted to test the case where we fetch memory straddling on both mapped and unmapped memory, but that's maybe far-fetched.

2024-03-18 08:40 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    }
You could perhaps use a `PerCPUMappingGuard` to map a previously unmapped region to do that. Otherwise I'd say just remove the test.

2024-03-18 09:07 UTC, 00xc approved these changes

2024-03-18 09:07 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    }
Done

2024-03-18 09:08 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    }
I removed it :)

2024-03-19 13:58 UTC, merged