Make read/write methods from GuestPtr unsafe, and copy_{from, to} methods from SecretsPage as well
coconut-svsm/svsm pull request #382
Opened 2024-06-14 08:30 UTC by p4zuu

Leaving as draft because I still have doubts.

Providing partial fix for #359 (tasks 7, 8, 9).

My two interrogations are:

1. There are several uses of the following pattern:
```rust
    let guard = PerCPUPageMappingGuard::create_4k(paddr)?; // paddr possibly guest or HV controlled
    let start = guard.virt_addr();
    let guest_page = GuestPtr::<Tt>::new(start + offset);
    let mut request = unsafe { guest_page.read()? };
``` 
As already discussed with @00xc, if `start + offset` is valid but `start + offset + size_of::<T>` ends on an unmapped page or on an adjacent page belonging to another guest or the SVSM kernel (I don't really know if it's possible), `read()` could raise a #PF and possibly return an error and panicking, or reading content from an unauthorized page. If such scenarii are possible, we should either:
- check that `start +  offset + size_of::<T>` doesn't cross the page end
- allow `GuestPtr::read()/write()` for partial read/write
- more general, we should always check that a guest or the HV can't force `GuestPtr::read()/write()` to return an error that will be treated as a fatal error by the SVSM kernel (that would be valid DoS).

2. In some core protocol handlers, a guest provides a physical address (example the [pvalidate](https://github.com/coconut-svsm/svsm/blob/75b83b3e1a5c860a84ccfe0e4b503e7efee5834f/kernel/src/protocols/core.rs#L312) handler), if I understand the code correctly, the guest-provided physical address pointing to the request entries is only verified if it's mapped or not. My understanding is that a guest could make the kernel read at any mapped address to fetch the `PValidateRequest` (including the kernel memory). Moreover, the guest-provided entries suffer from the same issue, the `paddr` to pvalidate are only verified to be mapped. A guest could make the SVSM kernel pvalidate any page. For the core protocol handlers that work with guest-provided paddrs, my understanding is that we should validate that paddrs only belong to the guest's memory region. I left TODOs is some places (not all of them) to points where there is this issue.

2024-06-17 11:13 UTC, 00xc commented
> Leaving as draft because I still have doubts.
> 
> Providing partial fix for #359 (tasks 7, 8, 9).
> 
> My two interrogations are:
> 
> 1. There are several uses of the following pattern:
> 
> ```rust
>     let guard = PerCPUPageMappingGuard::create_4k(paddr)?; // paddr possibly guest or HV controlled
>     let start = guard.virt_addr();
>     let guest_page = GuestPtr::<Tt>::new(start + offset);
>     let mut request = unsafe { guest_page.read()? };
> ```
> 
> As already discussed with @00xc, if `start + offset` is valid but `start + offset + size_of::<T>` ends on an unmapped page or on an adjacent page belonging to another guest or the SVSM kernel (I don't really know if it's possible), `read()` could raise a #PF and possibly return an error and panicking, or reading content from an unauthorized page. If such scenarii are possible, we should either:
> 
> * check that `start +  offset + size_of::<T>` doesn't cross the page end
> * allow `GuestPtr::read()/write()` for partial read/write
> * more general, we should always check that a guest or the HV can't force `GuestPtr::read()/write()` to return an error that will be treated as a fatal error by the SVSM kernel (that would be valid DoS).

One case we cannot protect from (as we already discussed) is `#VC` handling of kernel code, as we have no way of resetting to a valid instruction pointer.
 
> 2. In some core protocol handlers, a guest provides a physical address (example the [pvalidate](https://github.com/coconut-svsm/svsm/blob/75b83b3e1a5c860a84ccfe0e4b503e7efee5834f/kernel/src/protocols/core.rs#L312) handler), if I understand the code correctly, the guest-provided physical address pointing to the request entries is only verified if it's mapped or not. My understanding is that a guest could make the kernel read at any mapped address to fetch the `PValidateRequest` (including the kernel memory). Moreover, the guest-provided entries suffer from the same issue, the `paddr` to pvalidate are only verified to be mapped. A guest could make the SVSM kernel pvalidate any page. For the core protocol handlers that work with guest-provided paddrs, my understanding is that we should validate that paddrs only belong to the guest's memory region. I left TODOs is some places (not all of them) to points where there is this issue.

As far as I can tell we already guard against this via `valid_phys_address()`, so I think we're safe for now. Although perhaps we should enforce this at the type level.

2024-06-18 07:46 UTC, p4zuu commented
> As far as I can tell we already guard against this via `valid_phys_address()`, so I think we're safe for now. Although perhaps we should enforce this at the type level.

You're right, I misread `init_memory_map()`, I thought `MEMORY_MAP` contained SVSM kernel memory regions, but it actually contains guest regions, so we're good.

2024-06-20 14:04 UTC, p4zuu commented
Several uses of `GuestPtr::read()/write()` are to update VMSA's calling area. If I understand correctly, VMSA can't be modified by a guest or by the hypervisor, so we can trust its location and its content. With this, I think we can implement 2 safe methods to read and write CAA (and possibly extrapolate to other VMSA fields), that would remove several `unsafe` that I currently added for this PR. Something like:
```rust
pub fn read_caa(va: VirtAddr) -> Result<SvsmCaa, SvsmError> {
    let calling_area = GuestPtr::<SvsmCaa>::new(virt_addr);
    // SAFETY: HV and guests can't change VMSA's content, therefore CAA.
    unsafe { calling_area.read() }
}
```

2024-06-20 15:32 UTC, 00xc requested changes
Left some suggestions. On top of that, safety comments regarding the CAA should be updated based on my previous comment above.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/cpu/vc.rs
> +    // memory.
This is a very convoluted explanation. I would just say: we trust the CPU-provided register state to be valid. Thus, RIP will point to the instruction that caused `#VC` to be raised, so it can safely be read.

I think the worst case scenario is that somehow another CPU might unmap the code page where the instruction resides, causing the read to fail. Anyhow, that is not undefined behavior so it is safe.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/debug/gdbstub.rs
> +                return unsafe { write_u8(addr, value) };
This does not explain why it is safe. This should say something like: it is up to the user to ensure that the address we are writing a breakpoint to is valid.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/debug/gdbstub.rs
> +                unsafe { write_u8(dst, *src).map_err(|_| TargetError::NonFatal)? }
I'm having trouble understanding this one. Also, what do we mean by "attacker" here?

2024-06-20 15:32 UTC, 00xc commented on kernel/src/igvm_params.rs
> +            // is defined in the config.
```suggestion
            // SAFETY: mem_map_va points to newly mapped memory, whose physical
            // address is defined in the IGVM config.
```

2024-06-20 15:32 UTC, 00xc commented on kernel/src/igvm_params.rs
> +            // is defined in the config.
Same as the previous one.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +///    memory).
* `v` does not need to be a mapped address for this function to be safe. In fact, that is what this function guarantees: that accessing unmapped memory will simply return an error instead of causing an unexpected #PF or #GP.
* `v` does not need to belong to the issuer's address space. In fact we can use this to write to guest memory from the SVSM kernel IIUC. I'd reword that point to say that the caller needs to take care not to corrupt arbitrary memory, as this function won't make any checks in that regard.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +/// and that the #PF or #GP handler returns an error.
This sentence does not make much sense I think, and also talks about exceptions, which are an implementation detail the caller does not need to know about. I'd simply say:

```suggestion
/// # Returns
///
/// Returns an error if the specified address is not mapped or is not mapped
/// with the appropriate write permissions.
```

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    /// and that the #PF or #GP handler returns an error.
Same as with `write_u8`

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    /// and that the #PF or #GP handler returns an error.
Same as with `write_u8`

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    /// and that the #PF or #GP handler returns an error.
Same as with `write_u8`

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +        }
We don't want tests corrupting memory, so I'd give an actual explanation.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +        let result = unsafe { ptr.read().unwrap() };
Same here, we need an explanation.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +        let err = unsafe { ptr.read() };
Same here, we need an explanation.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/sev/secrets_page.rs
> +    /// attacker-controllable address.
The caller here is not responsible for verifying `self`. We are under the assumption that we are working with a valid type, since `&mut self` is a safe Rust reference. Otherwise every method call that takes `&self` or `&mut self` should be unsafe for that exact same reason.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/sev/secrets_page.rs
> +    pub unsafe fn copy_to(&self, target: VirtAddr) {
Same here `&self` can be assumed to be valid.

2024-06-20 15:32 UTC, 00xc commented on kernel/src/svsm.rs
> +    }
This should be updated regarding my comment above about `&self`.

2024-06-21 07:42 UTC, p4zuu commented on kernel/src/cpu/vc.rs
> +    // memory.
Even worse, I guess the page could be remapped to another guest or the SVSM kernel, but as long as we don't leak the bytes we're trying to read , we should be fine.

2024-06-21 11:53 UTC, 00xc commented on kernel/src/debug/gdbstub.rs
> +                unsafe { write_u8(dst, *src).map_err(|_| TargetError::NonFatal)? }
Then let's make the function unsafe and describe why in the function docs.

2024-06-21 13:53 UTC, p4zuu commented
> No, I don't think that's how it works. First, the guest's VMSA is different from the SVSM's VMSA - the guest is allowed to update its VMSA. Second, the CA is located in a different physical page than the VMSA. When the guest sets the CA's physical address (via `core_create_vcpu()`) or updates it (via `core_remap_ca()`) we have checks in place to verify it is valid. That is why mapping it and reading/writing to it is safe.

That makes sense to me, thanks. I think there is a 3rd way to update the CA: through `prepare_fw_launch()` raised during early setup with IGVM-provided value, so I guess we can safely trust it too, correct?

2024-06-21 14:32 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +///    memory).
Updated

2024-06-21 14:33 UTC, p4zuu commented on kernel/src/sev/secrets_page.rs
> +    /// attacker-controllable address.
Updated

2024-06-21 14:38 UTC, p4zuu commented on kernel/src/debug/gdbstub.rs
> +                unsafe { write_u8(dst, *src).map_err(|_| TargetError::NonFatal)? }
Nvm, `write_addrs()` belongs to the `MultiThreadBase` trait of the `gdbstub` crate. I fear there's nothing we can do

2024-06-25 10:36 UTC, joergroedel commented
> ```rust
>     let guard = PerCPUPageMappingGuard::create_4k(paddr)?; // paddr possibly guest or HV controlled
>     let start = guard.virt_addr();
>     let guest_page = GuestPtr::<Tt>::new(start + offset);
>     let mut request = unsafe { guest_page.read()? };
> ```

Longer term we should introduce a safe interface around this pattern, which does all the mapping and bounds checking internally and avoids the `unsafe` keyword everywhere in the code. Just not so sure about TLB flushing, maybe we need a collector type as a base which handles that. Something like this:

```rust
{
    // Create TLB handle
    tlb = tlb_gather::new();
    // Create memory handle which can not outlive TLB handle
    mem_handle = tlb.new_mapping(phys_addr, size);
    let mut foo = mem_handle.read();
    let mut bar = mem_handle::offset(1).read();
    drop(mem_handle);
    // mem_handle goes out of scope, unmapping the memory, TLB handle makes sure the virt range is not
    // re-used until it is destroyed

    mem_handle2 = tlb.new_mapping(paddr2, size2)
    // ... use mem_handle2

    // memhandle2 goes out of scope, mapping is removed
    // tlb goes out of scope and flushes the TLB(s).
}
   
```

2024-06-25 10:38 UTC, joergroedel commented
But for now it looks good to me, will merge it once @00xc approves.

2024-06-26 10:59 UTC, 00xc commented on kernel/src/mm/guestmem.rs
> +    /// with the appropriate read permissions.
On x86 there is no way to restrict read permissions on a page, so I think we cannot get `#GP`.

2024-06-26 11:02 UTC, 00xc commented on kernel/src/debug/gdbstub.rs
> +                unsafe { write_u8(dst, *src).map_err(|_| TargetError::NonFatal)? }
Then we should have something like "we trust the caller of this trait method to provide a valid address".

2024-06-26 11:03 UTC, 00xc commented
> But for now it looks good to me, will merge it once @00xc approves.

We still have some unresolved conversations. Once that's done I'll approve.

2024-06-28 10:40 UTC, p4zuu commented
> Longer term we should introduce a safe interface around this pattern, which does all the mapping and bounds checking internally and avoids the `unsafe` keyword everywhere in the code. 

I agree, this pattern happens in quite a few places and there is room for improvements.

> Just not so sure about TLB flushing, maybe we need a collector type as a base which handles that.

Couldn't we just simply create new `read()/write()` methods for `PerCPUPageMappingGuard`?

2024-06-28 11:10 UTC, p4zuu commented
> That makes sense to me, thanks. I think there is a 3rd way to update the CA: through `prepare_fw_launch()` raised during early setup with IGVM-provided value, so I guess we can safely trust it too, correct?

Checked with Carlos that the CA address updated in `prepare_fw_launch()` is validated in `validate_fw_memory()`.

2024-06-28 11:12 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +    /// with the appropriate read permissions.
Nice catch. Updated

2024-06-28 11:13 UTC, p4zuu commented on kernel/src/debug/gdbstub.rs
> +                unsafe { write_u8(dst, *src).map_err(|_| TargetError::NonFatal)? }
Updated

2024-06-28 11:30 UTC, p4zuu commented on kernel/src/mm/guestmem.rs
> +/// and that the #PF or #GP handler returns an error.
Applied the suggestion.

2024-07-01 08:08 UTC, 00xc commented
> > Just not so sure about TLB flushing, maybe we need a collector type as a base which handles that.
> 
> Couldn't we just simply create new `read()/write()` methods for `PerCPUPageMappingGuard`?

It wouldn't solve the fact that we would need to issue a flush for each guard. It also requires making `PerCPUPageMappingGuard` type-aware. Not a bad idea, but it is a more intrusive change.

2024-07-01 08:08 UTC, 00xc commented
There are some conflicts to resolve, please rebase.

2024-07-01 09:02 UTC, p4zuu commented
> There are some conflicts to resolve, please rebase.

Done

2024-07-01 09:34 UTC, 00xc approved these changes

2024-07-01 09:34 UTC, merged