SSE and FPU support
coconut-svsm/svsm pull request #410
Opened 2024-07-15 07:21 UTC by vsntk18

This PR entails following changes:
1. Enable the usage of SSE/FPU instructions in SVSM.
2. xstate management while switching between tasks.

I will submit the related exception handling in another PR.

2024-07-31 08:51 UTC, joergroedel commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
A file page is freed automatically when the ref goes away.

2024-07-31 09:04 UTC, joergroedel requested changes
This goes into the right direction, thanks for the work! I marked some desired changes inline.

2024-07-31 09:04 UTC, joergroedel commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
The required size for the xsave area is variable-sized and needs to be calculated. It can extend with new features, so we can not assume that one page is enough.

See AMD Architecture Programmers Manual Vol. 2 Section 11.5.3 for how to calculate the correct size.

2024-08-07 16:43 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +        log::info!("Legacy SSE instructions not supported by this hardware");
ok, initially I was thinking may be SSE/FPU support is optional.

2024-08-07 16:45 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +}
That's neat.  Thanks for the suggestion.

2024-08-07 16:46 UTC, vsntk18 commented on kernel/src/task/tasks.rs
> +    pub xsa_addr: u64,
Actually this value is used in the inline assembly, just like _rsp_.

2024-08-07 16:49 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +        log::info!("XSAVE is not supported by this hardware");
yes, without xsave at least some part of the state needs to be manually saved and restored. I expect xsave to be available on modern cpus.

2024-08-07 16:55 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +    }
hmm,  where else do you expect XCR register value to be used?   This function is called only once during the initialization of the cores.

2024-08-07 16:55 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +    xsse_val |= 0x7;
ok.

2024-08-12 12:07 UTC, 00xc commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
Right, but as you mention somewhere else, the xsave area can be larger than a page. I suggest using the new PageBox API once #420 is merged.

2024-08-12 12:08 UTC, 00xc commented on kernel/src/task/tasks.rs
> +    pub xsa_addr: u64,
They should be ABI-compatible for 64 bit systems, but we can leave as-is for consistency.

2024-08-13 12:14 UTC, joergroedel commented on kernel/src/cpu/sse.rs
> +        log::info!("XSAVE is not supported by this hardware");
There is no reason to handle hardware without XSAVE support, as all modern CPUs have that. The feature not being enumerated should case a boot panic.

2024-08-13 12:15 UTC, joergroedel commented on kernel/src/cpu/sse.rs
> +    }
Okay, in this case you can leave it as is. We can live without caching the value.

2024-08-13 12:18 UTC, joergroedel commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
Yes, but also: for the current size of 832 bytes, 4 states would fit into one page. So I think it makes sense to allocate the memory via the global allocator. This handles both cases, small and very big xsave areas.

2024-08-19 07:52 UTC, vsntk18 commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
When xsave area spans multiple pages, multiple file pages are allocated. All file pages are deallocated  when they go out of reference. Same technique is used for task stacks as well.

Do you think PageBox is better in this case?

2024-08-19 08:02 UTC, 00xc commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
Unless you need reference counting, I suggest using `PageBox`, as the backing memory is also freed on drop. Plus, the bounds of the backing memory is kept track of, meaning memory corruption is less likely.

2024-08-19 15:29 UTC, joergroedel commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
Hmm, given that the XSAVE area is about 800-900 bytes currently, a full page is probably not needed. I think it is better to use a `Box` instead. That will also handle the case of an XSAVE area that is bigger than one page and does not waste as much memory with the current size.

2024-08-21 19:07 UTC, vsntk18 commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
> Right, but as you mention somewhere else, the xsave area can be larger than a page. I suggest using the new PageBox API once #420 is merged.

can the memory allocated via PageBox be accessed globally ( both by kernel and tasks)? I got a page fault while accessing this memory to do xsave/xrstore.

2024-08-22 15:46 UTC, vsntk18 commented
Addressed the review comments.

2024-08-23 08:38 UTC, vsntk18 commented on kernel/src/mm/vm/mapping/xsave_area.rs
> +        let pg = allocate_file_page_ref()?;
After a discussion with Joerg,  decided to go with PageBox until we have our own smart pointers in SVSM.

2024-08-23 10:19 UTC, joergroedel requested changes
Thanks for updating the PR! I left a couple of review comments.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/cpu/sse.rs
> +    let Some(res) = cpuid_table_raw(1, 0, 0, 0) else {
This code needs to use the `cpuid` instruction directly to be compatible with the native and TD platform targets. I just realized there is no wrapper yet for `cpuid`, so please add one and use it for any FPU-related CPUID queries. This also affects other places in this PR.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/cpu/sse.rs
> +    }
```suggestion
    if !extended_sse_supported() {
        panic!("Extended SSE is not supported by this hardware");
    }
    
    if !xsave_supported() {
        panic!("XSAVE is not supported by this hardware");
    }
    
    cr4_xsave_enable();
    xcr0_set();    
```

Make the panic messages a bit more concise.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/task/schedule.rs
> +
This can happen in `schedule()`.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/task/schedule.rs
> +    }
This needs to be moved into the `if let Some((current, next)) = work {` branch. Otherwise the code will load an old FPU context when no context switch is happening.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/task/tasks.rs
> +    }
This needs to be in `setup_new_task()`.

2024-08-23 10:19 UTC, joergroedel commented on kernel/src/task/tasks.rs
> +        let (stack, raw_bounds, rsp_offset) = Self::allocate_ktask_stack(cpu, entry, xsa_addr)?;
The same needs to happen for user tasks.

2024-08-28 13:21 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +    let Some(res) = cpuid_table_raw(1, 0, 0, 0) else {
How about CpuidResult::get() which is also being used by platform for ex: kernel/src/platform/native.rs?

2024-08-30 09:28 UTC, vsntk18 commented on kernel/src/cpu/sse.rs
> +    }
Sure, truncated them a bit.

2024-08-30 09:29 UTC, vsntk18 commented on kernel/src/task/schedule.rs
> +
moved to schedule()

2024-08-30 09:30 UTC, vsntk18 commented on kernel/src/task/schedule.rs
> +    }
Ah, right!  good point.

2024-08-30 09:30 UTC, vsntk18 commented on kernel/src/task/tasks.rs
> +    }
done!

2024-08-30 09:31 UTC, vsntk18 commented on kernel/src/task/tasks.rs
> +        let (stack, raw_bounds, rsp_offset) = Self::allocate_ktask_stack(cpu, entry, xsa_addr)?;
added to user tasks as well.

2024-08-30 09:36 UTC, vsntk18 commented
|Addressed review comments.

2024-10-21 07:59 UTC, vsntk18 commented
Rebase done.

2024-10-23 16:24 UTC, msft-jlange commented
What are the rules for FP/SSE in interrupt handlers?  Is the interrupt dispatch logic required to save/restore FPU state to prevent reentrant corruption?

2024-10-24 12:17 UTC, joergroedel commented on kernel/src/cpu/sse.rs
> +    let Some(res) = cpuid_table_raw(1, 0, 0, 0) else {
Yes, that is the better option. I have seen you updated it that way.

2024-10-24 12:21 UTC, joergroedel commented on kernel/src/task/schedule.rs
> +            sse_restore_context(u64::from((*a).xsa.vaddr()));
The context needs to be loaded from `*b` instead of `*a`, no?

2024-10-24 15:18 UTC, joergroedel commented
> What are the rules for FP/SSE in interrupt handlers? Is the interrupt dispatch logic required to save/restore FPU state to prevent reentrant corruption?

None of this is handled yet in this PR. The plan is that the kernel is in general not allowed to use the FPU at all. There will be calls to enable/disable FPU usage, that would save/restore the state, but will not be possible to be used in a nested way. This means that IRQ handlers are in general not allowed to use the FPU.

2024-10-25 12:09 UTC, joergroedel commented on kernel/src/task/schedule.rs
> +            sse_restore_context(u64::from((*a).xsa.vaddr()));
Okay, I was wrong, as this part of the function runs once process A is scheduled back in, so restoring the FPU context from `*a` is correct.

2024-10-25 12:13 UTC, joergroedel approved these changes
The changes look ready for merging to me. There are still a few rough edges, but some of them need a better kernel initialization infrastructure first. So lets move on with this now. Thanks for taking on and driving this work forward, @vsntk18

2024-10-25 12:13 UTC, merged