stage2: relocate stage2 and boot data to 8 MB
coconut-svsm/svsm pull request #432
Opened 2024-08-01 21:21 UTC by msft-jlange

Stage2 has grown so that it cannot fit below 640 KB with enough space to provide a heap for stage2 execution.  This change relocates stage2 (and stage1 and the kernel images) up to 8 MB so that all of the memory below 640 KB can be used for the stage2 heap, and so that stage2 can continue to grow without concern for hitting any other size limits.

2024-08-06 16:48 UTC, p4zuu commented on kernel/src/boot_stage2.rs
> +        leal 12(%ecx), %ecx
I guess you meant the following here:
```suggestion
        leal 16(%ecx), %ecx
```

2024-08-06 16:49 UTC, p4zuu commented
SVSM kernel doesn't boot on my testing machine (Milan) unless I fix the `leal 16(%ecx), %ecx` in `boot_stage2.rs`, I guess it's a typo :)

2024-08-08 18:22 UTC, msft-jlange commented on kernel/src/boot_stage2.rs
> +        leal 12(%ecx), %ecx
Yes - thanks for catching this!  I'm not entirely sure why this fails for you but not for me; I suspect that different hypervisors populate the initial CPUID page differently such that in my case it just happens to work.

2024-08-14 10:01 UTC, roy-hopkins reviewed
This boots fine on my Genoa system with IGVM.

2024-08-14 11:43 UTC, msft-jlange commented on stage1/stage1.S
> +	pushl	$0x9F000
Might as well fix it.

2024-08-14 11:59 UTC, msft-jlange commented on igvmbuilder/src/gpa_map.rs
> +        //   0x8nnnnn-0x8nnnnn: kernel
This is a mistake - once the stage2 heap is moved to low memory, there should be no more fixed addresses, and the kernel should begin directly after the stage2 image.  Looks like I simply forgot to include that logic when building the IGVM.

2024-08-14 12:03 UTC, msft-jlange commented on utils/gen_meta.c
> +	svsm_meta->descs[0].len  = 8832 * 1024;
I think you are right.  I'll make that change.

2024-08-14 12:05 UTC, msft-jlange commented on kernel/src/stage2.rs
> +    setup_stage2_allocator(launch_info.kernel_elf_start as u64);
With this commit, stage1 is based at 8 MB, and the kernel ELF is embedded within it, so the kernel isn't in low memory.  However, the kernel does immediately follow the stage2 image, so there would be no room for a heap here.  I will try to get the code to be correct, though as you point out, it is somewhat moot because this is all replaced with a later commit.

2024-08-14 12:37 UTC, msft-jlange commented on kernel/src/stage2.rs
> +    setup_stage2_allocator(launch_info.kernel_elf_start as u64);
Actually, I think I'm not understanding the stage1 layout correctly, so this will need more work to fix.

2024-08-14 12:40 UTC, msft-jlange commented on utils/gen_meta.c
> +	svsm_meta->descs[0].len  = 8832 * 1024;
What we really want is to validate only the memory actually populated by stage2, but that is not known when the metadata is generated, so stage1 would have to execute PVALIDATE on its own.  But this would result in an unknown amount of memory being pre-validated, so the kernel would not know how much memory to restore prior to entering the guest.  I'll have to give this some more thought to figure out how to make this consistent across stage1/IGVM configurations.

2024-08-14 12:43 UTC, msft-jlange commented on kernel/src/mm/address_space.rs
> +    panic!("Invalid physical address {:#018x}", vaddr);
Yes.

2024-08-14 14:33 UTC, msft-jlange commented on utils/gen_meta.c
> +	svsm_meta->descs[0].len  = 8832 * 1024;
I think I have this correct now.  When booting from stage1, we reserve enough memory to hold the maximum possible stage2 size (640 KB), and this is expressed as multiple, non-overlapping regions.

2024-08-14 14:34 UTC, msft-jlange commented on kernel/src/stage2.rs
> +    setup_stage2_allocator(launch_info.kernel_elf_start as u64);
This should be correct now.  We use the reserved size of the stage2 area to hold the heap, without reference to the base of the kernel ELF image.

2024-08-14 18:23 UTC, AdamCDunlap commented
I tried testing this PR on Google's internal non-igvm boot path, but it looks like even svsm's main branch broke this (we haven't merged with github in a while). Internally we agreed that we'll commit to getting support for igvm before merging with github, so we have no objections to this PR.

I also tried our prototype igvm boot with this PR and it did as well as the other branch I've been testing on, so no objections there either.

2024-08-15 16:25 UTC, roy-hopkins commented
> I tried testing this PR on Google's internal non-igvm boot path, but it looks like even svsm's main branch broke this (we haven't merged with github in a while). Internally we agreed that we'll commit to getting support for igvm before merging with github, so we have no objections to this PR.

I've just raised a PR that should fix non-IGVM boot for the main branch. https://github.com/coconut-svsm/svsm/pull/439

2024-08-15 19:08 UTC, msft-jlange commented on bootlib/src/kernel_launch.rs
> +    pub _reserved: u32,
This is a structure on the stack, and we expect RSP to be aligned to an 8-byte boundary at all times.  Because the IGVM file builder uses the structure size to calculate the value of RSP, we need the structure size to be aligned to a multiple of 8 bytes so that RSP alignment remains correct.

It would be possible to change the logic in the IGVM builder to align RSP on its own, but that work is beyond the scope of this PR and should be done in a separate PR.

2024-08-15 19:11 UTC, msft-jlange commented on kernel/src/mm/address_space.rs
> +fn virt_to_phys_mapping(vaddr: VirtAddr, mapping: &FixedAddressMappingRange) -> Option<PhysAddr> {
I don't understand your question.  My intention was to leave the function signature alone as much as possible so I could avoid overhauling all of the callers to the virt/phys translation functions.

2024-08-15 19:11 UTC, msft-jlange commented on utils/gen_meta.c
> +	svsm_meta->descs[3].type = SEV_DESC_TYPE_SNP_SEC_MEM;
Good catch!

2024-08-15 19:14 UTC, msft-jlange commented on kernel/src/stage2.lds
> +	. = 8224k;
Actually, 0x808000 is more consistent with the rest of the code, which uses that same constant everywhere.

2024-08-15 19:15 UTC, Freax13 commented on kernel/src/mm/address_space.rs
> +fn virt_to_phys_mapping(vaddr: VirtAddr, mapping: &FixedAddressMappingRange) -> Option<PhysAddr> {
> I don't understand your question. 

Sorry, what I meant to say was "Have considered making this a method *of* `FixedAddressMappingRange`?" (i.e. move it into an `impl FixedAddressMappingRange` block).

> My intention was to leave the function signature alone as much as possible so I could avoid overhauling all of the callers to the virt/phys translation functions.

That's certainly a good intention, however this function only has two callers and you're touching both of them already. I'm also fine with this staying as is, I just wanted to bring it up.

2024-08-15 19:16 UTC, msft-jlange commented on kernel/src/stage2.lds
> +	. = 8224k;
ok

2024-08-15 19:19 UTC, msft-jlange commented on kernel/src/stage2.rs
> +    };
Yes, this is simpler.

2024-08-15 19:23 UTC, msft-jlange commented on kernel/src/mm/address_space.rs
> +    if let Some(ref mapping) = &FIXED_MAPPING.heap_mapping {
I think I prefer the first suggestion because it makes it more obvious that `mapping` must be a reference.

2024-08-15 19:25 UTC, msft-jlange commented
> I tried testing this PR on Google's internal non-igvm boot path, but it looks like even svsm's main branch broke this

Thanks for testing!  Roy has a PR open to fix the existing stage1 issue, so hopefully once that merges, the latest version of this PR will function correctly.

2024-08-15 19:26 UTC, msft-jlange commented on igvmbuilder/src/gpa_map.rs
> +        let kernel_address = (stage2_image.get_end() + 0xFFF) & !0xFFF;
yes, this is cleaner.

2024-08-15 19:36 UTC, msft-jlange commented on kernel/src/mm/address_space.rs
> +fn virt_to_phys_mapping(vaddr: VirtAddr, mapping: &FixedAddressMappingRange) -> Option<PhysAddr> {
I see what you mean.  This is definitely cleaner.

2024-08-15 19:38 UTC, msft-jlange commented on kernel/src/mm/address_space.rs
> +    panic!("Invalid virtual address {:#018x}", vaddr);
The code in the PR is the same panic syntax that was present before my change.  I'm just preserving what was already there.

2024-08-16 00:33 UTC, AdamCDunlap commented
I tried with both this PR and Roy's stage1 PR (which fixed the issue on its own) and I'm getting an error while trying to read the sev metadata GUID tables from svsm.bin: ` Section [unknown SNP metadata section type: 0x0] has length that's not a positive multiple of a 4K page size: 0x0`

Again, we don't want to block this PR, but it does seem like it messes up the GUID tables.

2024-08-16 09:38 UTC, roy-hopkins requested changes
With the latest changes, and with my fix from the other PR, my guest fails to boot in early firmware startup. Applying the change to `gen_meta.c` to fix the length allows my guest to boot correctly.

2024-08-16 09:38 UTC, roy-hopkins commented on utils/gen_meta.c
> +	svsm_meta->descs[3].len  = 0x8A0000 - 0x080000;
This should be:

```suggestion
	svsm_meta->descs[3].len  = 0x8A0000 - 0x808000;
```

2024-08-16 09:42 UTC, roy-hopkins commented
> I tried with both this PR and Roy's stage1 PR (which fixed the issue on its own) and I'm getting an error while trying to read the sev metadata GUID tables from svsm.bin: ` Section [unknown SNP metadata section type: 0x0] has length that's not a positive multiple of a 4K page size: 0x0`

Did you test with Jon's previous fix to `gen_meta.c`? The previous version was leaving `svsm_meta->descs[0]` uninitialised.

2024-08-16 15:06 UTC, AdamCDunlap commented
> > I tried with both this PR and Roy's stage1 PR (which fixed the issue on its own) and I'm getting an error while trying to read the sev metadata GUID tables from svsm.bin: ` Section [unknown SNP metadata section type: 0x0] has length that's not a positive multiple of a 4K page size: 0x0`
> 
> Did you test with Jon's previous fix to `gen_meta.c`? The previous version was leaving `svsm_meta->descs[0]` uninitialised.

I tried with the latest version and the SVSM kernel booted. Thanks!

2024-08-19 07:49 UTC, joergroedel commented on kernel/src/mm/address_space.rs
> +    }
Comments are outdated. Resolving conversation.

2024-08-19 07:49 UTC, joergroedel commented on kernel/src/mm/address_space.rs
> +            let offset: usize = paddr - mapping.phys_start;
Comment is outdated. Resolving conversation.

2024-08-19 08:03 UTC, joergroedel approved these changes
Testing looks good. No regressions found.

2024-08-19 08:47 UTC, roy-hopkins approved these changes
All looks good to me.

2024-08-19 14:30 UTC, merged