Implement initial userspace support
coconut-svsm/svsm pull request #467
Opened 2024-09-25 12:18 UTC by vijaydhanraj

This is a draft PR that adds basic syscall support like exit, close, opendir, readdir and exec as well as init task and dm implementation. The purpose of this PR is to get feedback from the community and ensure the design aligns with principles of user-mode support described in https://github.com/coconut-svsm/svsm/blob/main/Documentation/docs/developer/DEVELOPMENT-PLAN.md as well syscall ABIs https://mail.8bytes.org/pipermail/svsm-devel/2024-June/000334.html.

PS: The changes are built on top of https://github.com/coconut-svsm/svsm/pull/456.

2024-09-25 13:14 UTC, Freax13 reviewed
Some preliminary review comments.

2024-09-25 13:14 UTC, Freax13 commented on syscall/src/def.rs
> +pub const F_NAME_SIZE: usize = 256;
AFAICT the max size inside the kernel is 64 bytes. Why are we using a different size here?

2024-09-25 13:14 UTC, Freax13 commented on kernel/src/syscall/class0.rs
> +    log::info!("Terminating current task, exit_code {}", exit_code);
```suggestion
    log::info!("Terminating current task, exit_code {exit_code}");
```

2024-09-25 13:14 UTC, Freax13 commented on init/init.lds
Why do we need this linker script?

2024-09-25 13:14 UTC, Freax13 commented on Makefile
> +	cargo clippy --workspace --all-features --exclude svsm-fuzz --exclude svsm --exclude init --exclude dm --target=x86_64-unknown-linux-gnu -- -D warnings
Why are these excluded?

2024-09-25 13:14 UTC, Freax13 commented on init/.gitignore
> +target
Cargo won't create a `target` directory here (same goes for `dm`).

2024-09-25 13:14 UTC, Freax13 commented on init/src/main.rs
> +    let root = CString::new("/").expect("Failed to create new string");
IMHO these messages don't really say much, we might as well use unwrap here.

2024-09-29 16:59 UTC, vijaydhanraj commented on syscall/src/class0.rs
> +        syscall1(SYS_EXIT, code as u64);
Sure, will do.

2024-09-29 16:59 UTC, vijaydhanraj commented on syscall/src/class0.rs
> +    } as i64
Agree, I will refactor the syscalls.

2024-09-29 16:59 UTC, vijaydhanraj commented on syscall/src/class1.rs
> +pub fn readdir(fs: &FsObjHandle, dirents: &mut [DirEnt]) -> Result<u64, SysCallError> {
Yes, will do.

2024-09-29 16:59 UTC, vijaydhanraj commented on syscall/src/def.rs
> +pub const F_NAME_SIZE: usize = 256;
The spec says max length of file name in bytes is 256, so have adopted this.

2024-09-30 06:33 UTC, Freax13 commented on kernel/src/string.rs
> +        }
I don't know of a good solution to this. Maybe we need to rethink `FixedString`. Until we come up with a proper solution, I'm fine leaving this as is, but we should probably add a `// TODO` here to make sure we don't forget.

2024-09-30 06:36 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +    let dirents = VirtAddr::from(dirents).as_mut_ptr::<DirEnt>();
1. There are other syscalls where we need to check the pointers passed in by userspace. Please also update the other syscalls.
2. `GuestPtr` doesn't prevent the user from pointing into kernel memory. Please make sure that userspace doesn't do that.

2024-09-30 06:40 UTC, Freax13 commented on kernel/src/task/exec.rs
> +            );
No, my point is that anything after `[p_filesz..p_memsz)` must be zero-filled by the loader. The loader cannot assume that the file contains zeroes after `p_filesz` until the end of the page. If we just align up the size and mmap the file, we might map non-zero values into userspace where zero-values are expected.

2024-09-30 06:45 UTC, Freax13 commented on init/init.lds
That's a bug in our elf parser. AFAIK the ELF spec doesn't not guarantee that `p_vaddr` is page aligned, so the output you showed doesn't violate the spec. I'm fine with leaving this as is for now, adding a `// TODO` comment (or opening an issue), and fixing this in a later PR. We shouldn't need to use a linker script here.

2024-10-01 07:23 UTC, vijaydhanraj commented on init/init.lds
Got it, but my understanding from the spec was that `p_align` gives the value to which the segments are aligned in memory and in the file. So, since the addresses were not aligned by `0x1000` felt the parser did the right thing by flagging this as an error. If needed I will go ahead and create a separate issue.
```
  LOAD      0x000000000000c488 0x000000000040d488 0x000000000040d488 
            0x0000000000000b78 0x0000000000010ca0  RW     **0x1000**
```

2024-10-01 07:23 UTC, vijaydhanraj commented on kernel/src/syscall/class1.rs
> +    let dirents = VirtAddr::from(dirents).as_mut_ptr::<DirEnt>();
Sure, will apply the same logic to other syscalls as well.
Regarding the `GuestPtr` not preventing the user from pointing into kernel memory, I see 2 options. Is there a preference?

1. We could compare the VirtAddr with USER_MEM_* macros like below,
```
    if dirents < USER_MEM_START || dirents >= USER_MEM_END {
        return Err(EINVAL);
    }
```

2. Or we could get the current_task() and get the vm_user_range (probably need to introduce `get_user_vmr`) for the task. And then check if the `VirtAddr` falls withing the range.
```
let vmr_range = current_task().get_user_vmr().map_err(|_| EINVAL)?;
if dirents < vmr_range.0 || dirents >= vmr_range.1 {
    return Err(EINVAL);
} 
```

2024-10-01 08:17 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +    let dirents = VirtAddr::from(dirents).as_mut_ptr::<DirEnt>();
> Sure, will apply the same logic to other syscalls as well. Regarding the `GuestPtr` not preventing the user from pointing into kernel memory, I see 2 options. Is there a preference?
> 
>   1. We could compare the VirtAddr with USER_MEM_* macros like below,
> 
> 
> ```
>     if dirents < USER_MEM_START || dirents >= USER_MEM_END {
>         return Err(EINVAL);
>     }
> ```
> 
>   2. Or we could get the current_task() and get the vm_user_range (probably need to introduce `get_user_vmr`) for the task. And then check if the `VirtAddr` falls withing the range.
> 
> 
> ```
> let vmr_range = current_task().get_user_vmr().map_err(|_| EINVAL)?;
> if dirents < vmr_range.0 || dirents >= vmr_range.1 {
>     return Err(EINVAL);
> } 
> ```

The first option seems preferable to me. It's probably worthwhile introducing a new `UserPtr` wrapper type around `GuestPtr` that automatically does those checks for any reads/writes.

2024-10-01 08:30 UTC, Freax13 commented on kernel/src/task/exec.rs
> +            );
> ah I get your point; you mean something like below right?
> 
> ```
> diff --git a/kernel/src/task/exec.rs b/kernel/src/task/exec.rs
> index ea1964d6..bd0e094c 100644
> --- a/kernel/src/task/exec.rs
> +++ b/kernel/src/task/exec.rs
> @@ -13,7 +13,7 @@ use crate::mm::vm::VMFileMappingFlags;
>  use crate::mm::USER_MEM_END;
>  use crate::task::{create_user_task, current_task, schedule, TaskError};
>  use crate::types::PAGE_SIZE;
> -use crate::utils::align_up;
> +use crate::utils::{align_up, zero_mem_region};
>  use alloc::sync::Arc;
>  use elf::{Elf64File, Elf64PhdrFlags};
>  
> @@ -64,13 +64,14 @@ pub fn exec_user(binary: &str, root: Arc<dyn Directory>) -> Result<u32, SvsmErro
>          }
>  
>          if file_offset > 0 {
> -            let valid_file_size = align_up(
> -                seg.file_range.offset_end - seg.file_range.offset_begin,
> -                PAGE_SIZE,
> -            );
> +            let p_filesz = seg.file_range.offset_end - seg.file_range.offset_begin;
> +            let valid_file_size = align_up(p_filesz, PAGE_SIZE);
>  
>              if len > valid_file_size {
>                  task.mmap_user(virt_start, Some(&fh), file_offset, valid_file_size, flags)?;
> +                if p_filesz % PAGE_SIZE != 0 {
> +                    zero_mem_region(virt_start + p_filesz, virt_start + valid_file_size);
> +                }
>                  task.mmap_user(
>                      virt_start + valid_file_size,
>                      None,
> ```

Yup.

> [Update] Tried a quick experiment with above change and it throws an unhandled page-fault error. Will look into this. No issues observed when the memory is not zeroed out.
> 
> ```
> [SVSM] ERROR: Panic: CPU[0] panicked at kernel/src/cpu/idt/svsm.rs:198:9:
> Unhandled Page-Fault at RIP 0xffffff800017034d CR2: 0x000000000000cbb0 error code: 0x0000000000000002
> [SVSM] ---BACKTRACE---:
> [SVSM]   [0xffffff8000170b1e]
> [SVSM]   [0xffffff800017034d]
> [SVSM]   [0xffffff800014d0f6]
> [SVSM]   [0xffffff800012fb54]
> [SVSM]   [0xffffff8000140ab0]
> [SVSM] ---END---
> qemu-system-x86_64: terminating on signal 2
> ```

I think the page tables for `task` aren't active.

> No issues observed when the memory is not zeroed out.

That's bound to happen eventually.

2024-10-01 08:31 UTC, Freax13 commented on init/init.lds
Nope, that's not the case. `p_align` does not specific the alignment for `p_vaddr`, it only ensures that `p_vaddr % p_align == p_offset % p_align`.

2024-10-04 08:43 UTC, vijaydhanraj commented on kernel/src/task/exec.rs
> +            );
Yes, you are correct, the page tables for the new task aren't active and so the error. Few options to resolve the issue,
1. Switch the page tables to the new task, zeroed the memory and switched back to the kernel task page tables. But this doesn't seem like a clean solution.
2. mmap the pages as anonymous as part of the kernel task itself, clear the range `[p_filesz..p_memsz)` and update the new task's VMR range to point to this physical memory ensuring that ref count is not decremented when the mapping is dropped. (No implementation exists currently; we may need to implement this)
3. Customize the linker script in such a way that `.bss` section has a separate segment. This way we can avoid clearing `[p_filesz..p_memsz)` as we can simply mmap this entire region as an anonymous region.

For this PR I have reverted to approach 3, can you please share your thoughts on how we should go about this?

2024-10-04 08:43 UTC, vijaydhanraj commented on kernel/src/syscall/class1.rs
> +    let dirents = VirtAddr::from(dirents).as_mut_ptr::<DirEnt>();
Created a wrapper `UserPtr` around `GuestPtr` that automatically does those checks for `VirtAddr ` to be within `USER_MEM_START/END` range.

2024-10-04 08:44 UTC, vijaydhanraj commented
> Some preliminary review comments.

Thanks @Freax13 for the valuable comments. I have addressed all the earlier comments. Can you please take a look?

2024-10-04 14:17 UTC, Freax13 requested changes
I don't have time for a full review right now, I'll do that sometime next week.

2024-10-07 11:18 UTC, Freax13 commented
Now that #456 has been merged, this PR can be rebased onto `main` and probably be marked as "ready to review" (instead of as a draft).

2024-10-07 22:31 UTC, vijaydhanraj commented
> Now that #456 has been merged, this PR can be rebased onto `main` and probably be marked as "ready to review" (instead of as a draft).

Sure, will rebase, address your other comments and mark the PR ready to review.

2024-10-09 05:40 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +        }
> We need to consider the size of T when doing the bounds checks.

Yes, you are correct. We need to account for the size of `T`. Thanks for the suggestion, I have implemented likewise.

> That said, I'd prefer if we did those checks in the read and write methods (or in another method called by those methods). 

Yes, make sense.  I have implemented a separate function to do the bounds check and invoke it from the `read` and `write` methods.

2024-10-09 05:40 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +    }
Agree, have removed this function.

2024-10-09 05:40 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +    }
Yes, removed this function.

2024-10-09 05:40 UTC, vijaydhanraj commented on kernel/src/syscall/class0.rs
> +        let root_str = CStr::from_ptr(user_root_str).to_str().map_err(|_| EINVAL)?;
Thanks for the clarification. I have added a new `read_c_string` method to read from null-terminated c-style strings.

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
We should limit the size of the string. Can we just use `&mut [u8]` instead of `Vec<u8>`? That would also avoid allocating to the heap.

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/def.rs
> +pub const ENOTSUPP: i32 = -8;
Why do we need this when we have `SysCallError`? Can't we just use `SysCallError` everywhere?

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/syscall/class0.rs
> +    unsafe {
Please reduce the size of `unsafe` blocks. Most of the code in there isn't unsafe, but that's difficult to tell when everything is wrapped in unsafe. This also applies to `sys_opendir`.

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +                let mut new_entry = DirEnt::default();
Can we reduce the nesting here? We should treat `Ok(Some(...))` as the happy case and bail out early in the other cases.

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/task/exec.rs
> +    // needs to be fixed. Current WA is to use a custom linker script to align p_vaddr.
Please move this comment to the buggy code, not the call-site. Maybe also add that comment to the linker scripts themselves.

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/call.rs
> +                }
```suggestion
                if ret > (u64::MAX - u64::from(i32::MAX)) {
                    // Convert to negative error code
                    let error_code = ((ret as i64) - (1 << 32)) as i32;
                    return Err(SysCallError::from(error_code))
                }
```

The previous implementation classified `0x2_0000_0000` as an error, but that's not correct. 
We could also make the range even smaller (e.g. IIRC on Linux only everything from `0xffff_ffff_ffff_fe00` to `0xffff_ffff_ffff_ffff` is used for errors).

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/class0.rs
> +    // SYS_EXIT is supported syscall number by the svsm kernel.
```suggestion
    // SAFETY: SYS_EXIT is supported syscall number by the svsm kernel.
```

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/class0.rs
> +            flags as u64,
```suggestion
            u64::from(flags),
```

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/class1.rs
> +            .map(|ret| Ok(FsObjHandle(ObjHandle::new(ret as u32))))?
```suggestion
            .map(|ret| FsObjHandle(ObjHandle::new(ret as u32)))
```

2024-10-09 11:58 UTC, Freax13 commented on syscall/src/def.rs
> +pub const F_TYPE_DIR: u8 = 1;
Can we make this an enum?

2024-10-09 11:58 UTC, Freax13 commented on init/src/main.rs
> +    let bin = CString::new("/bin/").expect("Failed to create new string");
```suggestion
    let bin = CString::new("/bin/").unwrap();
```

See https://github.com/coconut-svsm/svsm/pull/467#discussion_r1775205323

2024-10-09 11:58 UTC, Freax13 commented on init/src/main.rs
> +    };
```suggestion
    let Ok(obj) = opendir(&bin) else {
        exit(0);
    };
```

2024-10-09 11:58 UTC, Freax13 commented on init/src/main.rs
> +        if n < dirents.len() - 1 {
```suggestion
        if n < dirents.len() {
```

2024-10-09 11:58 UTC, Freax13 commented on init/src/main.rs
> +    }
Please use `Option` instead of checking for `is_empty`.

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +
We don't need this anymore, do we?

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +            SvsmError::FileSystem(FsError::FileNotFound) => ENOTFOUND,
We should implement `From<SvsmError> for SysCallError` and just use that everywhere. This would make error handling much less verbose.

2024-10-09 11:58 UTC, Freax13 commented on kernel/src/task/tasks.rs
> +    pub fn get_rootdir(&self) -> Arc<dyn Directory> {
```suggestion
    pub fn rootdir(&self) -> Arc<dyn Directory> {
```

In Rust, [getters don't have a `get_` prefix](https://rust-lang.github.io/api-guidelines/naming.html?highlight=gett#getter-names-follow-rust-convention-c-getter).

2024-10-09 12:22 UTC, Freax13 commented on kernel/src/task/exec.rs
> +            );
> Yes, you are correct, the page tables for the new task aren't active and so the error. Few options to resolve the issue,
> 
>   1. Switch the page tables to the new task, zeroed the memory and switched back to the kernel task page tables. But this doesn't seem like a clean solution.
> 
>   2. mmap the pages as anonymous as part of the kernel task itself, clear the range `[p_filesz..p_memsz)` and update the new task's VMR range to point to this physical memory ensuring that ref count is not decremented when the mapping is dropped. (No implementation exists currently; we may need to implement this)
> 
>   3. Customize the linker script in such a way that `.bss` section has a separate segment. This way we can avoid clearing `[p_filesz..p_memsz)` as we can simply mmap this entire region as an anonymous region.
> 
> 
> For this PR I have reverted to approach 3, can you please share your thoughts on how we should go about this?

In the long run we should implement this properly, but I'm fine with going with approach 3 for now.

IMO we should implement this in `VMFileMapping::new`. If the size isn't a multiple of the page size, instead of failing, we should make a private copy of the page using `.try_cop_page()` and zero out the bytes after `size`. Each `PageRef` is already mapped into the kernel page tables anyways, so we don't need to create new mappings.

2024-10-13 08:14 UTC, vijaydhanraj commented on kernel/src/task/exec.rs
> +            );
Thanks for the suggestion. If it is fine with you, I can help with implementing this fix after this PR is merged.
I have created a github issue https://github.com/coconut-svsm/svsm/issues/483 to capture this as well the ELF parser issue and removing the linker script WA.

2024-10-15 14:16 UTC, Freax13 commented on syscall/src/call.rs
> +                }
Looks good to me.

2024-10-15 14:17 UTC, Freax13 commented on syscall/src/def.rs
> +pub const F_TYPE_DIR: u8 = 1;
I like your second approach. We wouldn't need to cast in very many places, would we?

2024-10-15 14:55 UTC, Freax13 commented on init/src/main.rs
> +    }
```suggestion
    loop {
        let n = readdir(&obj, &mut dirents).unwrap();
        if let Some(d) = dirents.iter().take(n).find(|d| d.file_type == F_TYPE_FILE) {
            binfile = Some(CString::from(
                CStr::from_bytes_until_nul(&d.file_name).unwrap(),
            ));
            break;
        }
        if n < dirents.len() {
            break;
        }
    }
```

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/cpu/idt/svsm.rs
> +    // when casting the usize back to i32 in the user space.
This comment is outdated.

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        true
```suggestion
        (USER_MEM_START..USER_MEM_END).contains(&v)
            && (USER_MEM_START..USER_MEM_END).contains(&(v + size_of::<T>()))
```

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +pub struct UserPtr<T: Copy + FromBytes> {
Can we move the `FromBytes` bound to the `read` method? I don't see a reason why all types must implement `FromBytes`. This would also solve the problems you mentioned in https://github.com/coconut-svsm/svsm/pull/467#discussion_r1797504701, wouldn't it?

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read(&self) -> Result<T, SvsmError> {
```suggestion
    #[inline]
    pub fn read(&self) -> Result<T, SvsmError> {
```

This function (and `read_c_string`, `write`, and `write_ref`) don't need to be unsafe. We have all the checks in place to make sure that nothing bad can happen :)

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
Hm, yeah, we probably shouldn't allocate a whole page on the stack. Still, can we enforce a size limit here?

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/syscall/class0.rs
> +    panic!("schedule() returned in sys_exit()");
```suggestion
    unreachable!("schedule() returned in sys_exit()");
```

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
Given that we don't seem to be reusing `buffer` anywhere, can we just allocate the memory inside this function and return a `String` instead?

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +        };
```suggestion
        let Some((name, dirent)) = fsobj.readdir()? else {
            return Ok(i as u64);
        };
```

2024-10-15 14:55 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +        }
```suggestion
        new_entry.file_name[..MAX_FILENAME_LENGTH].copy_from_slice(&fname);
```

2024-10-15 14:55 UTC, Freax13 commented on syscall/src/call.rs
> +#[macro_export]
```suggestion
```

2024-10-16 07:54 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
Yes, agree with your suggestion. This seems to be a better solution. But still allocating from the heap instead of statically allocating due to unknown `path` length.

2024-10-16 07:54 UTC, vijaydhanraj commented on kernel/src/syscall/class1.rs
> +        };
Done.

2024-10-16 07:54 UTC, vijaydhanraj commented on kernel/src/syscall/class1.rs
> +        }
Much better, thanks!

2024-10-16 07:54 UTC, vijaydhanraj commented on syscall/src/def.rs
> +pub const F_TYPE_DIR: u8 = 1;
This is no longer an issue, and I have made this to an `enum`.

2024-10-16 07:54 UTC, vijaydhanraj commented on init/src/main.rs
> +    }
Done.

2024-10-16 08:26 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
I'd be fine with 4K.

2024-10-16 08:28 UTC, Freax13 commented
FYI this branch has conflicts with main. You might have to rebase your branch to resolve them.

2024-10-16 08:48 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        unsafe { self.guest_ptr.write(buf) }
```suggestion
        self.write_ref(&buf)
```

2024-10-16 08:48 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub const fn cast<N: Copy + FromBytes>(&self) -> UserPtr<N> {
```suggestion
    pub const fn cast<N: Copy>(&self) -> UserPtr<N> {
```

2024-10-16 08:48 UTC, Freax13 commented on kernel/src/syscall/class1.rs
> +        if let DirEntry::File(ref f) = dirent {
```suggestion
        if let DirEntry::File(f) = dirent {
```

We don't need this here.

2024-10-16 08:48 UTC, Freax13 commented on syscall/src/def.rs
> +    Directory = 1,
```suggestion
    File,
    Directory,
```

2024-10-16 09:47 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
Can you please confirm if this looks fine?
```
diff --git a/kernel/src/mm/guestmem.rs b/kernel/src/mm/guestmem.rs
index c2b0154c..440ee5e9 100644
--- a/kernel/src/mm/guestmem.rs
+++ b/kernel/src/mm/guestmem.rs
@@ -344,7 +344,7 @@ impl UserPtr<c_char> {
     /// Reads a null-terminated C string from the user space.
     /// Allocates memory for the string and returns a `String`.
     pub fn read_c_string(&self) -> Result<String, SvsmError> {
-        let mut buffer: Vec<u8> = Vec::new();
+        let mut buffer = Vec::with_capacity(4096);
 
         for offset in 0.. {
             let current_ptr = self.offset(offset);
```

2024-10-16 11:08 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
No, this won't work. `Vec::with_capacity` creates a vector with the given capacity, but it doesn't prevent the vector from growing past this capacity. Instead we can add a check to the for loop body to see if `offset` is greater than 4k.

2024-10-16 20:04 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +    pub unsafe fn read_c_string<'a>(&self, buffer: &'a mut Vec<u8>) -> Result<&'a str, SvsmError> {
Thanks, done.

2024-10-17 11:30 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        }
```suggestion
```

2024-10-17 11:30 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        for offset in 0..buffer.capacity() {
We should return an error if the string exceeds the capacity. Also, we probably shouldn't default to using 4k as the capacity for the vector. Most strings are probably way smaller than that, the default allocation strategy of vectors should work fine.

2024-10-17 16:04 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +        for offset in 0..buffer.capacity() {
I see your point, how about this? Also, introduced a new const for max path len.
```
@@ -344,17 +342,17 @@ impl UserPtr<c_char> {
     /// Reads a null-terminated C string from the user space.
     /// Allocates memory for the string and returns a `String`.
     pub fn read_c_string(&self) -> Result<String, SvsmError> {
-        let mut buffer = Vec::with_capacity(4096);
+        let mut buffer = Vec::new();
 
-        for offset in 0..buffer.capacity() {
+        for offset in 0..PATH_MAX {
             let current_ptr = self.offset(offset as isize);
             let char_result = current_ptr.read()?;
             match char_result {
-                0 => break,
+                0 => return String::from_utf8(buffer).map_err(|_| SvsmError::InvalidUtf8),
                 c => buffer.push(c as u8),
             }
         }
-        String::from_utf8(buffer).map_err(|_| SvsmError::InvalidUtf8)
+        Err(SvsmError::InvalidBytes)
     }
 }
```

2024-10-17 16:05 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        for offset in 0..buffer.capacity() {
Looks good to me.

2024-10-17 16:45 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +        }
Removed the redundant check.

2024-10-17 16:45 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +        for offset in 0..buffer.capacity() {
Thanks, done.

2024-10-17 17:04 UTC, Freax13 approved these changes
Looks good to me, thanks!

2024-10-23 15:07 UTC, joergroedel commented
Thanks for that work, it is pretty impressive! Although it is hard to review on all levels due to its size:

```
 .github/workflows/rust.yml     |  2 +-
 Cargo.lock                     | 52 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 Cargo.toml                     |  5 +++++
 Makefile                       | 16 ++++++++++++++--
 dm/Cargo.toml                  | 15 +++++++++++++++
 dm/build.rs                    |  6 ++++++
 dm/dm.lds                      | 37 +++++++++++++++++++++++++++++++++++++
 dm/src/main.rs                 | 25 +++++++++++++++++++++++++
 elf/src/program_header.rs      |  3 +++
 init/Cargo.toml                | 16 ++++++++++++++++
 init/build.rs                  |  6 ++++++
 init/init.lds                  | 37 +++++++++++++++++++++++++++++++++++++
 init/src/main.rs               | 73 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 kernel/src/cpu/idt/svsm.rs     | 12 ++++++++----
 kernel/src/error.rs            | 27 +++++++++++++++++++++++++++
 kernel/src/fs/api.rs           |  1 +
 kernel/src/fs/filesystem.rs    | 60 +++++++++++++++++++++++++++++++++++++++++++++++++-----------
 kernel/src/fs/mod.rs           |  2 ++
 kernel/src/fs/obj.rs           | 72 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 kernel/src/mm/guestmem.rs      | 85 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 kernel/src/string.rs           | 11 +++++++++++
 kernel/src/svsm.rs             | 13 +++++++------
 kernel/src/syscall/class0.rs   | 42 ++++++++++++++++++++++++++++++++++++++++++
 kernel/src/syscall/class1.rs   | 54 ++++++++++++++++++++++++++++++++++++++++++++++++++++++
 kernel/src/syscall/handlers.rs | 21 ---------------------
 kernel/src/syscall/mod.rs      |  6 ++++--
 kernel/src/syscall/obj.rs      | 13 ++++++++++++-
 kernel/src/task/exec.rs        | 17 ++++++++++++-----
 kernel/src/task/schedule.rs    |  8 ++++++--
 kernel/src/task/tasks.rs       | 19 +++++++++++++++++--
 syscall/Cargo.toml             |  1 +
 syscall/src/call.rs            | 93 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 syscall/src/class0.rs          | 33 +++++++++++++++++++++++++++++++++
 syscall/src/class1.rs          | 38 ++++++++++++++++++++++++++++++++++++++
 syscall/src/def.rs             | 52 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 syscall/src/lib.rs             | 10 ++++++++--
 syscall/src/numbers.rs         | 10 ----------
 syscall/src/obj.rs             | 15 +++++++++++++++
 38 files changed, 939 insertions(+), 69 deletions(-)
```

Can you please split this into smaller PRs which we can merge one at a time? Please start with the system call interface and implementation. This PR can be rebased then on what has already been merged.

2024-10-23 17:11 UTC, vijaydhanraj commented
Sure, I can split this into smaller PRs. Would splitting commits into the below PRs be helpful?

- **PR#8:** Introduce a simple template for initial device model
    - dm: Add initial device model project
    - init: Extend opendir() and readdir() for dm discovery

- **PR#7**: Add the initial version of init

- **PR#6**: Introduce exec syscall
    - syscall: Implement exec()
    - kernel/syscall: Implement EXEC
    - kernel/task: Return TID in exec_user()

- **PR#5**: Introduce opendir and readdir syscalls
    - syscall/class1: Implement opendir() and readdir()
    - kernel/syscall: Implement OPENDIR and READDIR
    - kernel/fs/filesystem: Add opendir()
    - kernel/fs: Add FsObj
    - kernel/fs/filesystem: Add find_dir()
    - svsm: Initialize FS earlier

- **PR#4**: Introduce exit and open syscalls
    - syscall/obj: Close an ObjHandle when dropped
    - kernel/syscall: Implement close syscall
    - syscall: Introduce exit syscall


- **PR#3**: Introduce syscall interface and error code
    - syscall: Define error code
    - syscall: Add syscall macro

- **PR#2**: Introduce UserPtr wrapper around GuestPtr

- **PR#1**: Few bookkeeping and clean-up commits 
    - kernel/cpu/idt: Remove SYS_HELLO for implementing formal syscalls
    - kernel/syscall: Rename handlers.rs to class0.rs
    - syscall: Rename numbers.rs to def.rs
    - syscall: Add Obj trait

2024-10-25 07:39 UTC, Freax13 commented
FYI, we merged SMAP support in #473, this PR will have to be adjusted accordingly.

2024-10-27 23:12 UTC, vijaydhanraj commented
Hi @joergroedel as suggested, split this PR and added a PR https://github.com/coconut-svsm/svsm/pull/502 to introduce the syscall interface implementation.

2024-10-27 23:18 UTC, vijaydhanraj commented
> FYI, we merged SMAP support in #473, this PR will have to be adjusted accordingly.

Hi @Freax13 thanks, I have rebased this PR.

2024-10-28 08:54 UTC, Freax13 commented
> Hi @Freax13 thanks, I have rebased this PR.

I meant to say that we now need to execute `stac` & `clac` in the `UserPtr` methods.

2024-10-29 06:51 UTC, vijaydhanraj commented
Got it, will add the `stac` and `clac` as part of the `read/write_ref` `UserPtr` methods and update the PR.

2024-10-29 14:37 UTC, vijaydhanraj commented
@Freax13 I have updated the PR to use `stac` & `clac` in `UserPtr` methods. If the changes look fine, please let me know if this should be spined out as a separate PR?

2024-10-29 14:41 UTC, Freax13 commented
> @Freax13 I have updated the PR to use `stac` & `clac` in `UserPtr` methods. If the changes look fine, please let me know if this should be spined out as a separate PR?

Personally, I don't have a problem with large PRs, but @joergroedel might object.

From your comment above:
>   * **PR#2**: Introduce UserPtr wrapper around GuestPtr

It probably makes sense to add the changes to this PR.

2024-10-29 14:47 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +        }
```suggestion
        if !self.check_bounds() {
            return Err(SvsmError::InvalidAddress);
        }
        let _guard = user_access_begin();
```

The same change should be applied for `write_ref`.

2024-10-29 14:47 UTC, Freax13 commented on kernel/src/mm/guestmem.rs
> +}
```suggestion
struct UserAccessGuard;

impl UserAccessGuard {
    pub fn new() -> Self {
        stac();
        Self
    }
}

impl Drop for UserAccessGuard {
    fn drop(&mut self) {
        clac();
    }
}
```

2024-10-29 15:39 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +}
Done.

2024-10-29 15:39 UTC, vijaydhanraj commented on kernel/src/mm/guestmem.rs
> +        }
Since we switched to `new` method, used it here rather than calling the function.

2024-12-19 19:20 UTC, vijaydhanraj commented
This PR can be closed once https://github.com/coconut-svsm/svsm/pull/547 is merged. Most of the changes from this PR are already merged, with PR #547 being the last one.

2025-06-17 21:04 UTC, peterfang commented
Closing as the foundational user mode work is done. https://github.com/coconut-svsm/svsm/pull/547 will be looked at separately.

2025-06-17 21:04 UTC, closed without merging