igmvbuilder: support VSM isolation platform type
coconut-svsm/svsm pull request #472
Opened 2024-09-29 16:11 UTC by msft-jlange

This change enables building an IGVM file that support the `VSM_ISOLATION` platform type.

2024-10-08 13:24 UTC, roy-hopkins requested changes

2024-10-08 13:24 UTC, roy-hopkins commented on igvmbuilder/src/cmd_options.rs
> +    /// Includ VSM isolation platform target.
Typo: "Includ"

2024-10-08 13:24 UTC, roy-hopkins commented on igvmbuilder/src/vmsa.rs
> +            }
These two have been mixed up - Idtr sets gdtr and vise versa.

2024-10-08 13:24 UTC, roy-hopkins commented on igvmbuilder/src/vmsa.rs
> +            X86Register::R8(r) => {
No rdi?

2024-10-08 13:24 UTC, roy-hopkins commented on igvmbuilder/src/vmsa.rs
> +            X86Register::R8(r) => {
No rdi?

2024-10-08 17:13 UTC, msft-jlange commented on igvmbuilder/src/vmsa.rs
> +            }
Oops!

2024-10-08 17:15 UTC, msft-jlange commented on igvmbuilder/src/vmsa.rs
> +            X86Register::R8(r) => {
No, `Rdi` is not a member of `Register::X86Register` in the `igvm` crate.

2024-10-09 09:15 UTC, roy-hopkins approved these changes
Looks good, and tested the QEMU igvm output on SEV-SNP - all works.

2024-10-09 09:51 UTC, stefano-garzarella approved these changes
Tested QEMU/KVM IGVM and launch measurement.

2024-10-15 12:34 UTC, merged