Setup verification
coconut-svsm/svsm pull request #486
Opened 2024-10-16 02:53 UTC by ziqiaozhou

* Set up verification tool and add verification CI. 
* Change the minimum rust version to 1.77 since the verification tool still needs some efforts to support 1.80. This will not change the default version in non-verification mode, since rust-toolchain.toml specifies 1.80.
* `cargo verify` in kernel folder will run verification for functions that annotated with #[verus_verify]
* Added a new crate verismo, which will import the minimum required proofs from verismo project to help SVSM to do efficient proofs.
* Add some proofs for address.rs as a basic example to show how verification works.
* ./script/vfmt.sh will do enhanced formatting for code ending with .verus.rs

2024-10-25 18:47 UTC, ziqiaozhou commented on verify_proof/src/bits.verus.rs
> +    }
Thanks for the suggestion. It looks better.

2024-10-25 18:48 UTC, ziqiaozhou commented on verify_proof/src/bits.verus.rs
> +macro_rules! POW2_VALUE {
Yes. It is for performance. It can avoid repeatedly solving the same bitvector problem by z3.

2024-10-31 21:02 UTC, ziqiaozhou commented
I have updated tool to support Rust-1.82, improved the verification document, and marked the verify.yml as manually triggered CI so that I can still run CI in my forked repo before sending my change here. I can remove it if you prefer to not keeping the manually-triggered CI.

2024-11-12 11:05 UTC, joergroedel requested changes
I followed the documentation and ran a successful verification, but the process generated a few warnings which I'd like to see fixed:

```
warning: verus-related attribute has no effect because Verus is already ignoring this item. You may need to mark it as `#[verifier::verify]`.
  --> verify_proof/src/lib.rs:16:1
   |
16 | global size_of usize == 8;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
   --> verify_proof/src/bits.verus.rs:248:9
    |
248 |         pub broadcast proof fn $pname()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
347 | bit_shl_values! {u64, u64, 1u64, lemma_bit_u64_shl_values}
    | ---------------------------------------------------------- in this macro invocation
    |
    = note: this warning originates in the macro `bit_shl_values` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
   --> verify_proof/src/bits.verus.rs:248:9
    |
248 |         pub broadcast proof fn $pname()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
351 | bit_shl_values! {usize, u64, 1usize, lemma_bit_usize_shl_values}
    | ---------------------------------------------------------------- in this macro invocation
    |
    = note: this warning originates in the macro `bit_shl_values` (in Nightly builds, run with -Z macro-backtrace for more info)

verification results:: 0 verified, 0 errors
warning: `verify_proof` (lib) generated 3 warnings
note: preparing crate for verification

warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
   --> /home/joro/src/svsm/verify_proof/src/bits.verus.rs:248:9
    |
248 |         pub broadcast proof fn $pname()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Also, please look at the other review comments I left.

2024-11-12 11:05 UTC, joergroedel commented on scripts/vinstall.sh
> +curl --proto '=https' --tlsv1.2 -LsSf https://github.com/verus-lang/verusfmt/releases/download/v0.5.0/verusfmt-installer.sh | sh
Please ask the user before downloading and executing a script from the internet. Even better would be if you could commit this script directly to the SVSM repository.

2024-11-13 01:11 UTC, ziqiaozhou commented on scripts/vinstall.sh
> +curl --proto '=https' --tlsv1.2 -LsSf https://github.com/verus-lang/verusfmt/releases/download/v0.5.0/verusfmt-installer.sh | sh
I replace it with a cargo install.

2024-11-13 01:12 UTC, ziqiaozhou commented on scripts/vpath.sh
> +export VERUS_PATH=$verus
removed this scripts since it is only used in verify CI which is already removed.

2024-11-13 01:12 UTC, ziqiaozhou commented on scripts/vinstall.sh
> +sudo apt-get install build-essential ninja-build libclang-dev
Removed them since they are not needed anymore after a tool upgrade.

2024-11-13 18:11 UTC, ziqiaozhou commented
> I followed the documentation and ran a successful verification, but the process generated a few warnings which I'd like to see fixed:
> 
> ```
> warning: verus-related attribute has no effect because Verus is already ignoring this item. You may need to mark it as `#[verifier::verify]`.
>   --> verify_proof/src/lib.rs:16:1
>    |
> 16 | global size_of usize == 8;
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
>    --> verify_proof/src/bits.verus.rs:248:9
>     |
> 248 |         pub broadcast proof fn $pname()
>     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 347 | bit_shl_values! {u64, u64, 1u64, lemma_bit_u64_shl_values}
>     | ---------------------------------------------------------- in this macro invocation
>     |
>     = note: this warning originates in the macro `bit_shl_values` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
>    --> verify_proof/src/bits.verus.rs:248:9
>     |
> 248 |         pub broadcast proof fn $pname()
>     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ...
> 351 | bit_shl_values! {usize, u64, 1usize, lemma_bit_usize_shl_values}
>     | ---------------------------------------------------------------- in this macro invocation
>     |
>     = note: this warning originates in the macro `bit_shl_values` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> verification results:: 0 verified, 0 errors
> warning: `verify_proof` (lib) generated 3 warnings
> note: preparing crate for verification
> 
> warning: broadcast functions should have explicit #[trigger] or #![trigger ...]
>    --> /home/joro/src/svsm/verify_proof/src/bits.verus.rs:248:9
>     |
> 248 |         pub broadcast proof fn $pname()
>     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> Also, please look at the other review comments I left.

The warnings are removed. You need to run `cargo v prepare-verus` before `cargo verify` since I upgraded the verus version to avoid one warning due to mismatched version.

2024-11-22 09:02 UTC, joergroedel approved these changes
Looks good now, thanks for addressing my comments!

2024-11-22 09:02 UTC, merged