panic: use a platform-specific halt routine
coconut-svsm/svsm pull request #496
Opened 2024-10-24 04:20 UTC by msft-jlange

Not all platforms support HLT as a way to halt execution, and therefore the panic halt must be performed through a platform-specific routine. However, at the time of a panic, the global platform object may not yet be initialized.  Instead, use a more primitive mechanism for choosing a platform-specific halt routine during panic.

2024-10-24 15:35 UTC, joergroedel requested changes
In general it looks good, I left a minor change request and a more general comment that does not need to be addressed when updating this PR.

2024-10-24 15:35 UTC, joergroedel commented on kernel/src/platform/native.rs
> +    }
SNP and native use the same method, it is better to put this as the default implementation directly into the trait and avoid the duplication.

2024-10-24 16:30 UTC, msft-jlange commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
I agree that this specific could be reimplemented with global functions, and I can plan to make that change.  However, the existing pattern was chosen for a few very specific reasons.

The global `SVSM_PLATFORM` is necessarily an immutable object, because we cannot reasonably support a mutable global.  Even if `LockCell` were available in the `no_std` environment, we wouldn't want the potential of borrow conflicts if some caller happened to need a mutable reference.  So `SVSM_PLATFORM` must be immutable.  However, during the boot flow, there are cases where the platform object must be mutable because it must adapt to initialization parameters.  That means there must be a part of the initialization flow during which the platform object cannot be accessed through an immutable global.  This is why methods like `env_setup` take `mut &self`.  For calls to these functions, there is no choice but to pass the platform object as a parameter because a global doesn't provide the required mutability.  All of the current code handles two different phases, one in which the platform is passed as a parameter to solve exactly this problem, and another in which the platform is always consumed from a global.

It happens to be the case today that none of the existing implementations of the platform methods actually require `mut` but they're also immature, and I would prefer to start with the option for mutability and clean up later - that's much easier than starting with no option for mutability and being forced to add it later.  I'm similarly concerned about the suitability of diving directly into `Cell` for interior mutability on global objects before we've built enough code to know whether this will really be safe.

2024-10-24 16:32 UTC, msft-jlange commented on kernel/src/platform/native.rs
> +    }
I don't see how we can do that because the panic halt may be needed before the trait object exists.

2024-10-24 16:39 UTC, msft-jlange commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
And now that I take a closer look, I remember the reason I included the parameter in this particular function.  The platform object (everything in `platform/mod.rs`) is available both to the stage2 and svsm environments.  However, the panic flow is specific to the svsm environment.  We don't want to have `SVSM_PLATFORM_TYPE` present in stage2 because it isn't meaningful in the stage2 environment - and for that reason, we don't want to have `SVSM_PLATFORM_TYPE` in `platform/mod.rs`.  But we do want the platform-specific version of halt to be in the platform-specific code.  For this reason, this halt method takes a platform parameter because it's not available in the `platform` module - it comes from the caller in the svsm (there is no caller in stage2).  So I intend to leave this PR exactly as it is unless you can think of a way to solve the stage2/svsm split problem.

2024-10-25 09:20 UTC, Freax13 commented on kernel/src/platform/mod.rs
> +    pub fn halt(platform_type: SvsmPlatformType) {
What's the reasoning behind making this a function on `SvsmPlatformCell`?

2024-10-25 09:20 UTC, Freax13 commented on kernel/src/platform/native.rs
> +    }
We don't need a trait object, we can continue to have the same `halt` method on the `Platform` trait, specify a default there, and omit the implementations here and in the SNP implementation. This will not affect the callsite in `SvsmPlatformCell::halt`, if a platform implementation didn't override the default and is omitting `halt`. For example, `NativePlatform::halt()` would just call the default implementation.

2024-10-25 13:21 UTC, joergroedel commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
> And now that I take a closer look, I remember the reason I included the parameter in this particular function. The platform object (everything in `platform/mod.rs`) is available both to the stage2 and svsm environments. However, the panic flow is specific to the svsm environment. We don't want to have `SVSM_PLATFORM_TYPE` present in stage2 because it isn't meaningful in the stage2 environment - and for that reason, we don't want to have `SVSM_PLATFORM_TYPE` in `platform/mod.rs`. But we do want the platform-specific version of halt to be in the platform-specific code. For this reason, this halt method takes a platform parameter because it's not available in the `platform` module - it comes from the caller in the svsm (there is no caller in stage2). So I intend to leave this PR exactly as it is unless you can think of a way to solve the stage2/svsm split problem.

Okay, I am likely missing some important details here. Why is the `SVSM_PLATFORM_TYPE` not meaningful in stage2? As I see it stage2 does the same platform initialization as svsm, just with the difference that in stage2 `SVSM_PLATFORM_TYPE` is called `platform_cell` and allocated on the stack in `stage2_main`.

In the end the platform abstraction does not consume much memory, it only serves as a collection of pointers to functions which are linked into stage2 and the svsm. So I don't understand why stage2 can not just use `SVSM_PLATFORM_TYPE` as well.

2024-10-25 14:19 UTC, msft-jlange commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
> In the end the platform abstraction does not consume much memory, it only serves as a collection of pointers to functions which are linked into stage2 and the svsm. So I don't understand why stage2 can not just use `SVSM_PLATFORM_TYPE` as well.

It can; it was just more a matter of adhering to a general principle that we should avoid inserting objects where they are not needed.

Now that I take a closer look, this actually should be implemented for stage2 as well so that the stage2 panic handler can also halt correctly.  I hadn't done this originally because I thought that the platform identity was not known in stage2 early enough, but it is known from the beginning so I should just make this common so it is available to stage2.

2024-10-25 14:27 UTC, msft-jlange commented on kernel/src/platform/native.rs
> +    }
> We don't need a trait object, we can continue to have the same `halt` method on the `Platform` trait, specify a default there, and omit the implementations here and in the SNP implementation. This will not affect the callsite in `SvsmPlatformCell::halt`, if a platform implementation didn't override the default and is omitting `halt`. For example, `NativePlatform::halt()` would just call the default implementation.

`halt` does not take `&self` because there is no object to reference.  Trait methods require a `&self` reference.  Adding `&self` to this function so it could become part of the trait would require that every call be performed on an object that implements the trait, and I cannot figure out which object would be the right one.  At the time of the first panic, there is no object that is guaranteed to exist other than the global `SVSM_PLATFORM_TYPE`, which is an instance of `SvsmPlatformType` and not `SvsmPlatformCell`.  There's nothing I can identify in `SvsmPlatformType` that can support a platform-specific object which could implement platform-specific functionality for the trait that contains `halt`.  So I really don't understand how to follow your suggestion.

2024-10-25 14:29 UTC, msft-jlange commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
> Maybe we can split the platform trait into two traits, one of which takes multiple references where required and one of which only takes shared references. I generally agree with your sentiment that the currently code is immature and may take advantage of the mutable references in the future, but I also think that there are some methods for which we can reasonably forsee that this likely won't happen e.g. `halt`, `cpuid` or `get_page_encryption_masks`. The mutable trait could be passed as a parameter, the immutable trait could always be stored in a global.

Doing this would not address Joerg's concern, which was a desire to avoid passing platform objects around as parameters.

2024-10-25 14:31 UTC, msft-jlange commented on kernel/src/platform/mod.rs
> +    pub fn halt(platform_type: SvsmPlatformType) {
> What's the reasoning behind making this a function on `SvsmPlatformCell`?

This was done for namespace containment, so that the function wouldn't have to be a global function - the presence of the qualifying namespace reinforces the fact that this is intended to be a platform-specific function.  There is no `&self` so this isn't a method, and thus this just boils down to naming convention.

2024-10-25 16:33 UTC, msft-jlange commented on kernel/src/platform/native.rs
> +    }
Well, today I learned that it is actually possible to define a trait function that doesn't take `&self` and therefore it's possible to have a default implementation of a function that is not a method.  So I've updated the PR.

2024-10-25 18:42 UTC, Freax13 commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
> Doing this would not address Joerg's concern, which was a desire to avoid passing platform objects around as parameters.

We could stick a reference to the immutable platform trait object into a static and always use that directly. As you pointed out we can't do that for the current platform trait because we need it to be mutable, but if we don't need it to be mutable, there's not much preventing us from just putting it in a global. Of course, this doesn't help for the code where we need to mutable platform trait object, but my hope is that it'd at least be an improvement in the cases where we can use the global.

2024-10-25 18:45 UTC, Freax13 approved these changes

2024-10-25 18:56 UTC, msft-jlange commented on kernel/src/svsm.rs
> +        SvsmPlatformCell::halt(*SVSM_PLATFORM_TYPE);
> We could stick a reference to the immutable platform trait object into a static and always use that directly. As you pointed out we can't do that for the current platform trait because we need it to be mutable, but if we don't need it to be mutable, there's not much preventing us from just putting it in a global. Of course, this doesn't help for the code where we need to mutable platform trait object, but my hope is that it'd at least be an improvement in the cases where we can use the global. Edit: Maybe I didn't look at the existing code enough. I might be completely wrong here and we're already partially doing that. If that's the case feel free to disregard my comment above.

That is roughly what we do today.  The platform object only flows through parameters among those functions that need access to it while it remains mutable.  Then we stick it into `SVSM_PLATFORM` at which point it becomes immutable.  This is a little uglier than I'd like for a couple of reasons.  First, because we're `no_std` and because we have to bootstrap a bunch of platform support before memory management services are online, we can't create `Box::<dyn SvsmPlatform>` because we need the platform object before the global allocator can support `Box`.  That forces us to have something like the `SvsmPlatformCell` that we have today, which can act as a static container for every type of platform, and then it exposes a method to get the `dyn SvsmPlatform` when needed.  The other issue is that the only tool we have for globals that are mutable and then become immutable is `ImmutAfterInitCell` (and its cousin `ImmutAfterInitRef`).  These global containers require `Copy` and therefore the `SvsmPlatformCell` has to be `Copy` which precludes the inclusion of things like atomics, and thus atomics have to be separate globals that are referenced from the individual trait implementations.  The immutable globals also required `Sized` which means they cannot contain a `&dyn`.  I wish there were a way to solve both of these, because I'd love to be able to get rid of the `SvsmPlatformCell` variant, and I'd love to get rid of the extra globals and put them into the platform objects, but there's no clean path to that right now.  I would welcome any suggestions.

2024-10-30 13:09 UTC, joergroedel approved these changes
Thanks, this looks good to me now.

2024-10-30 13:09 UTC, merged