stage1: Rustify stage1 and update IGVM VTOM on TDP platforms
coconut-svsm/svsm pull request #517
Opened 2024-11-14 11:41 UTC by peterfang

Move stage1/*.S to a Rust crate. This allows for better interfacing with other crates and reduces hard-coding and chances of breakage.

Update IgvmParamBlock.vtom in addition to Stage2LaunchInfo.vtom during IGVM boot. It ensures Stage2 & the SVSM kernel can use VTOM as expected.

2024-11-14 11:45 UTC, peterfang commented
This fails CI as stage1/stage1.o and stage1/reset.o no longer exist.

2024-11-15 11:19 UTC, joergroedel requested changes
Hi Peter,

I like this change, it will simplify the build process and allows more sharing of constants and code between the different stages.

Can you please adapt the CI files to make it pass with these changes and have a look at using the existing `x86-64-unknown-none` target? I tried that already but ran into linker errors due to 32-bit relocations in 64-bit code. But maybe there is a way around that.

2024-11-15 11:19 UTC, joergroedel commented on Makefile
> +	cargo rustc --target i686-unknown-linux-gnu --manifest-path stage1/Cargo.toml ${CARGO_ARGS} --features load-stage2 --bin stage1 -- -C panic=abort
Do you see a change of making this work with the `x86-64-unknown-none` target? I'd like to avoid pull in another rust target into our build process.

2024-11-15 17:14 UTC, msft-jlange commented on kernel/src/platform/tdp.rs
> +        if vtom == 0 {
May be simpler just to `assert_ne!(vtom, 0)` so that we can panic and get it over with (with a clear error message) instead of making some other component deal with a generic error.

2024-11-15 22:10 UTC, peterfang commented on Makefile
> +	cargo rustc --target i686-unknown-linux-gnu --manifest-path stage1/Cargo.toml ${CARGO_ARGS} --features load-stage2 --bin stage1 -- -C panic=abort
I was wrestling with the "relocation truncated to fit" errors when using `x86-64-unknown-none`. I'll spend more time on this to see if there's a way to keep the target platform as is.

2024-11-15 22:10 UTC, peterfang commented on kernel/src/platform/tdp.rs
> +        if vtom == 0 {
That makes sense. Something's probably seriously wrong if we see VTOM == 0. I'll make the change.

2024-11-18 12:51 UTC, peterfang commented on Makefile
> +	cargo rustc --target i686-unknown-linux-gnu --manifest-path stage1/Cargo.toml ${CARGO_ARGS} --features load-stage2 --bin stage1 -- -C panic=abort
I have found a way to remove this error. Will be updating this PR soon.

2024-11-19 06:09 UTC, peterfang commented
> Hi Peter,
> 
> I like this change, it will simplify the build process and allows more sharing of constants and code between the different stages.
> 
> Can you please adapt the CI files to make it pass with these changes and have a look at using the existing `x86-64-unknown-none` target? I tried that already but ran into linker errors due to 32-bit relocations in 64-bit code. But maybe there is a way around that.

Hi Joerg, I sidestepped the ld issue on the CI system using `--emit=obj -C linker=/usr/bin/true`. It should work as expected now.

2024-12-10 10:51 UTC, joergroedel approved these changes
Changes look good to me now, thanks.

2024-12-10 10:55 UTC, merged