Implement a log buffer to store log messages(Draft initial commit).
coconut-svsm/svsm pull request #52
Opened 2023-06-19 16:52 UTC by vsntk18

Implemented a  global buffer to store log messages and passed this buffer from stage2 to svsm kernel. Replaced console logging with buffer logging.

Percpu line buffer will probably be necessary, and  is not yet implemented.   As a rust newbee, I appreciate your feedback on if I am using the right data structures in the right way.

2023-06-20 12:19 UTC, 00xc commented
Probably a good idea to rebase from the main branch to fix the cargo fmt checks. Also, make sure your author email matches your Signed-off-by email!

2023-06-20 12:34 UTC, vsntk18 commented
> Probably a good idea to rebase from the main branch to fix the cargo fmt checks. Also, make sure your author email matches your Signed-off-by email!
> 
> EDIT: nevermind, no need for a rebase, but the fmt checks should be fixed.

sorry, will fix the fmt checks. I was under the impression that commit hooks report the deviations.

2023-06-20 12:50 UTC, 00xc commented on src/log_buffer.rs
> +}
Can we get this into a struct? Something like:

```rust
#[derive(Clone, Copy, Debug)]
struct LogBufferState {
    full: usize,
    rc: usize,
    ...
}

impl LogBufferState {
    fn encode(self) -> usize { ... }
    fn decode(enc: usize) -> Self { ... }
}
```

Then we can do:

```rust
let pos = self.state.load(Ordering::Acquire);
let state = State::decode(pos);
...
let new_pos = state.encode();
if self
    .state
    .compare_exchange(pos, new_pos, Ordering::Acquire, Ordering::Relaxed)
    .is_ok()
{
    break;
}
```

It would be even more conventional to implement encoding and decoding via the From trait:

```rust
impl From<usize> for LogBufferState { ... }
impl From<LogBufferState> for usize { ... }
```

But that's not strictly necessary.

2023-06-20 12:50 UTC, 00xc commented on src/log_buffer.rs
> +        let mut is_full;
This is C-style coding, it's very uncharacteristic and best avoided in my opinion.

2023-06-20 12:51 UTC, 00xc commented
> sorry, will fix the fmt checks. I was under the impression that commit hook reports the deviations.

The git hook should warn you, but won't fix the issues automatically.

2023-06-20 12:52 UTC, 00xc commented on src/log_buffer.rs
> +        let mut is_full;
Unless the value of a variable needs to be kept for the next loop iteration, I'd say just shadow them by using `let`.

2023-06-20 13:19 UTC, 00xc commented on src/svsm.rs
> +    let migrate_info: &MigrateInfo = mi;
This is not necessary, right? We can simply use `mi`.

2023-06-21 07:19 UTC, vsntk18 commented on src/log_buffer.rs
> +}
Yes, using a struct makes much more sense.  Also implemented encoding and decoding via From train.

2023-06-21 07:19 UTC, vsntk18 commented on src/log_buffer.rs
> +        let mut is_full;
Yes, it's really ugly.  Got rid of it.

2023-06-21 07:21 UTC, vsntk18 commented on src/svsm.rs
> +    let migrate_info: &MigrateInfo = mi;
Removed this redundant variable.

2023-06-23 19:05 UTC, vsntk18 commented
Reworked the findings so far.
Added percpu line buffer implementation.

2023-06-29 19:52 UTC, vsntk18 commented
Status so far on this PR:
1. Implemented a global log buffer
2.  Added initialization and migration code for the log buffer.
3.  Implemented a percpu line buffer
4. Added a  feature called enable-console-log to print log messages to console.

2023-07-04 13:26 UTC, joergroedel requested changes
Provided some comments in the reviews. Please also move the logbuffer specific code into a separate sub-directory/module.

2023-07-04 13:26 UTC, joergroedel commented on src/line_buffer.rs
> +#[cfg(feature = "enable-console-log")]
For new files, please add our default file header as present in other source files.

2023-07-04 13:26 UTC, joergroedel commented on src/line_buffer.rs
> +    tail: usize,
A line buffer does not need head and tail pointers, a len is enough. Maybe you can use FixedString for it? The idea is to copy the contents of the line buffer to the global log once a newline character is encountered or the line buffer is full.

2023-07-04 13:26 UTC, joergroedel commented on src/log_buffer.rs
> +impl From<LogBufferState> for usize {
When we use locking there is no need to keep all state in a usize, you can just track separate usize members for head and tail. The wc and rc members are probably for locking, please use the RWLock or SpinLock implementations already present in the code-base.

2023-07-04 16:25 UTC, vsntk18 commented on src/log_buffer.rs
> +impl From<LogBufferState> for usize {
Wouldn't RWLock be too restrictive here?   It allows either multiple readers or a single writer in the critical section.

But keeping all state in a usize, we could allow either multiple writers or multiple readers (ok, multiple readers are probably rare), if I understand correctly.

2023-07-04 16:50 UTC, vsntk18 commented on src/line_buffer.rs
> +    tail: usize,
I had thought of using FixedString.  Since it is implemented as a char array than a u8 array, the buffer can store only 1/4 of the size with u8 array.   Is there a better reason to use FixedString here?

2023-07-05 10:54 UTC, 00xc commented on src/line_buffer.rs
> +                    unsafe { LB.write_log(st) };
Since the line buffer and the global buffer are backed by u8s perhaps could skip all this intermediate utf8 checking via `core::str::from_utf8`

2023-07-05 12:13 UTC, joergroedel commented on src/line_buffer.rs
> +    tail: usize,
The char type has an encode_utf8() method which gives you an u8 slice to store in the log buffer. This way we can buffer per-cpu (or per-task once we have tasks) as chars and write it as u8 to the global log buffer.

2023-07-05 12:15 UTC, joergroedel commented on src/log_buffer.rs
> +impl From<LogBufferState> for usize {
Lets keep things simple for now and switch to a lock implementation that we already have. The log-buffer is not performance critical, and once the system is running writes and reads are rare.

2023-07-07 18:18 UTC, vsntk18 commented on src/line_buffer.rs
> +#[cfg(feature = "enable-console-log")]
ok, I will adapt the pre-commit hook to check for this.

2023-07-11 17:02 UTC, vsntk18 commented
> Provided some comments in the reviews. Please also move the logbuffer specific code into a separate sub-directory/module.

2023-07-11 17:09 UTC, vsntk18 commented
In this PR:
1. Moved log buffer implementation to separate directory.
2. Moved line buffer implementation to src/cpu directory.
3.  Reworked line buffer to use len member instead of head and tail.  However kept the implementation as u8 array not as a FixedString,  since it seemed simple.  May be this is still arguable.
4. skipped all the intermediate utf8 checking as suggested by Carlos.

2023-08-10 11:05 UTC, 00xc commented on src/cpu/line_buffer.rs
> +                let mut buf_str: [u8; LINE_BUFFER_SIZE * 4] = [0; LINE_BUFFER_SIZE * 4];
This could simply be:

```rust
let mut buf_str = [0u8; LINE_BUFFER_SIZE * 4];
```

2023-08-10 11:07 UTC, 00xc commented on src/string.rs
> +    }
This should probably be named `clear()`, just like the `String` method:
https://doc.rust-lang.org/std/string/struct.String.html#method.clear

2023-08-10 11:14 UTC, 00xc commented on src/string.rs
> +}
This is overkill in my opinion. We can remove the `current` field and the `reset()` method by simply doing:

```rust
impl<const T: usize> FixedString<T> {
    ...
    pub fn iter(&self) -> impl Iterator<Item = char> + '_ {
        self.data.iter().take(self.len).copied()
    }
}
```

This would require doing `for ch in self.buf.iter()` instead in `LineBuffer::write_buffer()`.

2023-08-10 11:19 UTC, 00xc commented on src/string.rs
> +}
Or rather than removing `reset()` I would replace it with `clear()p  and have it set `self.len` to 0, since I think that's necessary for the `LineBuffer` logic.

2023-08-10 11:24 UTC, 00xc commented on Cargo.toml
> +default-debug = ["enable-stacktrace", "enable-console-log"]
The `default` feature has a special meaning, because it is always autoselected by cargo unless `--no-default-features` is passed. This is not super relevant because we build through a Makefile and pass features explicitly., but I'd rather keep it. Maybe we should have `default` and `default-debug`.

2023-08-10 18:03 UTC, vsntk18 commented on src/cpu/line_buffer.rs
> +                let mut buf_str: [u8; LINE_BUFFER_SIZE * 4] = [0; LINE_BUFFER_SIZE * 4];
Done!

2023-08-10 18:06 UTC, vsntk18 commented on Cargo.toml
> +default-debug = ["enable-stacktrace", "enable-console-log"]
ok,  now there are two features `default` and `default-debug`

2023-08-17 13:15 UTC, joergroedel requested changes
Can you please also add unit-tests to test the basic functionality and the edge scenarios like buffer overflow and wraparound of the buffer?

2023-08-17 13:15 UTC, joergroedel commented on src/log_buffer/mod.rs
> +        }
This empties the buffer when full, right? Please only advance tail so that the last line gets overwritten.

2023-08-17 13:15 UTC, joergroedel commented on src/log_buffer/mod.rs
> +    }
A Vec<u8> is not a good target for reading. Reading the log will most likely write the log data into a guest-provided buffer. We will decide later how to type that, so this function can be removed for now.

2023-08-17 13:25 UTC, 00xc commented on src/log_buffer/mod.rs
> +    }
Maybe taking a `&mut Vec` or a `&mut [u8]` would be the cleanest way to do it, but having these types in guest memory breaks Rust's ownership model (since the guest may write to that memory). Perhaps taking a pointer + length and doing a volatile write would be safer. Anyhow, I agree that removing this function for now is better.

2023-08-17 13:55 UTC, vsntk18 commented on src/log_buffer/mod.rs
> +    }
Yes, of course. I was just using this function just to check if log buffer was getting written correctly.

2023-08-22 09:54 UTC, roy-hopkins commented on src/log_buffer/mod.rs
> +            for item in tmp.iter().skip(1) {
If a multibyte character is followed by a single byte character then `tmp[1..3]` may contain non-zero values when processing the single byte character. You can clear `tmp` between each character, or it might make sense to use the return value from `encode_utf8` instead:

```
        let mut tmp: [u8; 4] = [0; 4];
        for ch in s.iter() {
            let utf = ch.encode_utf8(&mut tmp);
            for item in utf.as_bytes().iter() {
                self.buf[head] = *item;
                head = (head + 1) % BUF_SIZE;
            }
        }
```

2023-08-22 11:45 UTC, vsntk18 commented on src/log_buffer/mod.rs
> +            for item in tmp.iter().skip(1) {
Nice catch!  I thought the encode_utf8() would fill in the zeroes for the remaining bytes. But it doesn't.  Thanks for pointing out.

2023-08-24 08:38 UTC, vsntk18 commented on src/log_buffer/mod.rs
> +        }
This actually just updates the tail pointer when the log_write() makes the buffer full.

2023-08-24 08:38 UTC, vsntk18 commented
> Can you please also add unit-tests to test the basic functionality and the edge scenarios like buffer overflow and wraparound of the buffer?

Added some unit tests.

2024-06-10 08:46 UTC, vsntk18 commented
Needs rebase due to percpu related changes in 7e5a9a72cac97361fe0890084b16777e3ce685cb

2024-06-17 14:10 UTC, 00xc commented on kernel/src/log_buffer/mod.rs
> +    pub fn read_log(&mut self) -> Vec<u8> {
If it's only used for testing gate it behind `#[cfg(test)]` to avoid unused warnings.

2024-06-17 14:10 UTC, 00xc commented on kernel/src/log_buffer/mod.rs
> +    }
Why not pass a regular reference to the spinlock?

2024-06-17 14:10 UTC, 00xc commented on kernel/src/log_buffer/mod.rs
> +static mut LB: SpinLock<LogBuffer> = SpinLock::new(LogBuffer::new());
Why does it need to be `mut`?

2024-06-17 14:10 UTC, 00xc commented on kernel/src/log_buffer/mod.rs
> +fn test_read_write_normal() {
All of these should be in a test module, e.g.

```rust
#[cfg(test)]
mod test {
    use crate::types::LINE_BUFFER_SIZE;

    const BUF_SIZE: usize = 64;

    #[test]
    fn test_read_write_normal() {
        // ...
    }
}
```

2024-06-17 14:10 UTC, 00xc commented on kernel/src/utils/string_ring_buffer.rs
> +// Author: Roy Hopkins <roy.hopkins@suse.com>
Probably forgot to update author name :)

2024-06-17 14:10 UTC, 00xc commented on kernel/src/utils/string_ring_buffer.rs
> +fn test_ring_one_string() {
This test and the ones below should also be in a test module.

2024-06-17 14:10 UTC, 00xc commented on kernel/src/cpu/line_buffer.rs
> +        let line_buf: &mut LineBuffer = &mut this_cpu().get_line_buffer();
There's no need to add the type here, `RefMut` implements `Deref` and `DerefMut`, so access to the `LineBuffer` methods is transparent.

2024-06-17 14:10 UTC, 00xc commented on kernel/src/cpu/line_buffer.rs
> +        .expect("already initialized the logger");
I'd say return the error here and panic at the caller, just like we had before.

2024-06-19 09:07 UTC, vsntk18 commented on kernel/src/log_buffer/mod.rs
> +        self.buf.write(&s.to_string());
Changed write() interface to take char iterator as a parameter.

2024-06-19 09:07 UTC, vsntk18 commented on kernel/src/log_buffer/mod.rs
> +    pub fn read_log(&mut self) -> Vec<u8> {
done!

2024-06-19 09:09 UTC, vsntk18 commented on kernel/src/log_buffer/mod.rs
> +    }
Yes, some compilation problems made me use that.  But I have changed to use a regular reference now.

2024-06-19 09:09 UTC, vsntk18 commented on kernel/src/log_buffer/mod.rs
> +static mut LB: SpinLock<LogBuffer> = SpinLock::new(LogBuffer::new());
Not necessary.  Removed it.  Thanks!

2024-06-19 09:09 UTC, vsntk18 commented on kernel/src/log_buffer/mod.rs
> +fn test_read_write_normal() {
done!

2024-06-19 09:10 UTC, vsntk18 commented on kernel/src/utils/string_ring_buffer.rs
> +// Author: Roy Hopkins <roy.hopkins@suse.com>
No, actually Roy created this file in one of the branches. I cherry picked it to my branch. So I will let it stay. :)

2024-06-19 09:11 UTC, vsntk18 commented on kernel/src/utils/string_ring_buffer.rs
> +fn test_ring_one_string() {
done!

2024-06-19 09:11 UTC, vsntk18 commented on kernel/src/cpu/line_buffer.rs
> +        let line_buf: &mut LineBuffer = &mut this_cpu().get_line_buffer();
Removed!

2024-06-19 09:11 UTC, vsntk18 commented on kernel/src/cpu/line_buffer.rs
> +        .expect("already initialized the logger");
done!

2025-03-20 13:38 UTC, osteffenrh commented
What is the plan for this?

2025-03-20 14:09 UTC, vsntk18 commented
> What is the plan for this?

This was stalled due to lesser priority.  The changes on this PR is out-of-date, and a rebase would be necessary for the next round of review.  If you need this feature soon, I could spend some time on it next week or so.

2025-10-24 15:13 UTC, n-ramacciotti commented
Hi @vsntk18,
I'm interested in this feature for a Proof of Concept I'm developing. I noticed that this PR hasn’t been updated recently.
Do you plan to resume work on this?
I'd be glad to help if needed.

Thanks for your work on this.

2025-10-27 09:14 UTC, vsntk18 commented
> Hi @vsntk18, I'm interested in this feature for a Proof of Concept I'm developing. I noticed that this PR hasn’t been updated recently. Do you plan to resume work on this? I'd be glad to help if needed.
> 
> Thanks for your work on this.

Hi @n-ramacciotti ,   I could resume work on this. Before that I would like to sync with Jörg and others to learn about any possible changes to this feature.  I would much appreciate your help. Thanks!

2026-04-16 14:04 UTC, vsntk18 commented
Reworked log buffer implementation.

1. There is a per-task Line buffer
2. A Global log buffer backed by a RamFile
3. Added a couple of basic test-in-svsm tests for the kernel tasks

2026-04-27 07:17 UTC, joergroedel requested changes
Hi Vasant, thanks for moving this forward. The changes go into the right direction but I have some comments and questions on the design.

2026-04-27 07:17 UTC, joergroedel commented on kernel/src/fs/api.rs
> +        Ok(0)
There are a bunch of methods which only return `OK(0)` on success, which is not very useful. Either make them return the number of bytes added to the log or just `Ok(())`.

2026-04-27 07:17 UTC, joergroedel commented on kernel/src/fs/log_buffer.rs
> +}
Why does `LogBuffer` need a `File` implementation? The backing memory is the `Log/logfile` file in the RamFS, no?

2026-04-27 07:17 UTC, joergroedel commented on kernel/src/fs/log_buffer.rs
> +}
I think this struct should be a `RWLock` around a `RamFile` instance.

2026-04-27 07:51 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +}
This is the per-task Line Buffer.  RamFS backed file is the global log buffer. 

I am mirroring the ConsoleFile implementation. This LogBuffer is just a dummy interface to actual RamFS backed logfile. But it prohibits certain File operations like read, truncate etc which are not necessary for the Log file. At the same time, those operations are still needed and possible for the actual RamFS backed file.

2026-05-05 13:20 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +}
Should I change the name to LineBuffer to avoid confusion?  I used the name LogBuffer for the sake of uniformity.

2026-06-09 10:37 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +}
hmm, Access to RamFile is already synchronized, since it uses a RWLock for underlying RawRamFile, right?  Or, am I misunderstanding this?

2026-06-09 10:41 UTC, vsntk18 commented on kernel/src/fs/api.rs
> +        Ok(0)
will do that.

2026-06-10 15:22 UTC, vsntk18 commented
Addressed some suggestions made by Joerg (few might still be open for discussion) and rebased.

2026-06-11 10:29 UTC, n-ramacciotti commented on kernel/src/fs/console.rs
>  struct ConsoleBuffer {
Could this be removed and `StdoutBuffer` used directly in `ConsoleFile`?
```
pub struct ConsoleFile {
    buffer: SpinLock<StdoutBuffer>,
}
```

2026-06-11 10:29 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +pub fn log_reset() -> Result<usize, SvsmError> {
Since this is used for test in svsm, would it make sense to introduce it in the commit with the new tests ([bcef6bb](https://github.com/coconut-svsm/svsm/pull/52/changes/bcef6bb674a85185fb04d7c03a8d823b9a63b3d3)) and inside the `tests` module directly?

2026-06-11 10:51 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +        start_kernel_task(KernelThreadStartInfo::new(task1, 1), String::from("task1"))
Would it make sense to call `wait_for_termination` before checking the expected buffer?

2026-06-11 13:29 UTC, vsntk18 commented on kernel/src/fs/console.rs
>  struct ConsoleBuffer {
Good idea. Let me remove this unnecessary wrapper :)

2026-06-11 13:30 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +pub fn log_reset() -> Result<usize, SvsmError> {
Yeah, I thought there might be legitimate use for resetting the log.  But at the moment only in the test. So I will move it inside tests module. Thanks for the suggestion!

2026-06-11 13:32 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +        start_kernel_task(KernelThreadStartInfo::new(task1, 1), String::from("task1"))
Since there are only 3 tasks and no expectation of interrupts within the test, I didn't use wait_for_termination. I don't have a strong opinion on this. If you think there are good reasons for it, I can add it.

2026-06-11 14:41 UTC, vsntk18 commented
Addressed Nicola's review comments.

2026-06-11 15:00 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +        start_kernel_task(KernelThreadStartInfo::new(task1, 1), String::from("task1"))
I'm not sure that, when `start_kernel_task` returns, `task1` has already finished. It probably is, in this case `wait_for_termination` would return immediately. Let's hear from others!

2026-06-11 15:13 UTC, n-ramacciotti commented on kernel/src/console.rs
I don't know if it's necessary to keep them in the codebase, but these can be removed without consequence, as they are no longer used:
- `CONSOLE_LOGGER`
- `install_console_logger`
- `ConsoleLogger`

2026-06-11 15:16 UTC, vsntk18 commented on kernel/src/console.rs
When I resumed with this PR, stage2 was still there and using console logger.  But now it's gone I think.

2026-06-11 15:20 UTC, n-ramacciotti commented on kernel/src/console.rs
> When I resumed with this PR, stage2 was still there and using console logger. But now it's gone I think.

yes it's been removed. (#1053)

2026-06-11 16:07 UTC, n-ramacciotti commented on syscall/Cargo.toml
> +enable-console-log = []
IIUC, this feature should be also present in `userlib` and all the other userpace modules (`userinit` for the moment). And should be enabled in chain (`usermodule/enable` -> `userlib/enable` -> `syscall/enable`).

However, when enabled (even on its own by default), every call to `write_log` would cause a double write, for example:
```
[init] COCONUT-SVSM init process starting
[init] COCONUT-SVSM init process starting
```

This is due to the write to the `LOG_HANDLE`, which also prints to the console (with `kernel/enable-console-log`) and to the write to `CONSOLE_HANDLE`

That said, I'm not sure this feature should be available in `userspace`. It should probably be enough to use the kernel side feature.

2026-06-12 08:18 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +        start_kernel_task(KernelThreadStartInfo::new(task1, 1), String::from("task1"))
With the current scheduling mechanism it should. But probably it's good practice to wait_for_termination() in case something changes.  It doesn't cause any wait at the moment anyway.  so added it.

2026-06-12 08:19 UTC, vsntk18 commented on kernel/src/console.rs
Removed these unused symbols.

2026-06-12 08:21 UTC, vsntk18 commented on syscall/Cargo.toml
> +enable-console-log = []
Yeah, I haven't put much thought into userspace yet.  There aren't even tests yet, which I plan to add after https://github.com/coconut-svsm/svsm/pull/926 is merged. Let's revisit it as userspace evolves?

2026-06-12 08:49 UTC, vsntk18 commented
Addressed comments from Nicola

2026-06-12 09:11 UTC, n-ramacciotti commented on syscall/Cargo.toml
> +enable-console-log = []
> which I plan to add after https://github.com/coconut-svsm/svsm/pull/926 is merged. Let's revisit it as userspace evolves?

I'm not sure when #926 will be merged, but I agree. For the moment I think it is sufficient to drop the feature from `syscall` and `CONSOLE_HANDLE` from `syscall/log_buffer`, and address it later (maybe with a separate PR)

2026-06-12 09:23 UTC, vsntk18 commented on syscall/Cargo.toml
> +enable-console-log = []
yeah, dropped it for now.

2026-06-12 09:43 UTC, n-ramacciotti commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
What about changing this to `LineBuffer`? and moving it out of `api.rs` to `kernel/src/fs/buffer.rs`?

2026-06-12 09:43 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +struct LineBuffer {
What about changing this to `LogFile` (or something similar), mirroring `ConsoleFile`?

2026-06-12 09:43 UTC, n-ramacciotti commented on kernel/src/log_buffer.rs
> +static LOGGER: ImmutAfterInitCell<SpinLock<LogBuffer>> = ImmutAfterInitCell::uninit();
What about changing this to `BUFFER`?

2026-06-12 16:19 UTC, vsntk18 commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
I hadn't paid attention to Buffer trait. I made LineBuffer implement Buffer trait. I consolidated Console file and Log file into a single struct that way. kernel/src/fs/console.rs can be removed. How do you like this idea?

2026-06-12 16:20 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +struct LineBuffer {
This won't be necessary after the changes I indicated in the above comment

2026-06-12 16:20 UTC, vsntk18 commented on kernel/src/log_buffer.rs
> +static LOGGER: ImmutAfterInitCell<SpinLock<LogBuffer>> = ImmutAfterInitCell::uninit();
BUFFER would be too generic a name in my opinion

2026-06-12 16:34 UTC, n-ramacciotti commented on kernel/src/log_buffer.rs
> +static LOGGER: ImmutAfterInitCell<SpinLock<LogBuffer>> = ImmutAfterInitCell::uninit();
Yeah right

2026-06-12 16:35 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +struct LineBuffer {
But you did change `LineBuffer` to `LogFile` IIUC

2026-06-12 16:36 UTC, n-ramacciotti commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
It makes much sense!

2026-06-12 16:44 UTC, n-ramacciotti commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
I'm losing track of things in the commit history. What do you think about squashing some fixes? @vsntk18

2026-06-15 08:17 UTC, vsntk18 commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
@n-ramacciotti  I could do that. But wouldn't it easy for you to just review the delta from the last state? For example:  commit fd444abab42d4 is the implementation of the suggestions in your last round of review.

2026-06-15 08:18 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +struct LineBuffer {
Yeah, LineBuffer is shared by both console and logbuffer now.

2026-06-15 08:23 UTC, stefano-garzarella commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
+1 on squashing, please. I usually review patch by patch and having things fixed later will increase a lot the time to review.

2026-06-15 08:31 UTC, n-ramacciotti commented on kernel/src/fs/api.rs
> +pub struct StdoutBuffer {
I like the new changes in https://github.com/coconut-svsm/svsm/commit/fd444abab42d4a78ef4aaa5777e723df165893c5.

> I usually review patch by patch and having things fixed later will increase a lot the time to review.

I also prefer to review one commit at a time. Without squashing, the next round of reviews would involve a lot of back-and-forth between different commits.

2026-06-15 09:15 UTC, n-ramacciotti commented on kernel/src/fs/filesystem.rs
> +        assert!(root_list.contains(&FileName::from("test2")));
These tests have been changed as the root list now contains the log file. I had a similar issue in `test-in-svsm userspace PR` (where I have userspace binaries in the fs, see commit https://github.com/coconut-svsm/svsm/pull/926/changes/eef70b35df596cab1396eb50d065321f3c606560).

It makes sense to add here also:
```
assert!(!root_list.contains(&FileName::from("test1")));
```

Nit: What about moving these assert changes to a separate commit? It's just a personal preference, not a strong opinion.

2026-06-15 10:21 UTC, vsntk18 commented on kernel/src/fs/filesystem.rs
> +        assert!(root_list.contains(&FileName::from("test2")));
Addressed in c62bda8f7d212821e2983ee03ebb0a4f91692806.

2026-06-15 10:35 UTC, n-ramacciotti commented on kernel/src/fs/console.rs
> +pub fn stdout_open(_name: String) -> (Arc<dyn Obj>, Arc<dyn Obj>) {
What about moving these changes in a subsequent commit after `LogFile` introduction? I don't see an advantage of having two `ConsoleFile` here, considering that it also  will be dropped after

Edit: this comment is marked as outdated probably because `console.rs` has been removed, but I think it is still relevant.

2026-06-15 12:19 UTC, vsntk18 commented on kernel/src/fs/console.rs
> +pub fn stdout_open(_name: String) -> (Arc<dyn Obj>, Arc<dyn Obj>) {
Yeah, I suppose I can reorder those comments.

2026-06-15 12:31 UTC, vsntk18 commented
Reordered few commits to address Nicola's comments. No functional changes.

2026-06-15 13:01 UTC, n-ramacciotti commented
```
log_buffer: implement Buffer trait for line buffer
This way we can consolidate console buffer and log buffer into a
single line buffer.
```
Couldn't this also be done without implementing the `Buffer` trait?

2026-06-15 13:04 UTC, vsntk18 commented
> ```
> log_buffer: implement Buffer trait for line buffer
> This way we can consolidate console buffer and log buffer into a
> single line buffer.
> ```
> 
> Couldn't this also be done without implementing the `Buffer` trait?

Of course, it could be done that way. Semantically LineBuffer is a 'Buffer', so I just moved it to buffer.rs.  And, there is no real advantage. But I don't see any disadvantages either

2026-06-15 13:11 UTC, n-ramacciotti commented
> Of course, it could be done that way. Semantically LineBuffer is a 'Buffer', so I just moved it to buffer.rs. And, there is no real advantage. But I don't see any disadvantages either

Yeah, I don't see any disadvantages neither. 

My thoughts were on the commit message: from the title I understand that it's  thanks to `Buffer` trait that it is possible to obtain a single struct for both. When in reality it's just a plus

2026-06-15 13:17 UTC, vsntk18 commented
> > Of course, it could be done that way. Semantically LineBuffer is a 'Buffer', so I just moved it to buffer.rs. And, there is no real advantage. But I don't see any disadvantages either
> 
> Yeah, I don't see any disadvantages neither.
> 
> My thoughts were on the commit message: from the title I understand that it's thanks to `Buffer` trait that it is possible to obtain a single struct for both. When in reality it's just a plus

ok. yeah, if you have a suggestion for a more clear commit message, please let me know.

2026-06-15 14:10 UTC, n-ramacciotti commented
> ok. yeah, if you have a suggestion for a more clear commit message, please let me know.

What about something like:
```
kernel/log_buffer: Introduce line buffer

Console and File handling require both line buffering and only differ on the destination.

Modify `ConsoleBuffer` to accept an additional parameter (`is_console`) to differentiate
and redirect output to the correct handling.

Rename `ConsoleBuffer` to `LineBuffer` to better explain its behaviour.

Additionally, given that it is a buffer, implement `Buffer` trait on top of it.
```

Note that I didn't mention `StdoutBuffer` as it is not used in the final changes and can be dropped from the history.

what do you think?

2026-06-15 14:13 UTC, vsntk18 commented
> > ok. yeah, if you have a suggestion for a more clear commit message, please let me know.
> 
> What about something like:
> 
> ```
> kernel/log_buffer: Introduce line buffer
> 
> Console and File handling require both line buffering and only differ on the destination.
> 
> Modify `ConsoleBuffer` to accept an additional parameter (`is_console`) to differentiate
> and redirect output to the correct handling.
> 
> Rename `ConsoleBuffer` to `LineBuffer` to better explain its behaviour.
> 
> Additionally, given that it is a buffer, implement `Buffer` trait on top of it.
> ```
> 
> Note that I didn't mention `StdoutBuffer` as it is not used in the final changes and can be dropped from the history.
> 
> what do you think?

Yeah, that looks good to me. Thanks for the suggestion!

2026-06-15 14:26 UTC, n-ramacciotti commented
My idea was to drop entirely `StdoutBuffer` from the history. Like removing it from https://github.com/coconut-svsm/svsm/pull/52/changes/f4591554cfac61b7a86c5a5b4ff826ecfa55bd3e and directly introducing there `LineBuffer`.

2026-06-15 14:29 UTC, vsntk18 commented
> My idea was to drop entirely `StdoutBuffer` from the history. Like removing it from [f459155](https://github.com/coconut-svsm/svsm/commit/f4591554cfac61b7a86c5a5b4ff826ecfa55bd3e) and directly introducing there `LineBuffer`.

yes, of course. If the changes are functionally ok, I could try to reduce the number of commits.

2026-06-15 14:53 UTC, n-ramacciotti commented on kernel/src/task/schedule.rs
> +            .map_or(self.idle_task.as_ref().unwrap().clone(), |t| t.clone())
Without this change, it doesn't print anything. It seems important, could you please mention why this is needed in the commit message?

2026-06-15 14:59 UTC, n-ramacciotti commented on kernel/src/task/tasks.rs
> +        if args.thread_of.is_none() {
It is also worth mentioning in the commit that this is now done for both kernel and user tasks, while before it was only done for user tasks

2026-06-15 15:08 UTC, n-ramacciotti commented on kernel/src/svsm.rs
> +    install_buffer_logger();
I would mention it and also explain why in the commit description

2026-06-15 15:08 UTC, n-ramacciotti commented
@vsntk18 I left some minor comments. The rest LGTM. Thanks!

2026-06-15 17:24 UTC, vsntk18 commented on kernel/src/task/schedule.rs
> +            .map_or(self.idle_task.as_ref().unwrap().clone(), |t| t.clone())
yeah, will add

2026-06-16 07:40 UTC, vsntk18 commented on kernel/src/svsm.rs
> +    install_buffer_logger();
hmm, I am not sure about this tbh. I think it's an extra detail and would be a distraction in the commit message. But I left it as a comment so that if someone wants to move the code around, they keep this invariant in mind.

2026-06-16 07:47 UTC, vsntk18 commented on kernel/src/task/tasks.rs
> +        if args.thread_of.is_none() {
I mentioned in the commit message now that it's done for both user and kernel tasks.

2026-06-16 08:00 UTC, vsntk18 commented
dropped StdoutBuffer from history, and adjusted some commit messages.

2026-06-16 12:57 UTC, n-ramacciotti commented on kernel/src/svsm.rs
> +    install_buffer_logger();
Yeah, right. It is easier to spot in the code. All the new fixes and the PR in general LGTM!

2026-06-16 13:01 UTC, vsntk18 commented on kernel/src/svsm.rs
> +    install_buffer_logger();
Thanks for the review!

2026-06-17 12:22 UTC, n-ramacciotti commented
> Implemented a global buffer to store log messages and passed this buffer from stage2 to svsm kernel. Replaced console logging with buffer logging.
> 
> Percpu line buffer will probably be necessary, and is not yet implemented. As a rust newbee, I appreciate your feedback on if I am using the right data structures in the right way. Thanks!

nit: since the code has changed significantly from this version. Could this description be updated? Using also the "Fixes: issue number" tag to highlight better the relationship with the issue section (in this way it will be closed automatically once this is merged)

2026-06-17 12:40 UTC, vsntk18 commented
> > Implemented a global buffer to store log messages and passed this buffer from stage2 to svsm kernel. Replaced console logging with buffer logging.
> > Percpu line buffer will probably be necessary, and is not yet implemented. As a rust newbee, I appreciate your feedback on if I am using the right data structures in the right way. Thanks!
> 
> nit: since the code has changed significantly from this version. Could this description be updated? Using also the "Fixes: issue number" tag to highlight better the relationship with the issue section (in this way it will be closed automatically once this is merged)

That description suited the first version of the PR was created. Since then there were many changes in the design etc. The most recent description is: https://github.com/coconut-svsm/svsm/pull/52#issuecomment-4260684856

Linking the Fixes: #issue is a good idea. Thanks for the suggestion.  Let me do that :)

2026-06-17 13:20 UTC, n-ramacciotti commented
> Fixes: https://github.com/coconut-svsm/svsm/issues/12
>
>Signed-off-by: Vasant Karasulli <vasant.karasulli@suse.com>

There shouldn't be a space here to be considered a trailer (by git) and (maybe, but not tested) recognized by github.

In this PR, I see:

```
Successfully merging this pull request may close these issues.

None yet
```

IMHO: commit https://github.com/coconut-svsm/svsm/pull/52/changes/bce8181214279ee66650dda350ac3b168c180140 is more suited to have this trailer

Probably it's needed in the PR description.

2026-06-17 13:44 UTC, vsntk18 commented
> > Fixes: #12
> > Signed-off-by: Vasant Karasulli [vasant.karasulli@suse.com](mailto:vasant.karasulli@suse.com)
> 
> There shouldn't be a space here to be considered a trailer (by git) and (maybe, but not tested) recognized by github.
> 
> In this PR, I see:
> 
> ```
> Successfully merging this pull request may close these issues.
> 
> None yet
> ```

Are you sure?  I see Fixes tag with a space like that in many other commits, 92c082eb7cc7e3b4f68805b20e78cd2f0ac9aae1 for example
> 
> IMHO: commit [bce8181](https://github.com/coconut-svsm/svsm/commit/bce8181214279ee66650dda350ac3b168c180140) is more suited to have this trailer
> 
> Probably it's needed in the PR description.

Well, that's a toss up between 2 commits, whether the implementation of the buffer or redirecting to the buffer. But I can change it to your suggestion :)

2026-06-17 13:50 UTC, n-ramacciotti commented
> Are you sure? I see Fixes tag with a space like that in many other commits, [92c082e](https://github.com/coconut-svsm/svsm/commit/92c082eb7cc7e3b4f68805b20e78cd2f0ac9aae1) for example

I did a test and it  seems that it doesn't work neither even without the space. I'm pretty sure that git trailers should be a single block. (see [1]). I don't know how GitHub works though. 

> > IMHO: commit [bce8181](https://github.com/coconut-svsm/svsm/commit/bce8181214279ee66650dda350ac3b168c180140) is more suited to have this trailer
> > Probably it's needed in the PR description.
> 
> Well, that's a toss up between 2 commits, whether the implementation of the buffer or redirecting to the buffer. But I can change it to your suggestion :)

It's good also in the current commit. I don't have a strong preference.

[1] https://lore.kernel.org/git/xmqqr1k3w1g7.fsf@gitster.g/

2026-06-25 08:10 UTC, vsntk18 commented
Addressed Jörg's review comments:
          Enabled console output by default for both DEBUG and RELEASE builds. Console output can still be disabled by defining environment variable DISABLE_CONSOLE_LOG.

2026-07-10 13:47 UTC, vsntk18 commented
Rebased the PR.

Enabled console output by default for both DEBUG and RELEASE builds. Console output can still be disabled by defining environment variable DISABLE_CONSOLE_LOG.

2026-07-10 14:21 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +    let log_file: Arc<dyn File> = Arc::new(LogFile::new(taskname.clone(), false));
Do we really need to have both `console_file` and `log_file`? IIUC, kernel tasks during logging uses only the `log_file` (obj handle 1), which will also print to the console if enabled. If a kernel task want to print to the console it can directly use `console_write`. User tasks are therefore the only user of obj handle 0 and I don't think that a user task should be able to print to the console if the kernel disabled console log.

I believe this can also be addressed in a separate and subsequent PR if we want to merge this PR soon.

2026-07-10 14:36 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +    let log_file: Arc<dyn File> = Arc::new(LogFile::new(taskname.clone(), false));
> I don't think that a user task should be able to print to the console if the kernel disabled console log.

I am not sure about that.  Kernel might disable console log and user task still can call console_print() function to print messages to console, which in turn fetches the task specific console file.

2026-07-10 14:42 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +    let log_file: Arc<dyn File> = Arc::new(LogFile::new(taskname.clone(), false));
> Kernel might disable console log and user task still can call console_print() 

yes, exactly. I'm not sure this is a good behavior. My idea was to leave only one handler (on of `CONSOLE_HANDLE` or `LOG_HANDLE`), removing the ability for userspace to print directly to the console, but only through the console file handler, which leave the final decision to kernel (`enable_console_log`). Essentially, IMO, userspace should not be able to print directly neither it should know where the message is logged (console or log file).

2026-07-10 14:58 UTC, vsntk18 commented on kernel/src/fs/log_buffer.rs
> +    let log_file: Arc<dyn File> = Arc::new(LogFile::new(taskname.clone(), false));
It makes sense, yes. But I don't think user space consideration is complete with this PR, as we discussed before. I still need to add tests. I will revisit this.

2026-07-10 15:04 UTC, n-ramacciotti commented on kernel/src/fs/log_buffer.rs
> +    let log_file: Arc<dyn File> = Arc::new(LogFile::new(taskname.clone(), false));
Yes, this can be addressed also later!

2026-07-10 15:17 UTC, joergroedel reviewed
Hi Vasant,

Thanks for driving this forward. I found why I do not see anything when I build with this PR. Please also add the `enable-console-log` feature in the build recipes under `config/`.

Also there seem to be non-trivial conflicts with the user-mode testing PR I just merged, can you please have a look? I wasn't able to quickly resolve it and get `make test-in-svsm` working again.

Thanks!

2026-07-10 15:21 UTC, vsntk18 commented
> Hi Vasant,
> 
> Thanks for driving this forward. I found why I do not see anything when I build with this PR. Please also add the `enable-console-log` feature in the build recipes under `config/`.
> 
> Also there seem to be non-trivial conflicts with the user-mode testing PR I just merged, can you please have a look? I wasn't able to quickly resolve it and get `make test-in-svsm` working again.
> 
> Thanks!

Ok, will take a look. Thanks for the review.

2026-07-10 16:41 UTC, vsntk18 commented
Rebased the PR.

Addressed Joerg's comment:
added the enable-console-log feature in the build recipes under config/

2026-07-10 18:17 UTC, n-ramacciotti commented on user/lib/src/testing.rs
> +use crate::{log_msg, print, println};
This can be avoided by using "$crate" when introducing the new println and print. See https://github.com/coconut-svsm/svsm/commit/80c99e9a8e3b14992abe73b355a067ef792ba1fc

2026-07-11 10:00 UTC, joergroedel commented on user/lib/src/testing.rs
> +use crate::{log_msg, print, println};
Let's change that as a follow-on, thanks.

2026-07-11 10:01 UTC, joergroedel approved these changes

2026-07-11 10:07 UTC, vsntk18 commented on user/lib/src/testing.rs
> +use crate::{log_msg, print, println};
Yeah, I will send a separate small fix.

2026-07-11 10:31 UTC, merged