kernel/tdx: Fix TDX error codes
coconut-svsm/svsm pull request #524
Opened 2024-11-21 08:06 UTC by peterfang

- Fix the definition of TdxError::PageAlreadyAccepted
- Handle TDX_OPERAND_BUSY in TDG.MEM.PAGE.ACCEPT
- Do sanity checks on status codes

2024-11-21 15:45 UTC, msft-jlange commented on kernel/src/tdx/error.rs
> +    if code == 0 {
The TDX architecture defines results codes less than 0x8000_0000_0000_0000 as non-fatal conditions.  We can't treat a non-zero success condition as an error.  This is why this function is defined to return a `u64` in the `Ok` variant of the result - to provide a specific value of the success return in case it is a non-zero success value.

2024-11-21 15:46 UTC, msft-jlange commented on kernel/src/tdx/tdcall.rs
> +            Err(TdxError::OperandBusy) => continue,
My understanding is that TDX_OPERAND_BUSY only applies to TDH operations and not TDG operations.  When a TDG operation encounters a busy state, the TDX module will simply not advance RIP past the `tdcall` instruction, so the TD will naturally just reattempt the same call again.

2024-11-21 15:49 UTC, msft-jlange requested changes

2024-11-21 15:49 UTC, msft-jlange commented on kernel/src/tdx/tdcall.rs
> +    for _ in 0..10000 {
What makes 10000 - or any other arbitrary constant - a reasonable retry count?  Any retry count needs to be justified with on an architectural basis.

2024-11-21 18:26 UTC, peterfang commented on kernel/src/tdx/error.rs
> +    if code == 0 {
Yes, there are recoverable and unrecoverable error codes. I was going through those and was unable to come up with a conclusion as to whether SVSM would view them as OK() cases, and hence this change.
Are you okay with `PageAlreadyAccepted` being an Ok() case then? That would also mean conditions like `tdx_result(ret).is_ok()` would include this case.

2024-11-21 18:29 UTC, peterfang commented on kernel/src/tdx/tdcall.rs
> +            Err(TdxError::OperandBusy) => continue,
`TDX_OPERAND_BUSY` is a possible outcome for TDG calls as well. In this case, `TDG.MEM.PAGE.ACCEPT` could fail to acquire an internal lock (i.e. SEPT lock) due to a host or a TDX module operation.

2024-11-21 18:37 UTC, peterfang commented on kernel/src/tdx/tdcall.rs
> +    for _ in 0..10000 {
It was an empirical number that I saw in reference code. Do you have any suggestions on how we can improve this?
There are also implementations in the Linux kernel (for TDH calls) where this is retried indefinitely until the call returns a difference status code. I wasn't not sure if we want to adopt that strategy in SVSM.

2024-11-21 18:37 UTC, peterfang commented on kernel/src/tdx/tdcall.rs
> +unsafe fn accept_one_page(frame: PageFrame) -> Result<(), TdxError> {
I can confirm that `TDX_OPERAND_BUSY` is a case we should handle.

2024-11-21 18:42 UTC, msft-jlange commented on kernel/src/tdx/error.rs
> +    if code == 0 {
Somehow I had missed that TDX_PAGE_ALREADY_ACCEPTED was in the range of success codes.  I think a better approach here would be to define a `TdxSuccess` class to enumerate specific known success values, and to change this function to return `Result<TdxSuccess, TdxError>`.  Callers of `tdg_mem_page_accept` can match on `Ok(PageAlreadyAccepted)` instead of `Err(PageAlreadyAccepted)` to get the behavior we need.  But in general, `is_ok()` should always match all success codes.

2024-11-21 18:43 UTC, msft-jlange commented on kernel/src/tdx/tdcall.rs
> +    for _ in 0..10000 {
Looping forever is reasonable.  It is likely to produce a better outcome than random errors.

2024-11-21 18:49 UTC, msft-jlange commented on kernel/src/tdx/error.rs
> +pub enum TdVmcallError {
I don't see any conversion path from `TdVmcallError` to `SvsmError`.  We want to ensure that all defined error types can be represented in `SvsmError`.  I suspect that the best way to do this is not to define `TdVmcallError` as a separate class, but rather as an element of `TdxError`.  Then your ` tdvmcall_result` function could return `TdxError::TdVmcallError(result)` and stay within the error class that is already established.

2024-11-21 19:00 UTC, peterfang commented on kernel/src/tdx/tdcall.rs
> +unsafe fn accept_one_page(frame: PageFrame) -> Result<(), TdxError> {
Sure, I can simply retry on all recoverable error codes when doing a TDCALL.

2024-11-21 19:01 UTC, peterfang commented on kernel/src/tdx/error.rs
> +pub enum TdVmcallError {
Good idea. I'll make this change.

2024-11-22 17:08 UTC, msft-jlange approved these changes

2024-11-22 20:17 UTC, peterfang commented on kernel/src/tdx/tdcall.rs
> +    // r10 is guaranteed to be TDG.VP.VMCALL_SUCCESS
Sure, `debug_assert`  make sense here.

2024-11-25 08:36 UTC, merged