svsm: add SVSM VTPM Service Attestation
coconut-svsm/svsm pull request #541
Opened 2024-11-28 14:06 UTC by IT302

vTPM service attestation is described in section 8.3 of "Secure VM Service Module for SEV-SNP Guests, Publication #58019 Revision: 1.00 Issue Date: July 2023". It certifies the Endorsement Key (EK) of the vTPM by providing the TPMT_PUBLIC structure of the EK. This is crucial for downstream projects like Keylime, as the SVSM vTPM lacks an EK certificate found in physical TPMs to anchor trust.

The attestation is part of the SVSM Attestation Protocol and uses the SVSM_ATTEST_SINGLE_SERVICE call (see section 7 of the specifications). It is triggered by making an SVSM_ATTEST_SINGLE_SERVICE call with the GUID set to c476f1eb-0123-45a5-9641-b4e7dde5bfe3. The attestation code returns the VMPL0 attestation report and the vTPM Service Manifest Data Structure (TPMT_PUBLIC structure of the EK). The REPORT_DATA in the SNP attestation request is the SHA-512 digest of the input nonce and the vTPM Service Manifest Data Structure.

The vTPM initialization function was modified to generate an RSA 2048-bit EK from the TPM's Endorsement Primary Seed (EPS) and cache the public key as a TPMT_PUBLIC structure. This cached EK public key can be retrieved later for vTPM service attestation. The EK is created with the TCG default EK template (see Table 4 of the "TCG EK Credential Profile For TPM Family 2.0; Level 0 Version 2.5 Revision 2.0"). Since the EK is derived from the EPS, it can be recreated upstream at any time. For example, the same EK can be recreated in an OS using the TSS2 command "tpm2_createek -c ek.ctx -G rsa -u ek.pub" and compared against the one returned by vTPM service attestation.

vTPM service attestation as specified can only return one type of EK, so the implementation supports RSA 2048-bit EK as defined in Table 4 of the "TCG EK Credential Profile For TPM Family 2.0; Level 0 Version 2.5 Revision 2.0," which is the most common Trusted Computing Group(TCG) EK type.

Resolves coconut-svsm/svsm#437, resolves coconut-svsm/svsm#361

2024-11-28 14:07 UTC, IT302 commented
We need this for our upcoming Keylime TEE enhancements. There is an OS level test script for testing the feature, https://github.com/hpe-security-lab/svsm-vtpm-test

2024-12-11 15:27 UTC, joergroedel commented
@cclaudio can you please help to review this?

2024-12-11 18:22 UTC, tlendacky commented
> Attest single service doesn’t bind the fact that it’s a single service request, so it could be interpreted as a full attestation that just has one service, right? That could be a problem if you want to ensure a service is missing.

The manifest output of a single service vs all services is different, with the all services call containing the all services manifest GUID.

2024-12-14 01:42 UTC, cclaudio requested changes
Hi @IT302, thank you for the PR. I have made some comments and requested a few changes.

We should be able to send ATTEST requests to SVSM from guest userspace , see [1] for ABI specification and [2] for example. It would be great if we can test this PR through that interface.

[1] - https://github.com/coconut-svsm/linux/blob/svsm/Documentation/ABI/testing/configfs-tsm
[2] - https://github.com/coconut-svsm/linux/commit/70e6f7e2b98575621019aa40ac616be58ff984e0

2024-12-16 14:50 UTC, IT302 commented
> Hi @IT302, thank you for the PR. I have made some comments and requested a few changes.
> 
> With the ATTEST protocol implemented in the SVSM, we should be able to call it from guest userpsace through the configfs-tsm interface , see [1] for ABI specification and [2] for example. It would be great if we can test this PR through that interface.
> 
> [1] - https://github.com/coconut-svsm/linux/blob/svsm/Documentation/ABI/testing/configfs-tsm [2] - [coconut-svsm/linux@70e6f7e](https://github.com/coconut-svsm/linux/commit/70e6f7e2b98575621019aa40ac616be58ff984e0)

We’ve already tested the PR with the Linux configfs-tsm (check out the test script here: https://github.com/hpe-security-lab/svsm-vtpm-test). We’ve also successfully tested it with our Keylime TEE attester and verifier, and we’ll push those changes up once this PR is merged.

2024-12-16 14:51 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +fn attest_multiple_service(_params: &RequestParams) -> Result<(), SvsmReqError> {
Good catch!

2024-12-16 14:58 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +            ekpub: None,
The EKpub effectively serves as the vTPM’s “permanent”  identity and, in my opinion, should be generated and managed exclusively by the vTPM. Crucially, it is created during the vTPM’s initialization phase, before the vTPM is "handed off" to untrusted lower privileged VMPL users. Keeping the identity generation process fully self-contained within the vTPM’s initialization routine helps ensure that it maintains a single, consistent identity. This approach also reduces the likelihood of being tricked into signing unapproved identities by changing the EPS for example and requesting  VTPM attestation.

Each service should generate and provide what it  considers as  the valid service manifest data, and the attestation protocol subsystem  should be only concerned  with getting the manifest attested.  This way, we can keep coupling of subsystems to the barest minimum and improve maintainability. Perhaps, we should rename vtpm_get_ekpub() to vtpm_get_manifest() to make the intent clearer.

2024-12-16 15:01 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +    let manifest = vtpm_get_ekpub()?;
From my understanding of the SVSM spec, vTPM service attestation  does not use the Services Manifest format  defined in Table 12: Services Manifest. Page 29 of the spec says “The services manifest is identified by a 16-byte GUID, 4-byte length, and a 4-byte services count
at the beginning of the manifest. …”

Section 7.2 SVSM_ATTEST_SINGLE_SERVICE Call, which covers the attestation of single services, says on page 31:
“The SVSM will assemble a service manifest that will be used as input to the attestation request.
The service will produce a descriptive manifest in a service-defined format. If the size of the
assembled service manifest exceeds the size of the supplied service manifest buffer, RCX will be
set to the size of the service manifest (in bytes), and the call will return
SVSM_ERR_INVALID_PARAMETER.”

 
I took the above to mean that each service will define its own service manifest, and the services manifest in Table 12 is not a requirement. Note that Section 7.1 and Table 12 talk about services manifest, while Section 7.2 talks about service manifest.

Jumping to 8.3.3 SVSM_ATTEST_SINGLE_SERVICE Manifest Data. It says “The manifest data used in an SVSM_ATTEST_SINGLE_SERVICE call for manifest version 0 is
specified according to the following table.” The table is Table 18: vTPM Service Manifest Data Structure on page 36 which basically says that TPMT_PUBLIC structure of the endorsement key says at byte offset zero. 

Did I misinterpret the spec?

2024-12-16 15:01 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +fn attest_single_vtpm(
Make sense. Will look into it.

2024-12-16 15:03 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +    fn get_ekpub(&self) -> Result<Vec<u8>, SvsmReqError> {
Good idea. Where exactly in libtcgTPM are you thinking? Moving into the core TcgTPM means we will have to patch TcgTPM each time we update it.

A halfway house could be what was suggested by @stefano-garzarella , which is to import the TPM symbols via bindings.

2024-12-16 15:06 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +const TPM_RS_PW: u32 = 0x40000009;
Good idea. Will look into it.

2024-12-16 15:14 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // See Table 12 — Password Authorization Command of
That sounds good! But we’d need some code to create and marshal the parameters based on the TCG EK Credential Profile for TPM Family 2.0 inside the TcgTpm implementation. Wouldn’t that make updating the TcgTpm subsequently more complicated since our changes won’t be upstream? As you said, we can revisit this if we need to marshal many TPM commands.

2024-12-16 15:15 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +    // Validate that the report is not empty
Good catch , that's  an old comment

2024-12-16 15:21 UTC, tlendacky commented on kernel/src/protocols/attestation.rs
> +    let manifest = vtpm_get_ekpub()?;
No, you did not misinterpret the spec.

SVSM_ATTEST_SERVICES will build a specific formatted table for all services with offsets and lengths to each services manifest and each service supplying version 0 of their manifest.

SVSM_ATTEST_SINGLE_SERVICE allows you to request a specific manifest version (of which vTPM only currently has version 0) and that manifest is supplied directly in the manifest buffer (document bug: the SVSM_ATTEST_SINGLE_SERVICE RCX description should reference Table 13, not Table 11).

2024-12-16 21:04 UTC, cclaudio commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // See Table 12 — Password Authorization Command of
This is the function I am talking about
[TPM2_CreatePrimary()](https://github.com/TrustedComputingGroup/TPM/blob/f490f0078a8af4080ddf6cba8753f9f3363bae6f/TPMCmd/tpm/include/private/prototypes/CreatePrimary_fp.h#L39
). We would not need to change the upstream code, just create some bindings using bindgen. The function already handles (un)marshalling and have a return code that is much easier to work with.

The link below points to an old draft branch I have, but you can how TPM2_CreatePrimary could be used.
https://github.com/cclaudio/svsm/commit/d3fb0bb5756e69f71ce01f3fb4c0b1b3a0d3eaec

2024-12-16 21:33 UTC, cclaudio commented on kernel/src/vtpm/tcgtpm/mod.rs
> +    fn get_ekpub(&self) -> Result<Vec<u8>, SvsmReqError> {
I think it could be something like `libtcgtpm/src/cmds.rs`. The functions provided by this file could be added to lib.rs, which would already include the additional bindings created through bindgen.

2024-12-16 23:06 UTC, cclaudio commented on kernel/src/protocols/attestation.rs
> +    let manifest = vtpm_get_ekpub()?;
My bad, I just revisited the spec and you guys are right. Sorry about that.

2024-12-16 23:08 UTC, cclaudio commented on kernel/src/vtpm/tcgtpm/mod.rs
> +    fn get_ekpub(&self) -> Result<Vec<u8>, SvsmReqError> {
My only concern is that maintaining the `create_ek_rsa2048` may not be easy long term because it is hand crafting a TPM command that is relativaly complex. On the other hand, it is just one function, for now I think can just import the TPM symbols via bindings as @stefano-garzarella suggested.

I was thinking about some options but none of them seem to be optimal. One option could be to move some of its logic to libtcgtpm to reduce the `create_ek_rsa2048` complexity in the kernel crate.

Another idea could be to use functions that are already implemented by the upstream TPM implementation, e.g. TPM2_CreatePrimary. However, I just revisited it and it is an internal/private API, in other words, it's not necessarily stable.

2024-12-16 23:08 UTC, cclaudio commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // See Table 12 — Password Authorization Command of
The upstream `TPM2_CreatePrimary` implementation already handles (un)marshalling, no upstream change required. However, as I mentioned before, this API may not be stable since it is internal/private. So, never mind.

2024-12-16 23:19 UTC, cclaudio commented on kernel/src/vtpm/tcgtpm/mod.rs
> +            ekpub: None,
We can create it in the vTPM initialization phase, my suggestion was about where we should cache it. But yeah, I agree with you, caching it here in the TcgTpm structure looks better.

2024-12-17 15:29 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // Level 2 Revision 10".
This is not meant to be function documentation. It is an implementation note for whoever is going to work on the code, similar to the one `init()` function below. Perhaps changing "Creates" to "Create" may make the intention clearer.

2024-12-18 13:55 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +]);
I tried using the pattern above, but `from` and `from_str` are non-const functions, so the compiler did not accept them. 
I also attempted the following implementation:

```rust
impl Uuid {
    pub const fn new() -> Self {
        Uuid { data: [0; 16] }
    }

    pub const fn from_bytes(mem: &[u8; 16]) -> Self {
        Self {
            data: [
                mem[3], mem[2], mem[1], mem[0], mem[5], mem[4], mem[7], mem[6], mem[8], mem[9],
                mem[10], mem[11], mem[12], mem[13], mem[14], mem[15],
            ],
        }
    }
}

impl From<&[u8; 16]> for Uuid {
    fn from(mem: &[u8; 16]) -> Self {
        Uuid::from_bytes(mem)
    }
}
```

However, the compiler complained that to use a constant of type `Uuid` in a pattern, `Uuid` must be annotated with `#[derive(PartialEq)]` and that the traits must be derived; manual `impl`s are not sufficient.

Do you understand the reasoning behind the way utils::fw_meta::Uuid is implemented.  It seems there is no way to build a UUID from a string or bytes at compile time.

The external `uuid` crate provides a uuid! macro that allows for compile-time generation of UUIDs. Would it be better to use this instead?

2024-12-18 14:01 UTC, stefano-garzarella commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // Level 2 Revision 10".
Okay, I see now!

2024-12-18 16:32 UTC, cclaudio commented on kernel/src/protocols/attestation.rs
> +]);
Hmm .. I don't remember why we have our own UUID implementation, maybe for simplicity.

I think you are talking about https://docs.rs/uuid/latest/uuid. It seems they have a support for no-std (see Embedded section), but they also have some dependencies on serde which might not be needed in the SVSM. 

@joergroedel any thoughts about start using uuid? We would need to test it, but it seems ok.

2024-12-18 16:50 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +]);
> I think you are talking about https://docs.rs/uuid/latest/uuid. It seems they have a support for no-std (see Embedded section), but they also have some dependencies on serde which might not be needed in the SVSM.

@cclaudio https://github.com/coconut-svsm/svsm/pull/528 is going to introduce `serde` deps in any case, so it may not be a big issue.

> @joergroedel any thoughts about start using uuid? We would need to test it, but it seems ok.

+1 on `uuid`, we also already use it in `igvmbuilder` but of course with `std`, so `no_std` need to be tested, I agree.

2025-01-22 13:01 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +const TPM_RS_PW: u32 = 0x40000009;
```
<TPMCmd/tpm/include/public/TpmTypes.h>
...
typedef UINT16 TPM_ALG_ID;
#define TYPE_OF_TPM_ALG_ID       UINT16
#define ALG_ERROR_VALUE          0x0000
#define TPM_ALG_ERROR            (TPM_ALG_ID)(ALG_ERROR_VALUE)
......
```
For some reason, bindgen can generate bindings for `ALG_ERROR_VALUE` but not for `TPM_ALG_ERROR`. All the TPM types we need are defined like `TPM_ALG_ERROR`.  Any ideas on how to fix this?

2025-01-23 16:48 UTC, gemini-15 commented
This PR does not seem to work on our end with the linux configfs-tsm tests that we've done.

While we are able to get the attestation report from the `outblob` file, the EK public key is not returned in the `manifestblob`. We also have no cert available on the `auxblob` file either. 

The attestation report extracted from `outblob` doesn't contain the hashed EK pub key in the `report_data` either. 

Some precisions about our build : 
- [x] SVSM is built with debug/release and vTPM feature enabled (when using `make`). We use this PR version for SVSM
- [x] Linux kernel used is the coconut fork https://github.com/coconut-svsm/linux and the svsm branch (fd20cbd4a899fb4dd08479d0e110894c0db4f35f)
- [x] We specify the `service_guid` to the configfs to configure it for single service attest. 

**_We are still investigating where the issue could come from._** Also the example shown above [https://github.com/hpe-security-lab/svsm-vtpm-test](https://github.com/hpe-security-lab/svsm-vtpm-test) does not work. The [configfs-tsm ABI testing](https://github.com/coconut-svsm/linux/blob/svsm/Documentation/ABI/testing/configfs-tsm) does not include any `svsm` file as shown in the example. So it might be a different kernel that this PR was tested on. 
 
Let me know if I may have missed something, and any support would be great

2025-01-24 10:52 UTC, IT302 commented
> While we are able to get the attestation report from the `outblob` file, the EK public key is not returned in the `manifestblob`.

What is the VMPL of the attestation report from `outblob`?

2025-01-24 10:52 UTC, gemini-15 commented
> > **_We are still investigating where the issue could come from._** Also the example shown above https://github.com/hpe-security-lab/svsm-vtpm-test does not work. The [configfs-tsm ABI testing](https://github.com/coconut-svsm/linux/blob/svsm/Documentation/ABI/testing/configfs-tsm) does not include any `svsm` file as shown in the example. So it might be a different kernel that this PR was tested on.
> 
> The referenced tool should be writing "svsm" into the "service_provider" file, not "1" into the "svsm" file (not sure if there are other changes needed). The tool needs to be updated to match the upstream TSM implementation as specified in the Documentation file.

Thanks for the quick response. It worked perfectly !

2025-01-24 10:53 UTC, gemini-15 commented
> > While we are able to get the attestation report from the `outblob` file, the EK public key is not returned in the `manifestblob`.
> 
> What is the VMPL of the attestation report from `outblob`?

The VMPL specified is 2

2025-01-24 11:48 UTC, IT302 commented
> > > While we are able to get the attestation report from the `outblob` file, the EK public key is not returned in the `manifestblob`.
> > 
> > 
> > What is the VMPL of the attestation report from `outblob`?
> 
> The VMPL specified is 2

It seems the attestation request is not being sent to SVSM. The PR/SVSM should only provide VMPL0 attestations, see  https://github.com/coconut-svsm/svsm/blob/main/kernel/src/greq/services.rs#L28.

The VMPL2 attestation report must have come from outside SVSM, likely from the Linux . Are you using configfs-tsm directly or via a tool like virtee snpguest? Can you ensure that the VMPL or privilege level is set to 0 when making an attestation request? See,  https://github.com/coconut-svsm/svsm/issues/589

2025-01-24 13:14 UTC, gemini-15 commented
> It seems the attestation request is not being sent to SVSM. The PR/SVSM should only provide VMPL0 attestations, see https://github.com/coconut-svsm/svsm/blob/main/kernel/src/greq/services.rs#L28.
> 
> The VMPL2 attestation report must have come from outside SVSM, likely from the Linux . Are you using configfs-tsm directly or a tool like virtee snpguest? Can you ensure that the VMPL or privilege level is set to 0 when making an attestation request? See, #589

Here is the snippet of the attestation report : 
```
AttestationReport { version: 2, guest_svn: 0, policy: GuestPolicy { .0: 196608, abi_minor: 0, abi_major: 0, smt_allowed: 1, migrate_ma_allowed: 0, debug_allowed: 0, single_socket_required: 0 }, family_id: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], image_id: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], vmpl: 0, sig_algo: 1, current_tcb: TcbVersion { bootloader: 7, tee: 0, _reserved: [0, 0, 0, 0], snp: 14, microcode: 72 }, plat_info: PlatformInfo { .0: 1, tsme_enabled: 1, smt_enabled: 0 }, _author_key_en: 0, _reserved_0: 0, report_data: [17, 65, 68, 123, 219, 76,...
```
The attestation report as you said is at VMPL 0, which is what we needed also. However, even if I specify the vmpl level at 2 in `privlevel` the attestation report sent back still is generated at VMPL0. Is this expected behavior?

2025-01-27 12:33 UTC, IT302 commented
@cclaudio @stefano-garzarella Could you please review the changes? I plan to squash everything into a single commit at the end of the review process.

2025-02-10 09:48 UTC, IT302 commented
Hey @cclaudio @stefano-garzarella ,

Just a quick heads-up—I’ve made the requested changes on my PR. When you have a moment, could you take another look? Let me know if there’s anything else I need to fix.

Thanks

Geoffrey

2025-02-10 10:08 UTC, stefano-garzarella commented
@IT302 I'm really sorry, FOSDEM and FOSDEM-flu completely messed up my plans, I'll look into it as soon as possible these days!

2025-02-12 16:58 UTC, stefano-garzarella commented on kernel/src/vtpm/tcgtpm/mod.rs
> +const TPM_RS_PW: u32 = 0x40000009;
I think it's an issue still open https://github.com/rust-lang/rust-bindgen/issues/316 :-(

2025-02-13 11:16 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        let size = self.nonce_size as usize;
Done

2025-02-13 11:16 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +    // Validate that the report is not empty
Done

2025-02-13 11:27 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +const TPM_RS_PW: u32 = 0x40000009;
We need to revisit this in a future PR once the issue is resolved.

2025-02-13 11:47 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +]);
Now on uuid crate and it seems not to be using serde.

2025-02-13 11:51 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        if !gpa.is_aligned(8) || !valid_phys_address(gpa) || gpa.crosses_page(8) {
Done

2025-02-13 12:11 UTC, IT302 commented
> @IT302 please can you squash fixup with the original commits, I find it hard to review. Also, can you resolve comments that you addressed (not sure if you can, GH is strange)

Could you please take a look again? I have squashed the commits and resolved the comments.

2025-02-13 12:13 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        return Err(SvsmReqError::unsupported_protocol());
Done

2025-02-13 12:13 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        if !gpa.is_aligned(8) || !valid_phys_address(gpa) || gpa.crosses_page(8) {
Done

2025-02-13 12:14 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +fn attest_single_vtpm(
Moved common code into a function.

2025-02-13 12:16 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        u128::from_le_bytes(self.guid)
Done

2025-02-14 04:46 UTC, cclaudio commented on kernel/src/protocols/attestation.rs
> +    report_req.extend_from_slice(&buf[..nonce.len()]);
Do we need to zero-padding the buf if nonce is smaller than USER_DATA_SIZE?

2025-02-14 04:46 UTC, cclaudio commented on kernel/src/protocols/attestation.rs
> +    let attest_op = AttestSingleServiceOp::try_from_as_ref(buffer)?;
Similar to #603. We are not returning buffer, but we are passing attest_op to a function below. Do we need to have a local copy of buffer here?

2025-02-14 04:48 UTC, cclaudio commented
I have made a few comments. Apart from that the PR looks good to me. Thanks.

2025-02-14 06:13 UTC, msft-jlange commented on kernel/src/protocols/attestation.rs
> +        let nonce = buffer.to_vec();
I don't think this code suffers from the problem you're describing.  The returned `Vec<u8>` owns the allocation containing bytes of the nonce - that's the key difference between a slice and a `Vec`.  The `Vec` is allocated and populated by the `to_vec()` call on the slice, so at that point, there is no longer a reference to guest memory.  The contents of the nonce are completely unstable prior to that copy, but once the copy is made, the `Vec` is theoretically stable because it is a separate copy.

That said, creating a slice from guest memory is UB, because the rules of pointers are such that reads are only correctly defined if you know with certainty that nobody else can be writing to the same memory while the read is happening.  Consequently, there's a good chance that the `to_vec()` call will be unable to do the right thing because the slice isn't following the memory rules.

This consistency issue is precisely why `GuestPtr<T>` exists.  The only sound way to copy memory in or out of the guest address space is to use `GuestPtr` to do so.  I believe what this code needs to do is to create a new `Vec<u8>` based on the size obtained from `guest_nonce_gpa_and_size()` and then use `GuestPtr` to copy from guest memory into the vector.  I'm not sure that the existing `GuestPtr` will work as needed over slices, so we may need to extend `GuestPtr`, but there may be a way to do it with the existing code (I haven't tried).

2025-02-15 12:17 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +    report_req.extend_from_slice(&buf[..nonce.len()]);
I made the check stricter. Nonce and USER_DATA  refer to REPORT_DATA, and that is currently defined as 64 bytes. If there are any changes in the future, the specs would have to say how to handle that.

2025-02-15 12:18 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        let nonce = buffer.to_vec();
The code is now using GuestPtr and copies guest memory into a vector .

2025-02-19 17:28 UTC, cclaudio approved these changes
LGTM

2025-02-20 09:46 UTC, stefano-garzarella approved these changes
@IT302 great work!
I left some comments, but I don't want to stop this PR, we can fix them later eventually.

2025-02-20 09:46 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
Why not just `from_bytes()` ?

I couldn't find anything in the specification, so I expect it to follow the bytes ordering of the machine (which okay, it will always be LE), but why specify it?

2025-02-20 09:46 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +    }
IIUC currently we only supports `SVSM_ATTEST_*` if the `vtpm` feature is enabled, so I find having a lot of `#[cfg(all(feature = "vtpm", not(test)))]` here a bit confusing, so I'd suggest doing one of the following:
1. create another sub-module (e.g. attestation/vtpm.mod), where to move all the vtpm stuff, so we can use the cfg macro one/two times in this file, just to include it and call it.
2. move the cfg directly in kernel/src/requests.rs where we call `attestation_protocol_request`, but I'm not sure if in the future we will support the attestation also without the vtpm

2025-02-20 22:18 UTC, deeglaze commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
This really needs to be specified by AMD because it's important ABI. RFC4122 represents a UUID in big endian

> In the absence of explicit application or presentation protocol specification to the contrary, a UUID is encoded as a 128-bit object, as follows:

Network byte order follows. Given there is no presentation specified in the SVSM documentation, we must assume big endian.

2025-02-20 23:22 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +            ekpub: None,
The EKpub can still be destroyed with TPM2_ChangeEPS and will need to be flushed from this cache. I would like to not create the EK during initialization and instead opt to report a TPM_ALG_NULL key in the service manifest if the user has not created a primary key yet. We'll need a manifest version 1 to account for multiple possible algorithms.

2025-02-20 23:24 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        self.create_ek_rsa2048()?;
I don't think compile-time configuration is appropriate. It might be okay for manifest version 0, but we'll need to allow for broader use of the TPM2 API that allows for multiple primary keys of different algorithms to be created from the same primary seed.

2025-02-21 08:18 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
The endianness refers to the order of bytes in the UUID fields, not the platform. We need the bytes_le() function to convert from GUID ( Microsoft’s implementation) to RFC 4122 UUID. Although they have the same string representation, they have different byte orders. https://docs.rs/uuid/latest/uuid/struct.Uuid.html#endianness and https://uuid.ramsey.dev/en/stable/nonstandard/guid.html#globally-unique-identifiers-guids

The spec says GUID.

2025-02-21 08:37 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +            ekpub: None,
The cached Ekpub is akin to the vTPM’s identity. TPM2_ChangeEPS should invalidate the cached EKpub in the same way it invalidates EK certificates on a hardware TPM. Users should not be able to create valid new identities.

2025-02-21 09:07 UTC, IT302 commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        self.create_ek_rsa2048()?;
The compile-time configuration would probably be for manifest version 0 only.

2025-02-21 09:14 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +    }
Most of the [cfg(all(feature = “vtpm”, not(test)))] will disappear once we add another attest service that doesn’t rely on an optionally compiled component. Maybe we can hold off on making any changes for now and figure out how to organise and provide abstraction as we add more services.

2025-02-21 19:05 UTC, deeglaze commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
The spec says GUID, not Microsoft GUID, so it is ambiguous and should follow the RFC, not Microsoft.

2025-02-21 20:28 UTC, deeglaze commented on kernel/src/protocols/attestation.rs
> +    // Currently, only the VTPM service with the GUID 0xebf176c4_2301a545_9641b4e7_dde5bfe3
```suggestion
    // Currently, only the vTPM service with the GUID 0xebf176c4_2301a545_9641b4e7_dde5bfe3
```

2025-02-21 20:28 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        // 8. Create RSA2004 EK and cache EKpub for VTPM service attestation requests
```suggestion
        // 8. Create RSA2004 EK and cache EKpub for vTPM service attestation requests
```

2025-02-21 21:55 UTC, deeglaze commented on kernel/src/vtpm/mod.rs
> +    fn create_ek_rsa2048(&mut self) -> Result<(), SvsmReqError>;
Given the current thread on the coconut mailing list, I hesitate to merge this in as the default key. Using the storage key template means requiring a more challenging make/activatecredential flow that weakens the cryptographic binding between the vTPM quote and the SEV-SNP attestation report around the service manifest.

2025-02-21 23:12 UTC, deeglaze commented on kernel/src/protocols/attestation.rs
> +
This should check that the requested version of the manifest is 0.

2025-02-24 12:39 UTC, IT302 commented on kernel/src/vtpm/mod.rs
> +    fn create_ek_rsa2048(&mut self) -> Result<(), SvsmReqError>;
I don’t think we should deviate from the norm for our default key.  I am all for the efficiency of signing EKs, but there are  key applications/scenarios where vTPMs may be associated with a human user, so per the TCG, one should use the privacy-persisting decryption EKs and MakeCredential/ActivateCredential flow. One example is Virtual Desktop Infrastructure (VDI), https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new#confidential-virtual-machines-and-trusted-launch-virtual-machines-are-now-generally-available-in-azure-virtual-desktop. 

Also, some applications (like Keylime) expect an decryption EK. Perhaps, they can bind the decryption EK to the signing EK (using TPM2_Certify instead of MakeCredential/ActivateCredential) and bind the signing EK to the TEE attestation report.  This  is an additional step though and looks more complex than just using MakeCredential/ActivateCredential.

2025-02-25 08:51 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
@tlendacky any thought on this?

2025-02-25 08:53 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +    }
@IT302 also in that case I'd like to have different sub-modules to handle them, since I'm expecting different dependencies. Any way, I agree with you that we can figure out later.

2025-02-25 10:52 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
Linux provides GUIDs. https://github.com/torvalds/linux/blob/master/drivers/virt/coco/sev-guest/sev-guest.c#L346, https://github.com/torvalds/linux/blob/master/include/linux/uuid.h#L23 . If the decision is made to change from GUID to RFC 4122 UUID, then Linux would need to be updated accordingly.

2025-02-25 17:08 UTC, tlendacky commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
I did use the guid interfaces that are in Linux for the TSM support, which is little-endian (probably because I have been working in EDK2 too much :) ). I can update the GHCB and SVSM documents to specify the representation to state little-endian.

If big-endian is really, really preferred, it will require a fix in Linux as noted.

2025-02-26 09:13 UTC, stefano-garzarella commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
@tlendacky thanks! IMHO an update in the SVSM spec should be enough.

2025-02-26 10:25 UTC, IT302 commented on kernel/src/protocols/attestation.rs
> +        Uuid::from_bytes_le(self.guid)
I agree with @stefano-garzarella

2025-02-28 03:44 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +        self.create_ek_rsa2048()?;
Can we move this create call to cache on first call of get_ekpub? It's a bit of a boot time regression to create an rsa 2048 key every boot unprompted.

2025-02-28 19:45 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +    fn create_ek_rsa2048(&mut self) -> Result<(), SvsmReqError> {
Should we instead have a prepopulation of nvdata such that 0x01c0_0004 gets populated with this template, and we can therefore have a simpler creation process that says to read the template at the NV handle and then create the primary key with empty PCR selection and passwords? This is the "low range" RSA EK template after all.

For Google's keys, we use 0x01c10001 for our AK RSA key template and 0x01c100003 for our AK ECC key template. We can more easily determine which keys we can can cache if we're requesting them by template NV index.

2025-02-28 21:29 UTC, deeglaze commented on kernel/src/vtpm/tcgtpm/mod.rs
> +    fn create_ek_rsa2048(&mut self) -> Result<(), SvsmReqError> {
Also note that we can use the tpm_rs_base type definitions from github.com/tpm-rs/tpm-rs.git to marshal/unmarshal TPM types instead of all this munging.

2025-03-18 16:07 UTC, deeglaze commented on kernel/src/protocols/attestation.rs
> +        let buffer = unsafe { gptr.read().map_err(|_| SvsmReqError::invalid_parameter())? };
This is not necessarily a newly mapped region. create_4k does not fail if there is a present entry at the given address. The valid_phys_addr check does not also rule out SVSM user space, which we don't want the guest kernel to be able to read.

I think we need a guestmem.rs addition for GuestNonUserPtr to do this extra bounds checking.

2025-04-02 02:01 UTC, deeglaze commented
I move to close this PR in favor of https://github.com/coconut-svsm/svsm/pull/662 @IT302

2025-04-09 16:28 UTC, IT302 commented
> I move to close this PR in favor of #662 @IT302

Closing

2025-04-09 16:28 UTC, closed without merging