Making zero_mem_region() and control regs helpers unsafe
coconut-svsm/svsm pull request #546
Opened 2024-12-03 17:01 UTC by p4zuu

- As described in #359, `zero_mem_region()` should be unsafe.
- Writing to control registers can violate memory safety, therefore functions writing to CR0, CR3 and CR4 should also be unsafe. This led to making `flush_tlb_global_percpu()` unsafe too. Since I don't know perfectly the TLB code, maybe it's not necessary. Comments are very welcome here. Also, if it's correct to make `flush_tlb_global_percpu()` unsafe, for consistency reason I guess we should put other TLB helpers unsafe (again, comments are welcome here).
- Inlining control regs helpers

2024-12-04 09:56 UTC, stefano-garzarella commented on kernel/src/utils/util.rs
> +/// Caller should ensure [`core::ptr::write_bytes`] safety rules with `count`
What about replacing `size` with `count` in the code?

That way it's clearer to link the comment to the code and documentation of `core::ptr::write_bytes`.

2024-12-04 17:26 UTC, p4zuu commented on kernel/src/utils/util.rs
> +/// Caller should ensure [`core::ptr::write_bytes`] safety rules with `count`
Yes, that's a good idea :)

2024-12-04 18:24 UTC, msft-jlange requested changes
Once you remove the `unsafe` marker on the TLB flush routine (for the reasons I wrote there), you can also remove `unsafe` from all of the routines that request TLB flush.

2024-12-05 09:58 UTC, p4zuu commented on kernel/src/cpu/tlb.rs
> +pub unsafe fn flush_tlb_global_percpu() {
Got it, thanks!

2024-12-05 09:59 UTC, p4zuu commented
> Once you remove the `unsafe` marker on the TLB flush routine (for the reasons I wrote there), you can also remove `unsafe` from all of the routines that request TLB flush.

Fixed now, thanks for the input Jon!

2024-12-05 10:23 UTC, p4zuu commented on kernel/src/cpu/control_regs.rs
> +/// # Safety
Sorry I missed that. I find your doc more complete than mine so I think I can simply drop my commit for unsafe control regs

2024-12-06 09:18 UTC, stefano-garzarella approved these changes

2024-12-10 11:12 UTC, merged