kernel/cpu: add safety comments
coconut-svsm/svsm pull request #584
Opened 2024-12-20 13:55 UTC by p4zuu

Safety comments for:
- `stac` and `clac` instructions
- some TSS-related pieces of GDT code
- as described in #553 `write_msr()` should be unsafe since it can break memory safety. This part is still missing two comments [here](https://github.com/p4zuu/svsm/blob/f11a86f1ecbc33550ccaf443fe74dea15dceb5ac/kernel/src/sev/msr_protocol.rs#L148) and [here](https://github.com/p4zuu/svsm/blob/f11a86f1ecbc33550ccaf443fe74dea15dceb5ac/kernel/src/sev/msr_protocol.rs#L175) in the GHCB MSR protocol where I have doubt if the MSR request is subject to breaking memory safety or not, specifically `SNP_REG_GHCB_GPA_REQ` and `SNP_STATE_CHANGE_REQ` GHCB requests. My guess is a garbage request parameter can break the platform, but does it still count as memory safety?

2024-12-20 22:13 UTC, msft-jlange commented
> I have doubt if the MSR request is subject to breaking memory safety or not, specifically `SNP_REG_GHCB_GPA_REQ` and `SNP_STATE_CHANGE_REQ` GHCB requests. My guess is a garbage request parameter can break the platform, but does it still count as memory safety?

Both of these GHCB operations can cause physical memory to be remapped (one may cause the GHCB data to appear in a different place, and one may cause memory to be remapped with a different encryption attribute).  Because both of these operations can cause mapped memory to change contents, they are technically unsafe.

2024-12-20 22:21 UTC, msft-jlange requested changes

2024-12-20 22:21 UTC, msft-jlange commented on kernel/src/cpu/gdt.rs
> +        // allocated, which is always our case.
Actually, it is not necessarily the case that a global GDT is in use here.  However, the lifetime of the GDT doesn't matter, because once the task register is loaded, only the TSS needs to remain live.  For that reason, either this whole function should be `unsafe` (because the compiler cannot prove that the lifetime of the `tss` parameter cannot be proven) or the `tss` parameter should be declared as `&'static`.  A quick experiment suggests that the latter approach is workable as long as we modify `PerCpu::load()` and `PerCpu::load_isst()` to take `&'static self`.

2024-12-20 22:21 UTC, msft-jlange commented on kernel/src/cpu/vc.rs
> +                // SAFETY: writing to TSC MSR doesn't break memory safety.
Should say `TSC_AUX MSR`.

2025-02-01 11:44 UTC, p4zuu commented
> Both of these GHCB operations can cause physical memory to be remapped (one may cause the GHCB data to appear in a different place, and one may cause memory to be remapped with a different encryption attribute).  Because both of these operations can cause mapped memory to change contents, they are technically unsafe.

Thanks for your input on this Jon, and sorry for the massively delayed update. I entered a busy relocation mode and will start working on this again in a couple of weeks hopefully.

2025-03-01 09:50 UTC, p4zuu commented
Thanks for the initial review @msft-jlange. I addressed the comments and this is open again for review

2025-03-01 10:34 UTC, p4zuu commented on kernel/src/cpu/gdt.rs
> +        // allocated, which is always our case.
That sounds good to me. It builds fine with a `&'static self` for `PerCpu::load_gdt_tss()` and `PerCpu::load()`.

2025-03-03 16:16 UTC, msft-jlange approved these changes
Thanks for returning to this PR!  These changes look good.

2025-03-06 09:09 UTC, merged