Implement the attestation report feature
coconut-svsm/svsm pull request #69
Opened 2023-08-02 05:01 UTC by cclaudio

This PR implements the attestation report feature discussed in the issue #67 

`make test` will test the main functions used to encrypt and decrypt messages.

The branch [attestation-report-test](https://github.com/cclaudio/svsm/tree/attestation-report-test) can be used to test the `get_report()` and `get_ext_report()` functions. It contains one extra patch that calls them at boot time and print some information in the log.

2023-08-02 14:12 UTC, 00xc commented on src/protocols/errors.rs
> +
Same here, `Debug` is implemented for the type, so why not use it when printing the error instead?

2023-08-02 14:50 UTC, cclaudio commented on src/protocols/errors.rs
> +
Makes sense, I will drop the commit that adds this change

2023-08-02 14:52 UTC, cclaudio commented on src/protocols/errors.rs
> +
Yep, commit dropped.

2023-08-03 09:37 UTC, stefano-garzarella commented on Makefile
> +ifdef V
`make V=0` also enable the verbose mode, so what about this:

```
ifeq ($(V), 1)
CARGO_ARGS += -v
else ifeq ($(V), 2)
CARGO_ARGS += -vv
endif
```

2023-08-03 09:37 UTC, stefano-garzarella commented on src/mm/address_space.rs
>  pub const STACK_PAGES: usize = 16;
I don't know the details, but should we increase this as well?

Pre existing: maybe it's better to define a base and increment it when the gdb stub is enabled

2023-08-03 09:37 UTC, stefano-garzarella commented on src/psp/guest_request_msg.rs
> +/* SPDX-License-Identifier: MIT */
`cargo clippy` suggests several improvements for this file:

```
warning: you should consider adding a `Default` implementation for `SnpGuestRequestMsgHdr`
   --> src/psp/guest_request_msg.rs:103:5
    |
103 | /     pub fn new() -> SnpGuestRequestMsgHdr {
104 | |         SnpGuestRequestMsgHdr {
105 | |             authtag: [0; 32],
106 | |             msg_seqno: 0,
...   |
117 | |         }
118 | |     }
    | |_____^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default
    = note: `#[warn(clippy::new_without_default)]` on by default
help: try adding this
    |
92  + impl Default for SnpGuestRequestMsgHdr {
93  +     fn default() -> Self {
94  +         Self::new()
95  +     }
96  + }
    |

warning: casting raw pointers to the same type and constness is unnecessary (`*const u8` -> `*const u8`)
   --> src/psp/guest_request_msg.rs:158:24
    |
158 |         let msg_algo = &self.algo as *const _ as *const u8;
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&self.algo as *const _`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
    = note: `#[warn(clippy::unnecessary_cast)]` on by default

warning: casting raw pointers to the same type and constness is unnecessary (`*mut u8` -> `*mut u8`)
   --> src/psp/guest_request_msg.rs:223:17
    |
223 |                 self.buffer.as_mut_ptr() as *mut u8,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.buffer.as_mut_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast

warning: use of `offset` with a `usize` casted to an `isize`
   --> src/psp/guest_request_msg.rs:233:17
    |
233 |                 self.buffer.as_mut_ptr::<u8>().offset(MSG_HDR_SIZE as isize),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.buffer.as_mut_ptr::<u8>().add(MSG_HDR_SIZE)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_offset_with_cast
    = note: `#[warn(clippy::ptr_offset_with_cast)]` on by default

warning: unsafe function's docs miss `# Safety` section
   --> src/psp/guest_request_msg.rs:239:5
    |
239 |     pub unsafe fn payload_offset(&mut self) -> *mut u8 {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc
    = note: `#[warn(clippy::missing_safety_doc)]` on by default

warning: use of `offset` with a `usize` casted to an `isize`
   --> src/psp/guest_request_msg.rs:240:9
    |
240 |         self.buffer.as_mut_ptr::<u8>().offset(MSG_HDR_SIZE as isize)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.buffer.as_mut_ptr::<u8>().add(MSG_HDR_SIZE)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_offset_with_cast

warning: casting raw pointers to the same type and constness is unnecessary (`*const u8` -> `*const u8`)
   --> src/psp/guest_request_msg.rs:265:37
    |
265 |             unsafe { from_raw_parts(plaintext.as_ptr() as *const u8, plaintext_len as usize) };
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `plaintext.as_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast

warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/psp/guest_request_msg.rs:272:34
    |
272 |         let gcm = Aes256Gcm::new(&key);
    |                                  ^^^^ help: change this to: `key`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `#[warn(clippy::needless_borrow)]` on by default

warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/psp/guest_request_msg.rs:276:38
    |
276 |         let Ok(buffer) = gcm.encrypt(&nonce, payload) else {
    |                                      ^^^^^^ help: change this to: `nonce`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/psp/guest_request_msg.rs:329:34
    |
329 |         let gcm = Aes256Gcm::new(&key);
    |                                  ^^^^ help: change this to: `key`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/psp/guest_request_msg.rs:333:38
    |
333 |         let Ok(buffer) = gcm.decrypt(&nonce, payload) else {
    |                                      ^^^^^^ help: change this to: `nonce`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

warning: manual `!RangeInclusive::contains` implementation
   --> src/psp/guest_request_msg.rs:382:12
    |
382 |         if len < PAGE_SIZE || len > SNP_GUEST_REQ_MAX_DATA_SIZE {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `!(PAGE_SIZE..=SNP_GUEST_REQ_MAX_DATA_SIZE).contains(&len)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
    = note: `#[warn(clippy::manual_range_contains)]` on by default

warning: casting to the same type is unnecessary (`usize` -> `usize`)
   --> src/psp/guest_request_msg.rs:412:31
    |
412 |                 min(buf_size, SNP_GUEST_REQ_MAX_DATA_SIZE as usize),
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `SNP_GUEST_REQ_MAX_DATA_SIZE`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast

warning: casting raw pointers to the same type and constness is unnecessary (`*const [u8; 16384]` -> `*const [u8; 16384]`)
   --> src/psp/guest_request_msg.rs:419:19
    |
419 |         let buf = self.buffer.as_ptr() as *const [u8; SNP_GUEST_REQ_MAX_DATA_SIZE];
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `self.buffer.as_ptr()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast

warning: this `.into_iter()` call is equivalent to `.iter()` and will not consume the `slice`
   --> src/psp/guest_request_msg.rs:422:32
    |
422 |         unsafe { (*buf)[..end].into_iter().all(|e| *e == 0) }
    |                                ^^^^^^^^^ help: call directly: `iter`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref
    = note: `#[warn(clippy::into_iter_on_ref)]` on by default

```

2023-08-03 09:37 UTC, stefano-garzarella commented on src/psp/guest_request_cmd.rs
> +            log::error!("Encryption: sequence number overflow");
To understand better, so when we exhaust all the sequence numbers, we will always be in error?

2023-08-03 09:37 UTC, stefano-garzarella commented on src/psp/msg_report.rs
> +/// 64
Maybe a leftover? If not, we could explain why 64

2023-08-03 09:37 UTC, stefano-garzarella commented on src/psp/request.rs
> +/* SPDX-License-Identifier: MIT */
Some tips from `cargo clippy`:

```
warning: unused import: `crate::types::PAGE_SIZE`
  --> src/psp/request.rs:17:5
   |
17 | use crate::types::PAGE_SIZE;
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `allocate_pages`, `free_page`, `get_order`
  --> src/psp/request.rs:22:24
   |
22 | use crate::mm::alloc::{allocate_pages, free_page, get_order};
   |                        ^^^^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^^^
```

2023-08-03 09:57 UTC, 00xc commented on src/psp/guest_request_msg.rs
> +    }
I think setting the `len` field is missing in this method.

2023-08-03 20:15 UTC, cclaudio commented on Makefile
> +ifdef V
Looks good. I will apply that.

2023-08-03 20:20 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +/* SPDX-License-Identifier: MIT */
Wow, I did not run `cargo clippy`. I will fix that, thanks.

2023-08-04 19:16 UTC, cclaudio commented on src/mm/address_space.rs
>  pub const STACK_PAGES: usize = 16;
I doesn't seem we need to increase it. I also don't know the details about the gdb stub, but if `STACK_PAGES` is set to at least `10` in BOTH cases, I am still able to run the attestation code successfully. That shows that we have at least 6 free pages in the stack.

I like the idea of having a base stack size and increment it when the gdb stub is enabled. That improvement could be a separate PR.

2023-08-04 19:30 UTC, cclaudio commented on src/psp/msg_report.rs
> +/// 64
That's the `REPORT_DATA` field defined in the table 20 of the spec https://www.amd.com/system/files/TechDocs/56860.pdf

```diff
diff --git a/src/psp/msg_report.rs b/src/psp/msg_report.rs
index 009cdfc0bc3b..a35cdffe1865 100644
--- a/src/psp/msg_report.rs
+++ b/src/psp/msg_report.rs
@@ -13,7 +13,8 @@ use crate::protocols::errors::SvsmReqError;
 
 use alloc::vec::Vec;
 
-/// 64
+/// REPORT_DATA (512 bits)
+/// AMD SEV-SNP ABI spec, table 20.
 pub const USER_DATA_SIZE: usize = 64;
 
 #[repr(C, packed)]
```

2023-08-04 22:33 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +    }
Definitely, yes. Good catch, thanks.

2023-08-04 22:39 UTC, cclaudio commented on Makefile
> +ifdef V
Done.

2023-08-06 15:16 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +/* SPDX-License-Identifier: MIT */
Done

2023-08-06 15:23 UTC, cclaudio commented on src/psp/request.rs
> +/* SPDX-License-Identifier: MIT */
Thanks, fixed.

2023-08-06 22:26 UTC, cclaudio commented on src/psp/guest_request_cmd.rs
> +            log::error!("Encryption: sequence number overflow");
That's right. If the sequence number reaches  `u64::MAX`, all the subsequent guest request calls (whether or not its an attestation report call) will fail with the following error:

```
[SVSM] Validating 0x0000000000800000-0x0000000000809000
[SVSM] Validating 0x000000000080a000-0x0000000000820000
[SVSM] Flash region 0 at 0x00000000ffc84000 size 00000000000037c000
[SVSM] Flash region 1 at 0x00000000ffaf5000 size 00000000000010b000
[SVSM] ERROR: Encryption: sequence number overflow
[SVSM] ERROR: get_report() failed, e=RequestError(INVALID_REQUEST)
[SVSM] ERROR: Encryption: sequence number overflow
[SVSM] ERROR: get_ext_report() failed, e=RequestError(INVALID_REQUEST)
[SVSM] [CPU 0] Virtual memory pages used: 0 * 4K, 0 * 2M
[SVSM] VMSA PA: 0x800fee3000
[SVSM] Launching Firmware
```

The sequence number is sync'ed up with the PSP firmware, so at this point I would say that both them have exhausted the sequence number for guest request messages. I believe the VMPCK0 is used only to encrypt guest messages; if not, we may want to clear it here as well. I will double check that.

2023-08-06 23:13 UTC, cclaudio commented on src/sev/secrets_page.rs
> +    pub vmpck: [[u8; VMPCK_SIZE]; VMPL_MAX],
Done

2023-08-06 23:19 UTC, cclaudio commented
Hi @stefano-garzarella and @00xc, thank you very much for the feedback. I applied the changes below and marked their threads as resolved.

```
WIP: Call get_report() and get_ext_report() for testing              <------- This commit exists only in the test branch
	- Moved "use" statements to inside the testing function
psp: Add get_report() and get_ext_report()
psp: Add SnpGuestRequestCmd
	- fixups as suggested by "cargo clippy"
	- added structure and file comments pointing out the respective table in the spec as suggested by Stefano
psp: Add SnpGuestRequestMsg
	- fixups as suggested by "cargo clippy"
	- added structure and file comments pointing out the respective table in the spec as suggested by Stefano
	- set len in the "set_len" method as suggested by Carlos
sev/secrets_page: Export the VMPCK size
	- Adding this change as a separate commit as suggested by Stefano
sev/ghcb: Add guest_request() and guest_ext_request()
protocols/errors: Implement Display for SvsmReqError
	- Dropped this commit as suggested by Carlos
mm/address_space: Increase stack size for attestation report
Makefile: Build targets in verbose mode
	- It now supports "make V=1" and "make V=2" as suggested by Stefano
```

2023-08-06 23:24 UTC, cclaudio commented on src/psp/msg_report.rs
> +/// 64
Done

2023-08-06 23:47 UTC, cclaudio commented
Hi @stefano-garzarella and @00xc, thank you very much for the feedback. I applied the changes below and marked their threads as resolved.

- **WIP: Call get_report() and get_ext_report() for testing              <------- This commit exists only in the test branch**
 	- Moved "use" statements to inside the testing function
- **psp: Add get_report() and get_ext_report()**
- **psp: Add SnpGuestRequestCmd**
 	- fixups as suggested by "cargo clippy"
 	- added structure and file comments pointing out the respective table in the spec as suggested by Stefano
- **psp: Add SnpGuestRequestMsg**
 	- fixups as suggested by "cargo clippy"
 	- added structure and file comments pointing out the respective table in the spec as suggested by Stefano
 	- set len in the "set_len" method as suggested by Carlos
- **sev/secrets_page: Export the VMPCK size**
 	- Adding this change as a separate commit as suggested by Stefano
- **sev/ghcb: Add guest_request() and guest_ext_request()**
- **protocols/errors: Implement Display for SvsmReqError**
 	- Dropped this commit as suggested by Carlos
- **mm/address_space: Increase stack size for attestation report**
- **Makefile: Build targets in verbose mode**
 	- It now supports "make V=1" and "make V=2" as suggested by Stefano

2023-08-08 08:40 UTC, stefano-garzarella commented on src/mm/address_space.rs
>  pub const STACK_PAGES: usize = 16;
> I like the idea of having a base stack size and increment it when the gdb stub is enabled. That improvement could be a separate PR.

Yep, I agree! I'll send a separate PR for that!

2023-08-08 08:40 UTC, stefano-garzarella commented on src/psp/guest_request_cmd.rs
> +            log::error!("Encryption: sequence number overflow");
Thanks for the details!

2023-08-08 08:49 UTC, stefano-garzarella approved these changes
I still need to study the details, so I may come back with new comments, but for now LGTM, I left just a minor comment.

2023-08-08 08:49 UTC, stefano-garzarella commented on Makefile
>  TARGET_PATH="debug"
nit: if you need to resend, we can update the commit description

2023-08-11 22:17 UTC, cclaudio commented on Makefile
>  TARGET_PATH="debug"
I will need to update the branch, do you have any feedback on the commit description?

2023-08-12 02:13 UTC, cclaudio commented
`attestation-report` and `attestation-report-test` branches updated (version 3):
- [PATCH] psp: Add SnpGuestRequestMsg
   - Fixed one simple indentation reported by `cargo fmt --check`
- Rebased to latest main

2023-08-12 03:08 UTC, cclaudio commented
`attestation-report` and `attestation-report-test` branches updated (version 4):
- Updated the License  of the new files to be MIT or Apache-2.0

2023-08-14 14:38 UTC, cclaudio commented on src/mm/address_space.rs
> +pub const STACK_PAGES: usize = 12 + STACK_PAGES_GDB;
I did not spend much time on that, but I can try to pinpoint it.

2023-08-18 08:42 UTC, roy-hopkins commented on src/mm/address_space.rs
> +pub const STACK_PAGES: usize = 12 + STACK_PAGES_GDB;
I've been looking into stack usage in another area of the code so I thought I'd perform a quick analysis of this to see if I could provide some further information.

With debug builds the rust compiler allocates all function local variables on the stack at function entry, so large functions that include scoped variables can consume relatively large amounts of stack. This is mostly optimised away in release builds. With that in mind, I've traced the stack usage at the start of a few of the functions in the attestation code to get an indication:

```
Debug:
test_attestation_report = 15664
get_report = 6736
send_request = 1184
encrypt_save = 1840
decrypt_get = 1856

Release:
test_attestation_report = 2336
get_report = 2560
send_request = 304
encrypt_save = 2160
decrypt_get = 2144
```

For `get_report`, `SnpReportResponse` is allocated on the stack and is 1216 bytes.
For the encrypt/decrypt functions I suspect the majority of this stack usage is down to the encryption context. The size of the `gcm` variable is 992 bytes.

2023-08-18 15:29 UTC, cclaudio commented on src/mm/address_space.rs
> +pub const STACK_PAGES: usize = 12 + STACK_PAGES_GDB;
Hi @roy-hopkins, thank you. That's very interesting, how did you measure that?

2023-08-18 16:33 UTC, roy-hopkins commented on src/psp/guest_request_msg.rs
> +        self.buffer = allocate_page()?;
Should this allocation (and the sharing of the page with the host) be released when the `SnpGuestRequestMsg` is dropped?

2023-08-18 16:33 UTC, roy-hopkins commented on src/psp/guest_request_msg.rs
> +        this_cpu_mut().get_pgtable().set_shared_4k(self.buffer)?;
As far as I can tell, clearing the C bit will allow the host to read the previous contents of the page, but the page will only contain ciphertext. Should the page be cleared at this point as a precaution though?

2023-08-18 16:34 UTC, roy-hopkins commented on src/mm/address_space.rs
> +pub const STACK_PAGES: usize = 12 + STACK_PAGES_GDB;
```
/// Get the stack usage in the current function
#[macro_export]
macro_rules! get_fn_stack_usage {
    () => {
        unsafe {
            use core::arch::asm;
            let stack_usage: u64;
            asm!("mov   %rbp, %rax
                sub   %rsp, %rax",
            out("rax") stack_usage,
            options(att_syntax));
            stack_usage
        }
    }
}
```

2023-08-18 18:52 UTC, cclaudio commented on .cargo/config.toml
> +rustflags = ["-C", "force-frame-pointers", "--cfg", "aes_force_soft", "--cfg", "polyval_force_soft"]
```
cargo build --features "default" --bin stage2
   Compiling polyval v0.6.1
   Compiling aes v0.8.3
   Compiling ghash v0.5.0
LLVM ERROR: Do not know how to split the result of this operator!

error: could not compile `polyval` (lib)
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: Do not know how to split the result of this operator!

error: could not compile `aes` (lib)
make: *** [Makefile:39: stage1/stage2.bin] Error 101
```

When I don't force software implementation, `make` fails to compile aes and polyval. That was the main reason for the flags.

I did some research and it looks like that AES_NI may not be enabled or supported in the host/guest, which can involve BIOS, kernel and QEMU/KVM setup.

One of the main benefits of using the AES_NI instruction set is performance gain. However, the performance with the software implementation seems good enough for now, we are not heavily using AES in the SVSM. I think we can address that later if AES performance becomes an issue. Does that make sense?

2023-08-18 19:11 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +        this_cpu_mut().get_pgtable().set_shared_4k(self.buffer)?;
Yep.  I will call `self.clear()` in the line 203.

2023-08-18 19:53 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +        this_cpu_mut().get_pgtable().set_shared_4k(self.buffer)?;
```diff
--- a/src/psp/guest_request_msg.rs
+++ b/src/psp/guest_request_msg.rs
@@ -198,8 +198,14 @@ impl SnpGuestRequestMsg {
         Ok(())
     }
 
-    pub fn set_shared(&self) -> Result<(), SvsmReqError> {
+    /// Make the message buffer page shared.
+    ///
+    /// If the page was previously a private page, its current data
+    /// will appear to the user as ciphertext now. We clear the page
+    /// to prevent data leakage.
+    pub fn set_shared(&mut self) -> Result<(), SvsmReqError> {
         this_cpu_mut().get_pgtable().set_shared_4k(self.buffer)?;
+        self.clear();
         Ok(())
     }

```

2023-08-18 21:02 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +        self.buffer = allocate_page()?;
That's a great question.

The attestation report is important for a user to establish trust on the confidential VM. I am not deallocating the buffer when the object is dropped just to ensure that the attestation report service will be available if there is any memory pressure in the SVSM at boot/runtime. Here we are talking about 6 pages (1 for the request, 1 for the response and 4 for the extended report data), see the `SnpGuestRequestCmd::init()` in the `guest_request_cmd.rs`

As for sharing, maybe it's not ideal to keep them shared for the guest lifetime; however, the data stored in these pages are always authenticated before consumption. The request and response data are encrypted using AES_GCM and the VMPCK0 key, which is available only for the SVSM and the PSP firmware. The extended report data is used to store a certificate chain that can also be verified.

2023-08-21 09:47 UTC, stefano-garzarella commented on Makefile
>  TARGET_PATH="debug"
I meant something like this:

```
Makefile: Add verbose modes

$ make V=1
or
$ make V=2

These can be used to easily build targets in verbose mode. That can be
helpful for debugging. Currently we support V=1 or V=2 (the biggest is
the most verbose).
```

2023-08-22 08:44 UTC, roy-hopkins commented on .cargo/config.toml
> +rustflags = ["-C", "force-frame-pointers", "--cfg", "aes_force_soft", "--cfg", "polyval_force_soft"]
I had a quick chat with Jörg about this. It _should_ be possible to use AES_NI but we would need to make sure it is enabled then save/restore SSE/AVX state when switching tasks. It is not just for performance though. I believe these instructions provide strong side channel support among other things. 

However, it seems likely that we will be adding a crypto module to the SVSM at some point so this can be addressed at that stage.

2023-08-23 14:20 UTC, cclaudio commented on .cargo/config.toml
> +rustflags = ["-C", "force-frame-pointers", "--cfg", "aes_force_soft", "--cfg", "polyval_force_soft"]
Great, thanks for checking that with him.

2023-08-30 18:22 UTC, cclaudio commented on src/mm/address_space.rs
> +pub const STACK_PAGES: usize = 12 + STACK_PAGES_GDB;
I am making a a few changes to mitigate the stack consumption.
- get_report() and get_ext_report() receives a buffer that will be used for the request and response. This way we don't need to allocate the Response structure
- encrypt_save() and decrypt_get() will call gcm to do in-place operations, hence it will not allocate extra buffers. This may not help with stack consumption but at least give us more control on memory allocation.

2023-08-31 20:15 UTC, deeglaze commented on src/psp/guest_request_msg.rs
> +    pub fn encrypt_save(
Can these cryptographic implementations be stubbed into an interface that can be instantiated from the outset? If we (Google) are to use this package, we'll be required to link with BoringSSL and use its aes implementation. I haven't done much Rust programming yet, so I'm not sure the right idiom to do this.

2023-09-03 06:19 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +    pub fn encrypt_save(
They certainly can, but I think we would need to solve other problems if we decide to do that now. 
For now I am proposing RustCrypto with a simple interface (direct call) so that we can evaluate and discuss what would be the best option.

Crypto is required in multiple places, e.g. the attestation report feature and the vTPM; however, loading libraries (C blobs) is something that we are trying to avoid for multiple reasons, e.g. security. That's another motivation to use RustCrypto in CPL0 for now. The vTPM and its required crypto we would run as a CPL3 module.

We started to discuss options to mitigate that. For example, run OpenSSL as a CPL3 module and have an interface for CPL0 and other CPL3 modules to use it. That's possible, but it adds more complexity and we would need to provide secrets (e.g. VMPCK0) to CPL3.

I submitted a talk to the Confidential Computing MC at LPC 2023 and this is one of the topics I would like to discuss. :-)

2023-09-03 06:42 UTC, cclaudio commented
Hi everyone,

I updated the branch and it's much better now.

- Improved stack consumption. Before it was requiring a stack of at least 10 pages to run, now it runs with 5 pages. Basically, now the `get_report()` provides a buffer that is used for input and output. We read the request and write the response to the buffer without allocating memory in the stack.
-  Added a new patch to fix a VM boot hang that seems to be caused the cargo log version we are using
- Updated the commit messages.
- Updated comments/documentation in the source code.
- I was suggesting to use the `sev-host-set-cert-chain` tool to load the SEV-SNP certificates, but it is now deprecated. I updated that to suggest the virtee/snphost.
-  I mentioned that I wanted to replace the RustCrypto encrypt/decrypt by the ones that encrypts/decrypts in place, but I decided not to do that because it requires `Vec::from_raw_parts` , which is highly unsafe at the moment.

2023-09-15 14:09 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +    pub fn encrypt_save(
@deeglaze, we briefly discussed crypto support last Wednesday in our first community meeting, it was a great meeting by the way. The consensus seems to be that having RustCrypto in CPL0 is ok for now as a temporary solution; later when CPL3 is supported we will need to revisit that as there is a desire to have all crypto centralized in a privileged CPL3 module. Easier FIPS certification is one of the motivations for that.

I will open an issue to start discussing how that crypto module design would look like.

2023-09-15 15:52 UTC, deeglaze commented on src/psp/guest_request_msg.rs
> +    pub fn encrypt_save(
Thanks @cclaudio, that's good news. I'm sorry to have missed the meeting, but it's on my calendar for next time.

2023-09-24 19:01 UTC, crobinso commented
>     * Added a new patch to fix a VM boot hang that seems to be caused the cargo log version we are using

FYI main branch should have that fixed with 7236a1a94108

2023-09-27 19:27 UTC, daaltobe commented on src/greq/services.rs
> +    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
Could do static assert on REPORT_RESPONSE_SIZE > REPORT_REQUEST_SIZE and only check REPORT_RESPONSE_SIZE

2023-09-27 19:29 UTC, daaltobe commented on src/greq/services.rs
> +        if (*request).vmpl() != 0 {
I might hide the details of SnpReportRequest inside this code and have callers pass in input_data only, which also avoids checking VMPL.

2023-09-28 22:05 UTC, cclaudio commented on src/greq/services.rs
> +    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
Hi @daaltobe , thanks for your feedback.

I think you're suggesting something like the diff below. That assert is creating a requirement where the response structure must always be bigger than the request, but IIUC this requirement does not exist in the spec. Could you elaborate? Maybe I'm not getting your point.

```diff
     const REPORT_REQUEST_SIZE: usize = core::mem::size_of::<SnpReportRequest>();
     const REPORT_RESPONSE_SIZE: usize = core::mem::size_of::<SnpReportResponse>();
 
-    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
+    assert!(REPORT_RESPONSE_SIZE > REPORT_REQUEST_SIZE);
+
+    if buffer.is_null() || REPORT_RESPONSE_SIZE > buffer_size {
         return Err(SvsmReqError::invalid_parameter());
     }
```

2023-09-28 22:46 UTC, cclaudio commented on src/greq/services.rs
> +        if (*request).vmpl() != 0 {
Good idea. What about this?

```diff
--- a/src/greq/msg_report.rs
+++ b/src/greq/msg_report.rs
@@ -9,7 +9,6 @@
 /// service (MSG_REPORT_REQ and MSG_REPORT_RSP).
 extern crate alloc;
 
-use crate::getter_func;
 use crate::protocols::errors::SvsmReqError;
 
 /// REPORT_DATA (512 bits)
@@ -26,7 +25,15 @@ pub struct SnpReportRequest {
 }
 
 impl SnpReportRequest {
-    getter_func!(vmpl, u32);
+    pub fn validate(&self) -> Result<(), SvsmReqError> {
+        // Attestation report with other VMPL levels can be requested
+        // by the guest kernel directly to the PSP.
+        if self.vmpl != 0 {
+            return Err(SvsmReqError::invalid_parameter());
+        }
+
+        Ok(())
+    }
 }
--- a/src/greq/services.rs
+++ b/src/greq/services.rs
@@ -47,17 +47,14 @@ fn get_report_common(
     const REPORT_REQUEST_SIZE: usize = core::mem::size_of::<SnpReportRequest>();
     const REPORT_RESPONSE_SIZE: usize = core::mem::size_of::<SnpReportResponse>();
 
     if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
         return Err(SvsmReqError::invalid_parameter());
     }
 
     let request = buffer.as_ptr::<SnpReportRequest>();
-
-    unsafe {
-        if (*request).vmpl() != 0 {
-            return Err(SvsmReqError::invalid_parameter());
-        }
-    }
+    unsafe { (*request).validate()? };

     // The SnpReportRequest structure size has to fit in the
```

2023-09-28 22:53 UTC, cclaudio commented on src/greq/services.rs
> +    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
Hmm ... `cargo clippy` recommends removing that assert as it would be optimized out by the compiler

```
warning: `assert!(true)` will be optimized out by the compiler
  --> src/greq/services.rs:50:5
   |
50 |     assert!(REPORT_RESPONSE_SIZE > REPORT_REQUEST_SIZE);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: remove it
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assertions_on_constants
   = note: `#[warn(clippy::assertions_on_constants)]` on by default

warning: `svsm` (lib) generated 1 warning

```

2023-09-28 23:08 UTC, cclaudio commented on src/greq/services.rs
> +        if (*request).vmpl() != 0 {
I will also do something similar to `encrypt_save()` and `decrypt_get()`. Currently, they are doing much more than crypto operations.

2023-09-29 09:56 UTC, roy-hopkins commented on src/psp/guest_request_msg.rs
> +        self.buffer = allocate_page()?;
Ok, yes it makes sense to keep the buffers allocated for the lifetime of the SVSM in this case. The query I had was around `SnpGuestRequestMsg` itself though. 

I can see that `SnpGuestRequestDriver` has instances of `SnpGuestRequestMsg` for the request and response, therefore the lifetime of these are tied to the lifetime of the driver and hence to the lifetime of SVSM. At the moment, `SnpGuestRequestMsg` is only used in this context. But what if it is reused elsewhere in the future? Is that likely to happen? If so, each time an instance is created then goes out of scope it will leak the allocated page. I think the page should be freed when the instance is dropped to prevent this - it would not be able to be reused in this case anyway.

2023-09-29 22:26 UTC, daaltobe commented on src/greq/services.rs
> +    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
Interesting.  Not a big deal, all I was thinking is that it was odd to read that if, since report request size is much smaller than response size.  If you didn't reuse the buffer for input and output, couldn't Rust enforce the sizes for us at compile time?

2023-09-30 00:35 UTC, deeglaze commented on src/greq/services.rs
> +        if (*request).vmpl() != 0 {
Do you have the same double-buffering I added to sev-guest to avoid side channel attacks on in-place crypto in shared memory? I saw mention of in-place crypto and got worried.

2023-10-09 14:06 UTC, joergroedel commented on src/greq/driver.rs
> +            self.ext_data.init()?;
If I checked correctly, none of the underlying types implement the drop trait. The memory allocated in these functions will be leaked if initialization fails. Can you please implement the drop trait for `SnpGuestRequestMsg` and `SnpGuestRequestExtData` so that the pages are freed and set to private again?

2023-10-09 14:16 UTC, joergroedel commented
Except for the missing Drop trait implementations this LGTM.

2023-10-11 02:30 UTC, deeglaze commented on src/sev/ghcb.rs
> +        if self.sw_exit_info_2 != 0 {
Not every nonzero sw_exit_info_2 value is fatal, such as 2 << 32, from GHCB section 4.1.7, which indicates the guest should wait and retry.

2023-10-11 02:54 UTC, deeglaze requested changes

2023-10-11 02:54 UTC, deeglaze commented on src/greq/msg.rs
> +            Aes256Gcm::decrypt(&iv, vmpck0, aad, inbuf, outbuf, outbuf_size)?;
inbuf is used directly from shared memory instead of from a copy in encrypted memory. Do we know if this decrypt operation is strong against iago attacks, such as if inbuf is read more than once during decryption, and its contents are expected to be constant throughout?

2023-10-11 02:54 UTC, deeglaze commented on src/greq/driver.rs
> +                        if extended {
Do we expect `extended` to be false when the host sends back this value? You still need to complete the PSP request for the sequence numbers to stay in sync, so why keep this guarded?

2023-10-11 02:54 UTC, deeglaze commented on src/greq/msg.rs
> +        let plaintext = unsafe { from_raw_parts(payload.as_ptr::<u8>(), plaintext_size) };
Similar comment to below about decrypt: is this encryption strong against iago attacks, or can you add the double-buffering mitigation I added to Linux's sev-guest so that all encryption is done in encrypted memory before getting written to shared memory?

2023-10-11 03:02 UTC, cclaudio commented on src/sev/ghcb.rs
> +        if self.sw_exit_info_2 != 0 {
Here the error is just returned, it is not fatal. The caller `driver::send_request()` will do the proper error handling, which includes the `SNP_GUEST_REQ_ERR_BUSY` you mentioned and the `SNP_GUEST_REQ_INVALID_LEN`.

But, yeah, that comment is misleading. Let me make two changes:
- return RBX (without multiplying it by PAGE_SIZE)
- replace the comment to something like ` On error,  RBX and sw_exit_info_2 are returned for proper error handling.`

2023-10-12 01:50 UTC, cclaudio commented on src/greq/driver.rs
> +                        if extended {
The purpose of that check is to make sure that the hypervisor error code is consistent with the request. For example, if we send a "get_report", the hypervisor should not return that the buffer is too small because we did not request the SEV-SNP certificate chain.

Actually, I think I should add an else to that check where we disable the VMPCK0 and return an error; otherwise, a malicious hypervisor could try to reuse the IV that was not sent to the PSP.

Something like this:

```diff
                    // The certificate buffer provided is too small.
                    SNP_GUEST_REQ_INVALID_LEN => {
-                        if extended {
-                            if let Err(e1) = self.send(false) {
+                        if req_class == SnpGuestRequestClass::Extended {
+                            if let Err(e1) = self.send(SnpGuestRequestClass::Regular) {
                                log::error!(
                                    "SNP_GUEST_REQ_INVALID_LEN. Aborting, request resend failed"
                                );
                                disable_vmpck0();
                                return Err(e1);
                            }
                            return Err(e);
+                        } else {
+                           // We sent a regular SNP_GUEST_REQUEST, but the hypervisor returned
+                           // an error code that is exclusive for extended SNP_GUEST_REQUEST
+                           disable_vmpck0();
+                           return Err(SvsmReqError::invalid_request());
                        }
                    }
```

2023-10-12 14:33 UTC, cclaudio commented on src/greq/msg.rs
> +        let plaintext = unsafe { from_raw_parts(payload.as_ptr::<u8>(), plaintext_size) };
Fixed in the v5 (3bb2cf4 to 1abd100)

2023-10-12 14:33 UTC, cclaudio commented on src/greq/driver.rs
> +                        if extended {
Applied to the v5 (3bb2cf4 to 1abd100)

2023-10-12 14:34 UTC, cclaudio commented on src/sev/ghcb.rs
> +        if self.sw_exit_info_2 != 0 {
Applied to the v5 (3bb2cf4 to 1abd100)

2023-10-12 14:36 UTC, cclaudio commented on src/greq/driver.rs
> +            self.ext_data.init()?;
Implemented the drop trait for both structures in the v5 (3bb2cf4 to 1abd100)

2023-10-12 14:40 UTC, cclaudio commented on src/greq/services.rs
> +        if (*request).vmpl() != 0 {
@daaltobe , I hid that vmpl check in the v5 (3bb2cf4 to 1abd100)
@deeglaze , I added double-buffering in the v5 (3bb2cf4 to 1abd100)

Thanks

2023-10-12 14:43 UTC, cclaudio commented on src/greq/services.rs
> +    if buffer.is_null() || REPORT_REQUEST_SIZE > buffer_size || REPORT_RESPONSE_SIZE > buffer_size {
I don't know. I would need to run some tests to check that.

2023-10-12 14:46 UTC, cclaudio commented on src/psp/guest_request_msg.rs
> +        self.buffer = allocate_page()?;
Implemented the drop trait for both the `SnpGuestRequestMsg` and `SnpGuestRequestExtData`  in the v5 ([3bb2cf4 ](https://github.com/coconut-svsm/svsm/commit/3bb2cf49a072d3ea23e7a99a1c1a1469eab0bba1)to [1abd100](https://github.com/coconut-svsm/svsm/commit/1abd1001613b7320e9722389beef8c69f194efb2)

2023-10-12 15:03 UTC, cclaudio commented
Thanks @crobinso @daaltobe @roy-hopkins @deeglaze  and @joergroedel for the feedback!

attestation-report and attestation-report-test branches updated (v5):
- Updated commit messages
- Perform crypto operations in a protected page (staging message)
    - 592add9c19f5631c015c02eeff72af1202abed22
-  Implemented drop trait for SnpGuestRequestMsg and SnpGuestRequestExtData
    - 5a82bc0df19f71c29045e55834a75049e0983dc0
- Introduced a crypto API for the SVSM kernel
    - 3a591449d735c86829c5183375bab7976d1b98ca
    - 9099bafce3cf790e2572293d3e0ae512c110379a
- Disable the VMPCK0 if the hypervisor returned SNP_GUEST_REQ_INVALID_LEN for a regular SNP_GUEST_REQUEST
    - 592add9c19f5631c015c02eeff72af1202abed22

2023-10-17 02:53 UTC, cclaudio commented
Rebased to the latest main branch and fixed conflicts.

2023-10-18 09:21 UTC, joergroedel requested changes
Left two comments.

2023-10-18 09:21 UTC, joergroedel commented on src/greq/msg.rs
> +            self.free_pages();
The pages can only be freed when they are set to encrypted, otherwise it is better to leak the memory. Possibly state the leak in the error message.

2023-10-18 09:21 UTC, joergroedel commented on src/greq/msg.rs
> +            free_page(self.buffer);
The page can only be freed if it was set back to encrypted state. We can not leak a shared page back into the allocator.

2023-10-18 17:05 UTC, Freax13 requested changes

2023-10-18 17:05 UTC, Freax13 commented on src/greq/msg.rs
> +pub struct SnpGuestRequestExtData {
In it's current state, this data structure doesn't seem sound to me:
1. There's nothing stopping the user from calling `init` multiple times and leaking memory.
2. `set_len` allows the user to freely set any value. We can no longer rely on `len` being accurate. `set_len` should either be made unsafe or removed.
3. `ncopy_to` shouldn't take `outbuf` and `outbuf_size` like that. This is really unidiomatic for Rust code. This function should either be unsafe or not take `outbuf` and `outbuf_size` like that. Maybe a slice could work? This problem also occurs with other functions added in this pr.

2023-10-18 17:05 UTC, Freax13 commented on src/greq/msg.rs
> +    fn set_authtag(&mut self, tag: VirtAddr) {
This function should take a `tag: &[u8; 32]` (or `&[u8]`).

2023-10-18 17:10 UTC, Freax13 commented on src/crypto/rustcrypto.rs
> +    };
```suggestion
    let buffer = result.map_err(|_| SvsmReqError::invalid_format())?;
```

2023-10-18 17:13 UTC, Freax13 commented on src/greq/services.rs
> +        log::error!("SNP_GUEST_REQUEST driver failed to initialize, e={:?}", e);
```suggestion
        log::error!("SNP_GUEST_REQUEST driver failed to initialize, e={e:?}");
```

2023-10-18 18:42 UTC, cclaudio commented on src/greq/msg.rs
> +            self.free_pages();
Makes sense. I will state the leak in the error message and return just after that.

2023-10-18 18:42 UTC, cclaudio commented on src/greq/msg.rs
> +            free_page(self.buffer);
Same here, I will state the leak in the error message and return just after that. Thank you.

2023-10-20 13:36 UTC, cclaudio commented on src/greq/msg.rs
> +    fn set_authtag(&mut self, tag: VirtAddr) {
Makes sense. I will change it to take `tag: &[u8; 32]`. Thanks.

2023-10-20 13:37 UTC, cclaudio commented on src/crypto/rustcrypto.rs
> +    };
Thanks, I will apply that.

2023-10-20 13:52 UTC, cclaudio commented on src/greq/services.rs
> +        log::error!("SNP_GUEST_REQUEST driver failed to initialize, e={:?}", e);
I will apply that, thanks.

2023-10-20 15:34 UTC, cclaudio commented on src/greq/msg.rs
> +pub struct SnpGuestRequestExtData {
Thanks @Freax13, these are all good points. To begin with, I can improve the documentation of `SnpGuestRequestExtData` to better convey its purpose.

1. To prevent that I could check if the buffer was already initialized a the beginning of the `init()`, but that does not seem a good idea because I would need to do the same thing in almost all other methods. Ideally, I should have the `static GREQ_DRIVER` initialized on first use by using `lazzy_static` (or `once_cell`) something like the diff below. With that, I think I could just refactor the `init()` to become `new()` in both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`. Additionally, I could remove `greq_driver_init()`.
    - ```diff
      -/// `SNP_GUEST_REQUEST` driver.
      -/// The PSP accepts only one `SNP_GUEST_REQUEST` command at a time
      -static GREQ_DRIVER: SpinLock<SnpGuestRequestDriver> =
      -    SpinLock::new(SnpGuestRequestDriver::default());
      +lazy_static! {
      +    /// `SNP_GUEST_REQUEST` driver.
      +    /// The PSP accepts only one `SNP_GUEST_REQUEST` command at a time
      +    static ref GREQ_DRIVER: SpinLock<SnpGuestRequestDriver> =
      +        SpinLock::new(SnpGuestRequestDriver::new());
      +}
      ```
- Indeed, `set_len()` does not seem a good method name. The idea behind it is that we need to know whether or not the buffer provided in `get_ext_report()` has enough pages to hold the certificates data, however, only the hypervisor is able to check that. If it is not large enough, the hypervisor will return the number of pages required in RBX. I can change the method name to `set_max_len()` and the field to `max_len` - Note that `max_len` is the actual buffer size we provide to the hypervisor. Additionally, I can make the method `unsafe`
-  I will refactor the parameter be a slice. I should probably do the same with the buffer field in both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`, actually the buffer field could be a sized slice.

2023-10-20 19:05 UTC, Freax13 commented on src/greq/msg.rs
> +pub struct SnpGuestRequestExtData {
> Thanks @Freax13, these are all good points. To begin with, I can improve the documentation of `SnpGuestRequestExtData` to better convey its purpose.
> 
>   1. To prevent that I could check if the buffer was already initialized a the beginning of the `init()`, but that does not seem a good idea because I would need to do the same thing in almost all other methods. Ideally, I should have the `static GREQ_DRIVER` initialized on first use by using `lazzy_static` (or `once_cell`) something like the diff below. With that, I think I could just refactor the `init()` to become `new()` in both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`. Additionally, I could remove `greq_driver_init()`.
>        
>        * ```diff
>          -/// `SNP_GUEST_REQUEST` driver.
>          -/// The PSP accepts only one `SNP_GUEST_REQUEST` command at a time
>          -static GREQ_DRIVER: SpinLock<SnpGuestRequestDriver> =
>          -    SpinLock::new(SnpGuestRequestDriver::default());
>          +lazy_static! {
>          +    /// `SNP_GUEST_REQUEST` driver.
>          +    /// The PSP accepts only one `SNP_GUEST_REQUEST` command at a time
>          +    static ref GREQ_DRIVER: SpinLock<SnpGuestRequestDriver> =
>          +        SpinLock::new(SnpGuestRequestDriver::new());
>          +}
>          ```

In this case you can also use [`core::cell::OnceCell`](https://doc.rust-lang.org/core/cell/struct.OnceCell.html) in something like `SpinLock<OnceCell<SnpGuestRequestDriver>>`. Regardless of the container, we should probably make sure that any `SnpGuestRequestDriver` is always initialized: As you pointed out, checking that the buffer is initialized in every method is very verbose, so we if we can make sure instances of `SnpGuestRequestDriver` are always initialized, we don't need to worry about that.

>   2. Indeed, `set_len()` does not seem a good method name. The idea behind it is that we need to know whether or not the buffer provided in `get_ext_report()` has enough pages to hold the certificates data, however, only the hypervisor is able to check that. If it is not large enough, the hypervisor will return the number of pages required in RBX. I can change the method name to `set_max_len()` and the field to `max_len` - Note that `max_len` is the actual buffer size we provide to the hypervisor. Additionally, I can make the method `unsafe`

I took another look at `set_len` and it turned out that my initial concern with this function was unwarranted, I somehow completely missed the `if !(PAGE_SIZE..=SNP_GUEST_REQ_MAX_DATA_SIZE).contains(&len) {` check. My apologies.
`set_max_len` seems like a good descriptive name.

>   3. I will refactor the parameter be a slice. I should probably do the same with the buffer field in both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`, ...

Sounds good to me :)

> ... actually the buffer field could be a sized slice.

I'm not completely sure what you have in mind here, but keep in mind that you have to make sure that the hypervisor can never change memory that Rust expects to be immutable.

2023-10-29 15:58 UTC, cclaudio commented
Thanks @Freax13 and @joergroedel for the feedback. In the last branch update (v6 - from [afd7c4b ](https://github.com/coconut-svsm/svsm/commit/afd7c4bc99dc6b4fa4e4917642aaa3f5f67d6a25)to [30c556e](https://github.com/coconut-svsm/svsm/commit/30c556e2b29c36374c3289695d5bfad0e11446c9)), I addressed all the changes you suggested.

* Replaced all `VirtAddr` parameters by a slice in almost all patches
* Replaced the `VirtAddr` fields in the driver by `Option<&mut ...>`. This sounds more rust idiomatic and with that the rust compiler can help us detecting syntax/semantic issues with the fields. 
* Moved driver related code from `services.rs` and `msg.rs` to `driver.rs`, including the static driver instance
* Refactored the static driver instance to be `static GREQ_DRIVER: SpinLock<OnceCell<SnpGuestRequestDriver>> = SpinLock::new(OnceCell::new());`
* Updated the code to only free pages if they are encrypted
* Updated the documentation

The test branch was also updated accordingly.

2023-10-29 20:11 UTC, Freax13 requested changes

2023-10-29 20:11 UTC, Freax13 commented on src/greq/msg.rs
> +        self.data[..n].fill(0);
```suggestion
        self.data
            .get_mut(..n)
            .ok_or_else(SvsmReqError::invalid_parameter)?
            .fill(0);
```
Also applies to `copy_to_slice` and `is_nclear`.

2023-10-29 20:11 UTC, Freax13 commented on src/greq/pld_report.rs
> +        };
```suggestion
        let request = unsafe { &*buffer.as_ptr().cast::<SnpReportRequest>() };
```

2023-10-29 20:11 UTC, Freax13 commented on src/greq/pld_report.rs
> +        };
```suggestion
        let response: &SnpReportResponse = unsafe { &*buffer.as_ptr().cast::<SnpReportResponse>() };
```

2023-10-29 20:11 UTC, Freax13 commented on src/greq/pld_report.rs
> +#[repr(C)]
This needs to be `repr(C, packed)` if we want to create references from unaligned byte slices.

2023-10-30 15:02 UTC, cclaudio commented on src/crypto/rustcrypto.rs
> +    unsafe { copy_nonoverlapping(buffer.as_ptr(), outbuf.as_mut_ptr(), buffer.len()) };
Nice, I will apply this to other places too. Thanks.

2023-10-30 18:48 UTC, cclaudio commented on src/greq/pld_report.rs
> +        };
I will apply the same idea to `SnpGuestRequestDriver::new()` as well, thanks.

2023-11-06 05:06 UTC, cclaudio commented on src/greq/driver.rs
> +            disable_vmpck0();
Although we call `disable_vmpck0` for multiple error cases, they are very specific and they not necessarily cause panic.

2023-11-06 05:08 UTC, cclaudio commented on src/greq/driver.rs
> +}
I moved them to `mm/pagetable.rs`, except the `free_pages_4k` which is no longer needed.

2023-11-06 05:33 UTC, cclaudio commented
Thanks @Freax13 for the feedback. All changes applied.
- Added `packed` to the structs in `pld_report.rs`
- Refactored the `msg.rs` and `driver.rs` to get a slice range using `get()` and `get_mut()`
- Moved functions that handle the C-bit to `mm/pagetable`, as a separate patch
- Refactored `SnpGuestRequestDriver` struct fields to be `Box<STRUCT>` rather than just `&mut STRUCT`. To support that, I added the methods `.boxed_new()`, `.set_encrypted()` and `.set_shared()` to the `SnpGuestRequestMsg` and `SnpGuestRequestExtData` structs. The `boxed_new()` allocates the object directly in the heap without going through the stack.

2023-11-06 05:57 UTC, cclaudio commented on src/greq/msg.rs
> +            // zeros here or earlier (e.g. alloc_zeroed, allocate_zeroed_page)
The current implementation is working now because the driver initializes its buffers for every message sent to the PSP.

However, I'd like to call your attention to this just in case you know how to fix it. Usually, invalid parameter in this context usually mean memory not page aligned or not shared with the hypervisor.

2023-11-06 05:58 UTC, cclaudio commented on src/greq/msg.rs
> +            // zeros here or earlier (e.g. alloc_zeroed, allocate_zeroed_page)
Same for `SnpGuestRequestExtData::boxed_new()`

2023-11-06 14:22 UTC, osteffenrh commented
Hi @cclaudio,

the current state of this PR seems to end up in a deadlock for me,
trying to acquire the `ROOT_MEM` lock.
I am using your [attestation-report-test](https://github.com/cclaudio/svsm/tree/attestation-report-test) branch.
It gets stuck in `test_get_regular_report()`.

GDB session:
```
[...]
#1  0xffffff80000066ce in svsm::svsm_main () at src/svsm.rs:479
479	    debug_break();   // added by me.
(gdb) s
70	    }
(gdb) s
svsm::svsm_main () at src/svsm.rs:480
480	    test_get_regular_report();
(gdb) s
svsm::greq::services::test_get_regular_report () at src/greq/services.rs:31
31	    let vaddr = allocate_zeroed_page().unwrap();
(gdb) s
svsm::mm::alloc::allocate_zeroed_page () at src/mm/alloc.rs:772
772	    ROOT_MEM.lock().allocate_zeroed_page()
(gdb) s
svsm::locking::spinlock::SpinLock<svsm::mm::alloc::MemoryRegion>::lock<svsm::mm::alloc::MemoryRegion>
    (self=0xffffff800010cd60 <svsm::mm::alloc::ROOT_MEM::h3d8003dc93a1d738>)
    at src/locking/spinlock.rs:58
58	        let ticket = self.current.fetch_add(1, Ordering::Relaxed);
(gdb) s

 < guest and gdb session hang >

```

2023-11-06 16:18 UTC, cclaudio commented
> Hi @cclaudio,
> 
> the current state of this PR seems to end up in a deadlock for me, trying to acquire the `ROOT_MEM` lock. I am using your [attestation-report-test](https://github.com/cclaudio/svsm/tree/attestation-report-test) branch. It gets stuck in `test_get_regular_report()`.
> 
> GDB session:
> 
> ```
> [...]
> #1  0xffffff80000066ce in svsm::svsm_main () at src/svsm.rs:479
> 479	    debug_break();   // added by me.
> (gdb) s
> 70	    }
> (gdb) s
> svsm::svsm_main () at src/svsm.rs:480
> 480	    test_get_regular_report();
> (gdb) s
> svsm::greq::services::test_get_regular_report () at src/greq/services.rs:31
> 31	    let vaddr = allocate_zeroed_page().unwrap();
> (gdb) s
> svsm::mm::alloc::allocate_zeroed_page () at src/mm/alloc.rs:772
> 772	    ROOT_MEM.lock().allocate_zeroed_page()
> (gdb) s
> svsm::locking::spinlock::SpinLock<svsm::mm::alloc::MemoryRegion>::lock<svsm::mm::alloc::MemoryRegion>
>     (self=0xffffff800010cd60 <svsm::mm::alloc::ROOT_MEM::h3d8003dc93a1d738>)
>     at src/locking/spinlock.rs:58
> 58	        let ticket = self.current.fetch_add(1, Ordering::Relaxed);
> (gdb) s
> 
>  < guest and gdb session hang >
> ```

Hi @osteffenrh, thanks for the feedback. The PR seems to be working for me with  and without `enable-gdb`. 
- Does it hang for you on every boot?
- How are you connecting gdb to the guest? I can't see that `[SVSM] * Waiting for connection from GDB *` message.
- Are you running the latest svsm kernel branch in the guest kernel? It includes some patches from Tom Lendacky that could help with that.

2023-11-06 16:19 UTC, Freax13 commented on src/greq/msg.rs
> +            // zeros here or earlier (e.g. alloc_zeroed, allocate_zeroed_page)
I don't think this is related to the actual content of the page. I also get error 22 if I replace `alloc` with `allocate_page`.

2023-11-06 16:31 UTC, roy-hopkins commented
Hi @osteffenrh, I suspect the hang on the lock is due to the fact that the GDB stub borrows the same functions as the code it is debugging, often resulting in deadlocks if you try to single step over lock code. You can try setting breakpoints instead after the lock has been taken. That normally works.

Having said that, I tried running the latest code from this PR this morning, albeit merged into my own development branch. I found that it was hanging on the call to `test_get_regular_report()` too. The problem was traced to `SnpGuestRequestMsg::set_shared()` which clears the C bit from the message buffer but was not informing the hypervisor that the encryption state has changed. I'll add a review comment with a suggested fix.

2023-11-06 16:37 UTC, Freax13 commented
> The problem was traced to `SnpGuestRequestMsg::set_shared()` which clears the C bit from the message buffer but was not informing the hypervisor that the encryption state has changed. I'll add a review comment with a suggested fix.

Informing the hypervisor about the encryption state change also seems to fix https://github.com/coconut-svsm/svsm/pull/69#discussion_r1382813034 for me.

2023-11-06 16:39 UTC, roy-hopkins commented on src/greq/msg.rs
> +            .map_err(|_| SvsmReqError::invalid_request())
I cannot see where the hypervisor is informed of the encrypted state change for this memory. On my test system this resulted in a lockup when the memory contents were written.

I fixed it with the following temporary code:
```suggestion
        let vaddr = VirtAddr::from(self as *mut Self);
        this_cpu_mut()
            .get_pgtable()
            .set_shared_4k(vaddr)
            .map_err(|_| SvsmReqError::invalid_request())?;

        let paddr = virt_to_phys(vaddr);
        this_cpu_mut()
            .ghcb()
            .page_state_change(
                paddr,
                paddr + PAGE_SIZE,
                PageSize::Regular,
                PageStateChangeOp::PscShared,
            )
            .map_err(|_| SvsmReqError::invalid_request())
```

This also needs to be done in `set_encrypted()` and the corresponding `range` functions in the same module.

2023-11-06 16:50 UTC, tlendacky commented on src/greq/msg.rs
> +            .map_err(|_| SvsmReqError::invalid_request())
Arguably, the page state change should be done by the set_shared_4k() and set_encrypted_4k() (set_private_4k ? ) so that every caller of those functions doesn't have to then make the page state change call.

2023-11-06 16:53 UTC, Freax13 commented on src/greq/driver.rs
> +    request: Box<SnpGuestRequestMsg>,
This is technically unsound. Rust assumes that the memory pointed to in those `Box`es behave according to it's ownership rules, but given that they are shared, the host can mess with the memory in a way that Rust doesn't allow.

2023-11-06 16:53 UTC, Freax13 commented on src/greq/driver.rs
> +            disable_vmpck0();
Sure, I'm not saying that they cause a panic. I'm just saying that if some other code in the SVSM panicked (e.g. because an attacker is trying to exploit the SVSM), the SVSM's state might be messed up, so we might also also consider erasing the keys to prevent exploits.

2023-11-06 16:53 UTC, Freax13 commented on src/greq/msg.rs
> +    }
If we derive `Clone` & `Copy` for `SnpGuestRequestMsg`, we can get rid of the unsafe by simply doing `*self = *src`.

2023-11-06 16:53 UTC, Freax13 commented on src/greq/msg.rs
> +            core::mem::forget(boxed);
This doesn't do anything, does it?

2023-11-06 16:53 UTC, Freax13 commented on src/greq/msg.rs
> +    // this is a large object
Do we really need to avoid copying from the stack here? I replaced this function's body with
```rust
        Ok(Box::new(Self {
            hdr: Default::default(),
            pld: [0; MSG_PAYLOAD_SIZE],
        }))
```
and didn't hit any errors.

2023-11-06 17:15 UTC, cclaudio commented on src/greq/msg.rs
> +    }
OK, I can derive Copy and Clone again for both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`. These are big structs, is there a situation where copying values could lead to more stack consumption?

2023-11-06 17:18 UTC, Freax13 commented on src/greq/msg.rs
> +    }
> OK, I can derive Copy and Clone again for both `SnpGuestRequestMsg` and `SnpGuestRequestExtData`. These are big structs, is there a situation where copying values could lead to more stack consumption?

No

2023-11-06 17:37 UTC, cclaudio commented on src/greq/msg.rs
> +    // this is a large object
What would happen if there isn't space available in the stack for that object? I have seen cases where the SVSM just hangs and then when I increase the stack the code just works again.

The PR uses two big structs: `SnpGuestRequestMsg` and `SnpGuestRequestExtData`, which is 1 page and 4 pages respectively. Should we allocate both in the stack and then copy to a Box?

2023-11-06 17:45 UTC, cclaudio commented on src/greq/msg.rs
> +            core::mem::forget(boxed);
If we can't set the page(s)  back to encrypted, @joergroedel mentioned that it would be better to leak the memory to avoid returning shared pages to the allocator.

With the code above, I would expect `boxed` to take ownership over the `self` and the `forget(boxed)` would run `let _ = ManuallyDrop::new(boxed)` preventing the boxed drop from being called and so leaking the memory. It would be good to have a test case for that, but I don't know how we can test that.

2023-11-06 17:50 UTC, cclaudio commented on src/greq/driver.rs
> +            disable_vmpck0();
> Sure, I'm not saying that they cause a panic. I'm just saying that if some other code in the SVSM panicked (e.g. because an attacker is trying to exploit the SVSM), the SVSM's state might be messed up, so we might also also consider erasing the keys to prevent exploits.

Oh, got it! I will call `disable_vmpck0` from the panic handler too. Thanks

2023-11-06 18:38 UTC, cclaudio commented on src/greq/driver.rs
> +    request: Box<SnpGuestRequestMsg>,
Indeed. One interesting thing I like about `Box<SnpGuestRequestMsg>` is that it implies that the object is stored in the heap and the Box drop() takes care of freeing the memory.

I am wondering if it makes sense to continue using Box, but do something like `let req = ManuallyDrop::new(request)` before handing it over to the hypervisor and do something like `request = req.take()` when the hypervisor returns it to us.

Another option is to go back to `Option<&mut SnpGuestRequestMsg>` and then allocate and free pages in the driver new() and drop().

Which one sounds better to you?

2023-11-06 19:23 UTC, Freax13 commented on src/greq/msg.rs
> +            core::mem::forget(boxed);
`boxed` sort of takes ownership of `self` in the sense that it would deallocate the memory if the box were dropped (which is of course doesn't happen here because boxed is forgotten), but it doesn't take ownership away from the `Box` that also owns this memory. As is, those two lines don't do anything.

2023-11-06 19:43 UTC, Freax13 commented on src/greq/msg.rs
> +    // this is a large object
You may be right, I don't know what happens if we run out of stack space.

2023-11-06 19:48 UTC, Freax13 commented on src/greq/driver.rs
> +    request: Box<SnpGuestRequestMsg>,
But then again, this wouldn't be the only code sharing mutable references with the host. The current GHCB abstractions suffer from the exact same problem. Maybe we should merge the incorrect implementation first and then clean them up later. This pr has been open for a long time already, maybe it's better to merge it and then address some of the problems in later prs.

2023-11-07 21:55 UTC, cclaudio commented on src/greq/msg.rs
> +            .map_err(|_| SvsmReqError::invalid_request())
For now I am changing the page state like in the code snippet above.

I tried to do that in the `set_shared_4k` and `set_encrypted_4k`, but that causes a `error: kvm run failed Invalid argument`

2023-11-08 06:50 UTC, cclaudio commented on src/greq/msg.rs
> +            // zeros here or earlier (e.g. alloc_zeroed, allocate_zeroed_page)
This issue disappeared now that we are informing the hypervisor that the encrypted state of the pages have changed. So, now I am calling `alloc_zeroed` without any issues.

2023-11-08 06:56 UTC, cclaudio commented on src/greq/driver.rs
> +    request: Box<SnpGuestRequestMsg>,
Ok, I am fine with that. Thanks for the feedback.

2023-11-08 07:31 UTC, cclaudio commented
Thanks @osteffenrh @roy-hopkins @Freax13 @tlendacky  for the feedback. 

Changes included in this branch update:
- We were leaking the shared memory in the drop of `SnpGuestRequestMsg` and `SnpGuestRequestExtData`. I moved that code  to the drop of the Driver so that we can leak the Box rather than the self of the aforementioned structs.
- Using the Copy trait for copying the `SnpGuestRequestMsg` and `SnpGuestRequestMsgHdr`. Removed the `copy_from()`
- Informing the hypervisor when we change the encrypted state of pages.
    - Calling `page_state_change()` directly in the `set_encrypted_4k()` and `set_shared_4k()` functions crashes the guest "error: kvm run failed Invalid Argument". It looks like that these functions are called in multiple places and one or more of them are not happy with the `page_state_change()`. So, for now, I think it is better to call `page_state_change()` directly in the driver code.
- Calling `alloc_zeroed()` to allocate memory for the boxes. The PSP is no longer returning the error 22 now that we are informing the hypervisor when we change the encrypted state of pages
- Disable the VMPCK0 in the panic handler. New patch.

2023-11-20 14:55 UTC, merged

2023-11-20 14:55 UTC, joergroedel commented
Merged manually, thanks. Any pending feedback can be addressed on-top.