Add initial Address allocator implementation
coconut-svsm/svsm pull request #77
Opened 2023-08-24 07:36 UTC by joergroedel

The address allocator uses a first-fit algorithm and an RBTree as its data structure. This is just a start, more features will be needed in the future, but here is the initial version for review.

2023-08-29 08:16 UTC, 00xc requested changes
As per Carlos Bilbao's RFC on the mailing list, `pub` structs and methods should have some documentation.

2023-08-29 08:17 UTC, 00xc commented on src/mm/address_ranges.rs
> +intrusive_adapter!(RangeAdapater<T> = Box<Range<T>>: Range::<T> { link: Link });
Small typo, should be `RangeAdapter`

2023-08-29 08:20 UTC, 00xc commented on src/mm/address_ranges.rs
> +            let node = cursor.get().unwrap();
This is equivalent and avoids an unwrap:

```rust
while let Some(node) = cursor.get() {
    ...
}
```

2023-08-29 08:24 UTC, 00xc commented on src/mm/address_ranges.rs
> +    pub fn alloc(&mut self, size: usize, data: T) -> Option<usize> {
Maybe the return value should be a `VirtAddr`? Same with the input for `free()` and `get()`

2023-08-29 12:14 UTC, joergroedel commented on src/mm/address_ranges.rs
> +intrusive_adapter!(RangeAdapater<T> = Box<Range<T>>: Range::<T> { link: Link });
Fixed, thanks.

2023-08-29 12:15 UTC, joergroedel commented on src/mm/address_ranges.rs
> +            let node = cursor.get().unwrap();
Yes, this is better, thanks. Changed it.

2023-08-29 12:15 UTC, joergroedel commented on src/mm/address_ranges.rs
> +    pub fn alloc(&mut self, size: usize, data: T) -> Option<usize> {
Converted to VirtAddr.

2023-08-31 09:24 UTC, joergroedel commented
During further development I realized that a separate generic address allocator is not the best way, because it will cause a lot of issues with locking. Going forward it will be integrated into the data structure that also keeps track of virtual memory mappings and page-tables. So I close this PR for now, the code here will be submitted as part of another PR.

2023-08-31 09:24 UTC, closed without merging